/* Generated by QOCOGEN on 03/31/2026 22:46:51 */
/* Copyright (c) 2025, Govind M. Chari <govindchari1@gmail.com> */
/* This source code is licensed under the BSD 3-Clause License  */

#ifndef QOCO_CUSTOM_LDL_H
#define QOCO_CUSTOM_LDL_H

#include "kkt.h"
#include "utils.h"
#include "workspace.h"

void ldl(Workspace* work);

// Solves L*D*L'*xyzbuff = kkt_rhs.
void tri_solve(Workspace* work);

// Solves L*D*L'*xyz = kkt_rhs with iterative refinement.
void kkt_solve(Workspace* work);
#endif