
/*
Auto-generated by CVXPYgen on March 02, 2026 at 15:02:13.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include <time.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_sqrt_tau(1.41421356237309514547);
  cpg_update_tau(2.00000000000000000000);
  cpg_update_sqrt_tau_xq_goal(0, 0.70710678118654757274);
  cpg_update_tau_lamb(10000.00000000000000000000);
  cpg_update_start_pos(0, 1.00000000000000000000);
  cpg_update_end_pos(0, 0.50000000000000000000);
  cpg_update_A_discrete(0, 0.99999086249136159843);
  cpg_update_B_discrete(0, 0.00000178271166414467);
  cpg_update_y_discrete(0, 0.00190589104020324205);
  cpg_update_ox_cvxpy(0, 1.00000227609303249388);
  cpg_update_ou_cvxpy(0, -0.33979467468866253466);
  cpg_update_etta(0.00000762939453125000);
  cpg_update_inv_Jb_S_b_scaling(0, 0.34908455161710033599);
  cpg_update_inv_Jb_c_b_scaling(0, -0.17350332446085925397);
  cpg_update_omegab_max(0.17453292519943294780);
  cpg_update_inv_JW_S_W_scaling(0, 1675.51608191455625274102);
  cpg_update_inv_JW_c_W_scaling(0, -837.75804095727812637051);
  cpg_update_speedW_max(837.75804095727812637051);
  cpg_update_S_u_scaling(0, 0.00020000000000000001);
  cpg_update_c_u_scaling(0, -0.00010000000000000000);
  cpg_update_torqW_max(0.00100000000000000002);
  cpg_update_Fth_max(0.00063199999999999997);

  // Solve the problem instance
  double start = clock();
  cpg_solve();
  double  end = clock();

  double cpu_time_used = ((double)(end - start)) / CLOCKS_PER_SEC;

  printf("obj = %f\n", CPG_Result.info->obj_val);
  
  printf("Solver time = %.1f ms\n", cpu_time_used*1000);

  return 0;

  return 0;

}
