
/*
Auto-generated by CVXPYgen on April 18, 2026 at 11:57:16.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    double sqrt_tau;
    double sqrt_tau_sqrt_lamb;
    std::array<double, 273> sqrt_tau_sqrt_lamb_ox;
    double sqrt_tau_sqrt_lamb_etta;
    std::array<double, 819> sqrt_tau_sqrt_lamb_C_discrete;
    std::array<double, 63> sqrt_tau_sqrt_lamb_z_discrete;
    std::array<double, 169> sqrt_tau_sqrt_lamb_S_x_scaling;
    std::array<double, 13> sqrt_tau_sqrt_lamb_c_x_scaling;
    double sqrt_tau_sqrt_lamb_vel_max;
    double sqrt_tau_sqrt_lamb_omega_max;
    std::array<double, 13> start_pos;
    std::array<double, 13> end_pos;
    std::array<double, 3380> A_discrete;
    std::array<double, 1560> B_discrete_l;
    std::array<double, 1560> B_discrete_r;
    std::array<double, 260> y_discrete;
    std::array<double, 36> S_u_scaling;
    std::array<double, 6> c_u_scaling;
    double acc_max;
    double torq_max;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool sqrt_tau;
    bool sqrt_tau_sqrt_lamb;
    bool sqrt_tau_sqrt_lamb_ox;
    bool sqrt_tau_sqrt_lamb_etta;
    bool sqrt_tau_sqrt_lamb_C_discrete;
    bool sqrt_tau_sqrt_lamb_z_discrete;
    bool sqrt_tau_sqrt_lamb_S_x_scaling;
    bool sqrt_tau_sqrt_lamb_c_x_scaling;
    bool sqrt_tau_sqrt_lamb_vel_max;
    bool sqrt_tau_sqrt_lamb_omega_max;
    bool start_pos;
    bool end_pos;
    bool A_discrete;
    bool B_discrete_l;
    bool B_discrete_r;
    bool y_discrete;
    bool S_u_scaling;
    bool c_u_scaling;
    bool acc_max;
    bool torq_max;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 126> u;
    std::array<double, 273> x;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 13> d0;
    std::array<double, 13> d1;
    std::array<double, 13> d2;
    std::array<double, 13> d3;
    std::array<double, 13> d4;
    std::array<double, 13> d5;
    std::array<double, 13> d6;
    std::array<double, 13> d7;
    std::array<double, 13> d8;
    std::array<double, 13> d9;
    std::array<double, 13> d10;
    std::array<double, 13> d11;
    std::array<double, 13> d12;
    std::array<double, 13> d13;
    std::array<double, 13> d14;
    std::array<double, 13> d15;
    std::array<double, 13> d16;
    std::array<double, 13> d17;
    std::array<double, 13> d18;
    std::array<double, 13> d19;
    std::array<double, 13> d20;
    std::array<double, 13> d21;
    double d22;
    double d23;
    double d24;
    double d25;
    double d26;
    double d27;
    double d28;
    double d29;
    double d30;
    double d31;
    double d32;
    double d33;
    double d34;
    double d35;
    double d36;
    double d37;
    double d38;
    double d39;
    double d40;
    double d41;
    double d42;
    double d43;
    double d44;
    double d45;
    double d46;
    double d47;
    double d48;
    double d49;
    double d50;
    double d51;
    double d52;
    double d53;
    double d54;
    double d55;
    double d56;
    double d57;
    double d58;
    double d59;
    double d60;
    double d61;
    double d62;
    double d63;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
