
/*
Auto-generated by CVXPYgen on March 31, 2026 at 22:47:08.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_sqrt_tau(cpg_float val){
  cpg_params_vec[0] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_sqrt_alpha_m_sqrt_tau(cpg_float val){
  cpg_params_vec[1] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_tau_lamb(cpg_float val){
  cpg_params_vec[2] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_start_pos(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_end_pos(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+10] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_A_discrete(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+17] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_discrete_l(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2467] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_discrete_r(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3517] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_y_discrete(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4567] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_ox_cvxpy(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4917] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_ou_cvxpy(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+5274] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_etta(cpg_float val){
  cpg_params_vec[5427] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_inv_Jb_S_b_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+5428] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_inv_Jb_c_b_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+5437] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_omega_max(cpg_float val){
  cpg_params_vec[5440] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_S_u_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+5441] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_c_u_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+5450] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_m_max(cpg_float val){
  cpg_params_vec[5453] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<6764; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<964; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

void cpg_canonicalize_G(){
  for(i=0; i<7104; i++){
    Canon_Params.G->x[i] = 0;
    for(j=canon_G_map.p[i]; j<canon_G_map.p[i+1]; j++){
      Canon_Params.G->x[i] += canon_G_map.x[j]*cpg_params_vec[canon_G_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<3096; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d52 = qoco_custom_workspace.sol.z[780];
  CPG_Dual.d53 = qoco_custom_workspace.sol.z[811];
  CPG_Dual.d54 = qoco_custom_workspace.sol.z[842];
  CPG_Dual.d55 = qoco_custom_workspace.sol.z[873];
  CPG_Dual.d56 = qoco_custom_workspace.sol.z[904];
  CPG_Dual.d57 = qoco_custom_workspace.sol.z[935];
  CPG_Dual.d58 = qoco_custom_workspace.sol.z[966];
  CPG_Dual.d59 = qoco_custom_workspace.sol.z[997];
  CPG_Dual.d60 = qoco_custom_workspace.sol.z[1028];
  CPG_Dual.d61 = qoco_custom_workspace.sol.z[1059];
  CPG_Dual.d62 = qoco_custom_workspace.sol.z[1090];
  CPG_Dual.d63 = qoco_custom_workspace.sol.z[1121];
  CPG_Dual.d64 = qoco_custom_workspace.sol.z[1152];
  CPG_Dual.d65 = qoco_custom_workspace.sol.z[1183];
  CPG_Dual.d66 = qoco_custom_workspace.sol.z[1214];
  CPG_Dual.d67 = qoco_custom_workspace.sol.z[1245];
  CPG_Dual.d68 = qoco_custom_workspace.sol.z[1276];
  CPG_Dual.d69 = qoco_custom_workspace.sol.z[1307];
  CPG_Dual.d70 = qoco_custom_workspace.sol.z[1338];
  CPG_Dual.d71 = qoco_custom_workspace.sol.z[1369];
  CPG_Dual.d72 = qoco_custom_workspace.sol.z[1400];
  CPG_Dual.d73 = qoco_custom_workspace.sol.z[1431];
  CPG_Dual.d74 = qoco_custom_workspace.sol.z[1462];
  CPG_Dual.d75 = qoco_custom_workspace.sol.z[1493];
  CPG_Dual.d76 = qoco_custom_workspace.sol.z[1524];
  CPG_Dual.d77 = qoco_custom_workspace.sol.z[1555];
  CPG_Dual.d78 = qoco_custom_workspace.sol.z[1586];
  CPG_Dual.d79 = qoco_custom_workspace.sol.z[1617];
  CPG_Dual.d80 = qoco_custom_workspace.sol.z[1648];
  CPG_Dual.d81 = qoco_custom_workspace.sol.z[1679];
  CPG_Dual.d82 = qoco_custom_workspace.sol.z[1710];
  CPG_Dual.d83 = qoco_custom_workspace.sol.z[1741];
  CPG_Dual.d84 = qoco_custom_workspace.sol.z[1772];
  CPG_Dual.d85 = qoco_custom_workspace.sol.z[1803];
  CPG_Dual.d86 = qoco_custom_workspace.sol.z[1834];
  CPG_Dual.d87 = qoco_custom_workspace.sol.z[1865];
  CPG_Dual.d88 = qoco_custom_workspace.sol.z[1896];
  CPG_Dual.d89 = qoco_custom_workspace.sol.z[1927];
  CPG_Dual.d90 = qoco_custom_workspace.sol.z[1958];
  CPG_Dual.d91 = qoco_custom_workspace.sol.z[1989];
  CPG_Dual.d92 = qoco_custom_workspace.sol.z[2020];
  CPG_Dual.d93 = qoco_custom_workspace.sol.z[2051];
  CPG_Dual.d94 = qoco_custom_workspace.sol.z[2082];
  CPG_Dual.d95 = qoco_custom_workspace.sol.z[2113];
  CPG_Dual.d96 = qoco_custom_workspace.sol.z[2144];
  CPG_Dual.d97 = qoco_custom_workspace.sol.z[2175];
  CPG_Dual.d98 = qoco_custom_workspace.sol.z[2206];
  CPG_Dual.d99 = qoco_custom_workspace.sol.z[2237];
  CPG_Dual.d100 = qoco_custom_workspace.sol.z[2268];
  CPG_Dual.d101 = qoco_custom_workspace.sol.z[2299];
  CPG_Dual.d102 = qoco_custom_workspace.sol.z[2330];
  CPG_Dual.d103 = qoco_custom_workspace.sol.z[2331];
  CPG_Dual.d104 = qoco_custom_workspace.sol.z[2332];
  CPG_Dual.d105 = qoco_custom_workspace.sol.z[2333];
  CPG_Dual.d106 = qoco_custom_workspace.sol.z[2334];
  CPG_Dual.d107 = qoco_custom_workspace.sol.z[2335];
  CPG_Dual.d108 = qoco_custom_workspace.sol.z[2336];
  CPG_Dual.d109 = qoco_custom_workspace.sol.z[2337];
  CPG_Dual.d110 = qoco_custom_workspace.sol.z[2338];
  CPG_Dual.d111 = qoco_custom_workspace.sol.z[2339];
  CPG_Dual.d112 = qoco_custom_workspace.sol.z[2340];
  CPG_Dual.d113 = qoco_custom_workspace.sol.z[2341];
  CPG_Dual.d114 = qoco_custom_workspace.sol.z[2342];
  CPG_Dual.d115 = qoco_custom_workspace.sol.z[2343];
  CPG_Dual.d116 = qoco_custom_workspace.sol.z[2344];
  CPG_Dual.d117 = qoco_custom_workspace.sol.z[2345];
  CPG_Dual.d118 = qoco_custom_workspace.sol.z[2346];
  CPG_Dual.d119 = qoco_custom_workspace.sol.z[2347];
  CPG_Dual.d120 = qoco_custom_workspace.sol.z[2348];
  CPG_Dual.d121 = qoco_custom_workspace.sol.z[2349];
  CPG_Dual.d122 = qoco_custom_workspace.sol.z[2350];
  CPG_Dual.d123 = qoco_custom_workspace.sol.z[2351];
  CPG_Dual.d124 = qoco_custom_workspace.sol.z[2352];
  CPG_Dual.d125 = qoco_custom_workspace.sol.z[2353];
  CPG_Dual.d126 = qoco_custom_workspace.sol.z[2354];
  CPG_Dual.d127 = qoco_custom_workspace.sol.z[2355];
  CPG_Dual.d128 = qoco_custom_workspace.sol.z[2356];
  CPG_Dual.d129 = qoco_custom_workspace.sol.z[2357];
  CPG_Dual.d130 = qoco_custom_workspace.sol.z[2358];
  CPG_Dual.d131 = qoco_custom_workspace.sol.z[2359];
  CPG_Dual.d132 = qoco_custom_workspace.sol.z[2360];
  CPG_Dual.d133 = qoco_custom_workspace.sol.z[2361];
  CPG_Dual.d134 = qoco_custom_workspace.sol.z[2362];
  CPG_Dual.d135 = qoco_custom_workspace.sol.z[2363];
  CPG_Dual.d136 = qoco_custom_workspace.sol.z[2364];
  CPG_Dual.d137 = qoco_custom_workspace.sol.z[2365];
  CPG_Dual.d138 = qoco_custom_workspace.sol.z[2366];
  CPG_Dual.d139 = qoco_custom_workspace.sol.z[2367];
  CPG_Dual.d140 = qoco_custom_workspace.sol.z[2368];
  CPG_Dual.d141 = qoco_custom_workspace.sol.z[2369];
  CPG_Dual.d142 = qoco_custom_workspace.sol.z[2370];
  CPG_Dual.d143 = qoco_custom_workspace.sol.z[2371];
  CPG_Dual.d144 = qoco_custom_workspace.sol.z[2372];
  CPG_Dual.d145 = qoco_custom_workspace.sol.z[2373];
  CPG_Dual.d146 = qoco_custom_workspace.sol.z[2374];
  CPG_Dual.d147 = qoco_custom_workspace.sol.z[2375];
  CPG_Dual.d148 = qoco_custom_workspace.sol.z[2376];
  CPG_Dual.d149 = qoco_custom_workspace.sol.z[2377];
  CPG_Dual.d150 = qoco_custom_workspace.sol.z[2378];
  CPG_Dual.d151 = qoco_custom_workspace.sol.z[2379];
  CPG_Dual.d152 = qoco_custom_workspace.sol.z[2380];
  CPG_Dual.d153 = qoco_custom_workspace.sol.z[2381];
  CPG_Dual.d154 = qoco_custom_workspace.sol.z[2391];
  CPG_Dual.d155 = qoco_custom_workspace.sol.z[2401];
  CPG_Dual.d156 = qoco_custom_workspace.sol.z[2411];
  CPG_Dual.d157 = qoco_custom_workspace.sol.z[2421];
  CPG_Dual.d158 = qoco_custom_workspace.sol.z[2431];
  CPG_Dual.d159 = qoco_custom_workspace.sol.z[2441];
  CPG_Dual.d160 = qoco_custom_workspace.sol.z[2451];
  CPG_Dual.d161 = qoco_custom_workspace.sol.z[2461];
  CPG_Dual.d162 = qoco_custom_workspace.sol.z[2471];
  CPG_Dual.d163 = qoco_custom_workspace.sol.z[2481];
  CPG_Dual.d164 = qoco_custom_workspace.sol.z[2491];
  CPG_Dual.d165 = qoco_custom_workspace.sol.z[2501];
  CPG_Dual.d166 = qoco_custom_workspace.sol.z[2511];
  CPG_Dual.d167 = qoco_custom_workspace.sol.z[2521];
  CPG_Dual.d168 = qoco_custom_workspace.sol.z[2531];
  CPG_Dual.d169 = qoco_custom_workspace.sol.z[2541];
  CPG_Dual.d170 = qoco_custom_workspace.sol.z[2551];
  CPG_Dual.d171 = qoco_custom_workspace.sol.z[2561];
  CPG_Dual.d172 = qoco_custom_workspace.sol.z[2571];
  CPG_Dual.d173 = qoco_custom_workspace.sol.z[2581];
  CPG_Dual.d174 = qoco_custom_workspace.sol.z[2591];
  CPG_Dual.d175 = qoco_custom_workspace.sol.z[2601];
  CPG_Dual.d176 = qoco_custom_workspace.sol.z[2611];
  CPG_Dual.d177 = qoco_custom_workspace.sol.z[2621];
  CPG_Dual.d178 = qoco_custom_workspace.sol.z[2631];
  CPG_Dual.d179 = qoco_custom_workspace.sol.z[2641];
  CPG_Dual.d180 = qoco_custom_workspace.sol.z[2651];
  CPG_Dual.d181 = qoco_custom_workspace.sol.z[2661];
  CPG_Dual.d182 = qoco_custom_workspace.sol.z[2671];
  CPG_Dual.d183 = qoco_custom_workspace.sol.z[2681];
  CPG_Dual.d184 = qoco_custom_workspace.sol.z[2691];
  CPG_Dual.d185 = qoco_custom_workspace.sol.z[2701];
  CPG_Dual.d186 = qoco_custom_workspace.sol.z[2711];
  CPG_Dual.d187 = qoco_custom_workspace.sol.z[2721];
  CPG_Dual.d188 = qoco_custom_workspace.sol.z[2731];
  CPG_Dual.d189 = qoco_custom_workspace.sol.z[2741];
  CPG_Dual.d190 = qoco_custom_workspace.sol.z[2751];
  CPG_Dual.d191 = qoco_custom_workspace.sol.z[2761];
  CPG_Dual.d192 = qoco_custom_workspace.sol.z[2771];
  CPG_Dual.d193 = qoco_custom_workspace.sol.z[2781];
  CPG_Dual.d194 = qoco_custom_workspace.sol.z[2791];
  CPG_Dual.d195 = qoco_custom_workspace.sol.z[2801];
  CPG_Dual.d196 = qoco_custom_workspace.sol.z[2811];
  CPG_Dual.d197 = qoco_custom_workspace.sol.z[2821];
  CPG_Dual.d198 = qoco_custom_workspace.sol.z[2831];
  CPG_Dual.d199 = qoco_custom_workspace.sol.z[2841];
  CPG_Dual.d200 = qoco_custom_workspace.sol.z[2851];
  CPG_Dual.d201 = qoco_custom_workspace.sol.z[2861];
  CPG_Dual.d202 = qoco_custom_workspace.sol.z[2871];
  CPG_Dual.d203 = qoco_custom_workspace.sol.z[2881];
  CPG_Dual.d204 = qoco_custom_workspace.sol.z[2891];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_custom_workspace.sol.obj);
  CPG_Info.iter = qoco_custom_workspace.sol.iters;
  CPG_Info.status = qoco_custom_workspace.sol.status;
  CPG_Info.pri_res = qoco_custom_workspace.sol.pres;
  CPG_Info.dua_res = qoco_custom_workspace.sol.dres;
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (Canon_Outdated.G) {
    cpg_canonicalize_G();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (qoco_custom_workspace.n <= 0 ) {
    load_data(&qoco_custom_workspace);
  }
  if (Canon_Outdated.A) {
    update_A(&qoco_custom_workspace, Canon_Params.A->x);
  }
  if (Canon_Outdated.h) {
    update_h(&qoco_custom_workspace, Canon_Params.h);
  }
  if (Canon_Outdated.G) {
    update_G(&qoco_custom_workspace, Canon_Params.G->x);
  }
  if (Canon_Outdated.b) {
    update_b(&qoco_custom_workspace, Canon_Params.b);
  }
  // Solve with QOCOgen
  qoco_custom_solve(&qoco_custom_workspace);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
  Canon_Outdated.G = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  set_default_settings(&qoco_custom_workspace);
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  (&(qoco_custom_workspace.settings))->max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  (&(qoco_custom_workspace.settings))->bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  (&(qoco_custom_workspace.settings))->ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  (&(qoco_custom_workspace.settings))->iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  (&(qoco_custom_workspace.settings))->kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  (&(qoco_custom_workspace.settings))->kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  (&(qoco_custom_workspace.settings))->abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  (&(qoco_custom_workspace.settings))->reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  (&(qoco_custom_workspace.settings))->abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  (&(qoco_custom_workspace.settings))->reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  (&(qoco_custom_workspace.settings))->verbose = verbose_new;
}
