/* Generated by QOCOGEN on 03/31/2026 22:28:24 */
/* Copyright (c) 2025, Govind M. Chari <govindchari1@gmail.com> */
/* This source code is licensed under the BSD 3-Clause License  */

#ifndef QOCO_CUSTOM_WORKSPACE_H
#define QOCO_CUSTOM_WORKSPACE_H

typedef struct {
   int max_iters;
   int bisect_iters;
   int ruiz_iters;
   int iter_ref_iters;
   double kkt_static_reg;
   double kkt_dynamic_reg;
   double abstol;
   double reltol;
   double abstol_inacc;
   double reltol_inacc;
   unsigned char verbose;
} Settings;

typedef struct {
   double x[2727];
   double s[3096];
   double y[964];
   double z[3096];
   int iters;
   double obj;
   double pres;
   double dres;
   double gap;
   unsigned char status;
} Solution;

typedef struct {
   int n;
   int m;
   int p;
   double P[600];
   double c[2727];
   double A[6764];
   double b[964];
   double G[7104];
   double h[3096];
   int l;
   int nsoc;
   int q[51];
   int perm[6787];
   int Pnnz;
   int Wnnz;
   double x[2727];
   double s[3096];
   double y[964];
   double z[3096];
   double L[22633];
   double D[6787];
   double W[3402];
   double lambda[3096];
   double xbuff[2727];
   double ubuff1[3096];
   double ubuff2[3096];
   double ubuff3[3096];
   double Ds[3096];
   double Winv[3402];
   double WtW[3402];
   double kkt_rhs[6787];
   double kkt_res[6787];
   double xyz[6787];
   double Druiz[2727];
   double Eruiz[964];
   double Fruiz[3096];
   double Dinvruiz[2727];
   double Einvruiz[964];
   double Finvruiz[3096];
   double k;
   double kinv;
   double xyzbuff[6787];
   double xyzbuff2[6787];
   double sbar[4];
   double zbar[4];
   double mu;
   double sigma;
   double a;

   Settings settings;
   Solution sol;
} Workspace;

#endif