/* Generated by QOCOGEN on 03/31/2026 22:28:29 */
/* Copyright (c) 2025, Govind M. Chari <govindchari1@gmail.com> */
/* This source code is licensed under the BSD 3-Clause License  */

#ifndef QOCO_CUSTOM_KKT_H
#define QOCO_CUSTOM_KKT_H

#include "cone.h"
#include "ldl.h"
#include "workspace.h"

// Computes y = K * x where K is the permuted KKT matrix.
void KKT_perm_product(double* x, double* y, Workspace* work);
void compute_kkt_residual(Workspace* work);
void construct_kkt_aff_rhs(Workspace* work);
void construct_kkt_comb_rhs(Workspace* work);
void predictor_corrector(Workspace* work);
#endif