
/*
Auto-generated by CVXPYgen on April 17, 2026 at 13:06:24.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include <chrono>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.sqrt_tau) {
        cpg_update_sqrt_tau(CPG_Params_cpp.sqrt_tau);
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb) {
        cpg_update_sqrt_tau_sqrt_lamb(CPG_Params_cpp.sqrt_tau_sqrt_lamb);
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_ox) {
        for(i=0; i<403; i++) {
            cpg_update_sqrt_tau_sqrt_lamb_ox(i, CPG_Params_cpp.sqrt_tau_sqrt_lamb_ox[i]);
        }
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_etta) {
        cpg_update_sqrt_tau_sqrt_lamb_etta(CPG_Params_cpp.sqrt_tau_sqrt_lamb_etta);
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_C_discrete) {
        for(i=0; i<1209; i++) {
            cpg_update_sqrt_tau_sqrt_lamb_C_discrete(i, CPG_Params_cpp.sqrt_tau_sqrt_lamb_C_discrete[i]);
        }
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_z_discrete) {
        for(i=0; i<93; i++) {
            cpg_update_sqrt_tau_sqrt_lamb_z_discrete(i, CPG_Params_cpp.sqrt_tau_sqrt_lamb_z_discrete[i]);
        }
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_S_x_scaling) {
        for(i=0; i<169; i++) {
            cpg_update_sqrt_tau_sqrt_lamb_S_x_scaling(i, CPG_Params_cpp.sqrt_tau_sqrt_lamb_S_x_scaling[i]);
        }
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_c_x_scaling) {
        for(i=0; i<13; i++) {
            cpg_update_sqrt_tau_sqrt_lamb_c_x_scaling(i, CPG_Params_cpp.sqrt_tau_sqrt_lamb_c_x_scaling[i]);
        }
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_vel_max) {
        cpg_update_sqrt_tau_sqrt_lamb_vel_max(CPG_Params_cpp.sqrt_tau_sqrt_lamb_vel_max);
    }
    if (CPG_Updated_cpp.sqrt_tau_sqrt_lamb_omega_max) {
        cpg_update_sqrt_tau_sqrt_lamb_omega_max(CPG_Params_cpp.sqrt_tau_sqrt_lamb_omega_max);
    }
    if (CPG_Updated_cpp.start_pos) {
        for(i=0; i<13; i++) {
            cpg_update_start_pos(i, CPG_Params_cpp.start_pos[i]);
        }
    }
    if (CPG_Updated_cpp.end_pos) {
        for(i=0; i<13; i++) {
            cpg_update_end_pos(i, CPG_Params_cpp.end_pos[i]);
        }
    }
    if (CPG_Updated_cpp.A_discrete) {
        for(i=0; i<5070; i++) {
            cpg_update_A_discrete(i, CPG_Params_cpp.A_discrete[i]);
        }
    }
    if (CPG_Updated_cpp.B_discrete_l) {
        for(i=0; i<2340; i++) {
            cpg_update_B_discrete_l(i, CPG_Params_cpp.B_discrete_l[i]);
        }
    }
    if (CPG_Updated_cpp.B_discrete_r) {
        for(i=0; i<2340; i++) {
            cpg_update_B_discrete_r(i, CPG_Params_cpp.B_discrete_r[i]);
        }
    }
    if (CPG_Updated_cpp.y_discrete) {
        for(i=0; i<390; i++) {
            cpg_update_y_discrete(i, CPG_Params_cpp.y_discrete[i]);
        }
    }
    if (CPG_Updated_cpp.S_u_scaling) {
        for(i=0; i<36; i++) {
            cpg_update_S_u_scaling(i, CPG_Params_cpp.S_u_scaling[i]);
        }
    }
    if (CPG_Updated_cpp.c_u_scaling) {
        for(i=0; i<6; i++) {
            cpg_update_c_u_scaling(i, CPG_Params_cpp.c_u_scaling[i]);
        }
    }
    if (CPG_Updated_cpp.acc_max) {
        cpg_update_acc_max(CPG_Params_cpp.acc_max);
    }
    if (CPG_Updated_cpp.torq_max) {
        cpg_update_torq_max(CPG_Params_cpp.torq_max);
    }

    // Solve
    auto ASA_start = std::chrono::high_resolution_clock::now();
    cpg_solve();
    auto ASA_end = std::chrono::high_resolution_clock::now();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<186; i++) {
        CPG_Prim_cpp.u[i] = CPG_Prim.u[i];
    }
    for(i=0; i<403; i++) {
        CPG_Prim_cpp.x[i] = CPG_Prim.x[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d3[i] = CPG_Dual.d3[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d4[i] = CPG_Dual.d4[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d5[i] = CPG_Dual.d5[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d6[i] = CPG_Dual.d6[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d7[i] = CPG_Dual.d7[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d8[i] = CPG_Dual.d8[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d9[i] = CPG_Dual.d9[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d10[i] = CPG_Dual.d10[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d11[i] = CPG_Dual.d11[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d12[i] = CPG_Dual.d12[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d13[i] = CPG_Dual.d13[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d14[i] = CPG_Dual.d14[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d15[i] = CPG_Dual.d15[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d16[i] = CPG_Dual.d16[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d17[i] = CPG_Dual.d17[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d18[i] = CPG_Dual.d18[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d19[i] = CPG_Dual.d19[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d20[i] = CPG_Dual.d20[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d21[i] = CPG_Dual.d21[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d22[i] = CPG_Dual.d22[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d23[i] = CPG_Dual.d23[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d24[i] = CPG_Dual.d24[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d25[i] = CPG_Dual.d25[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d26[i] = CPG_Dual.d26[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d27[i] = CPG_Dual.d27[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d28[i] = CPG_Dual.d28[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d29[i] = CPG_Dual.d29[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d30[i] = CPG_Dual.d30[i];
    }
    for(i=0; i<13; i++) {
        CPG_Dual_cpp.d31[i] = CPG_Dual.d31[i];
    }
    CPG_Dual_cpp.d32 = CPG_Dual.d32;
    CPG_Dual_cpp.d33 = CPG_Dual.d33;
    CPG_Dual_cpp.d34 = CPG_Dual.d34;
    CPG_Dual_cpp.d35 = CPG_Dual.d35;
    CPG_Dual_cpp.d36 = CPG_Dual.d36;
    CPG_Dual_cpp.d37 = CPG_Dual.d37;
    CPG_Dual_cpp.d38 = CPG_Dual.d38;
    CPG_Dual_cpp.d39 = CPG_Dual.d39;
    CPG_Dual_cpp.d40 = CPG_Dual.d40;
    CPG_Dual_cpp.d41 = CPG_Dual.d41;
    CPG_Dual_cpp.d42 = CPG_Dual.d42;
    CPG_Dual_cpp.d43 = CPG_Dual.d43;
    CPG_Dual_cpp.d44 = CPG_Dual.d44;
    CPG_Dual_cpp.d45 = CPG_Dual.d45;
    CPG_Dual_cpp.d46 = CPG_Dual.d46;
    CPG_Dual_cpp.d47 = CPG_Dual.d47;
    CPG_Dual_cpp.d48 = CPG_Dual.d48;
    CPG_Dual_cpp.d49 = CPG_Dual.d49;
    CPG_Dual_cpp.d50 = CPG_Dual.d50;
    CPG_Dual_cpp.d51 = CPG_Dual.d51;
    CPG_Dual_cpp.d52 = CPG_Dual.d52;
    CPG_Dual_cpp.d53 = CPG_Dual.d53;
    CPG_Dual_cpp.d54 = CPG_Dual.d54;
    CPG_Dual_cpp.d55 = CPG_Dual.d55;
    CPG_Dual_cpp.d56 = CPG_Dual.d56;
    CPG_Dual_cpp.d57 = CPG_Dual.d57;
    CPG_Dual_cpp.d58 = CPG_Dual.d58;
    CPG_Dual_cpp.d59 = CPG_Dual.d59;
    CPG_Dual_cpp.d60 = CPG_Dual.d60;
    CPG_Dual_cpp.d61 = CPG_Dual.d61;
    CPG_Dual_cpp.d62 = CPG_Dual.d62;
    CPG_Dual_cpp.d63 = CPG_Dual.d63;
    CPG_Dual_cpp.d64 = CPG_Dual.d64;
    CPG_Dual_cpp.d65 = CPG_Dual.d65;
    CPG_Dual_cpp.d66 = CPG_Dual.d66;
    CPG_Dual_cpp.d67 = CPG_Dual.d67;
    CPG_Dual_cpp.d68 = CPG_Dual.d68;
    CPG_Dual_cpp.d69 = CPG_Dual.d69;
    CPG_Dual_cpp.d70 = CPG_Dual.d70;
    CPG_Dual_cpp.d71 = CPG_Dual.d71;
    CPG_Dual_cpp.d72 = CPG_Dual.d72;
    CPG_Dual_cpp.d73 = CPG_Dual.d73;
    CPG_Dual_cpp.d74 = CPG_Dual.d74;
    CPG_Dual_cpp.d75 = CPG_Dual.d75;
    CPG_Dual_cpp.d76 = CPG_Dual.d76;
    CPG_Dual_cpp.d77 = CPG_Dual.d77;
    CPG_Dual_cpp.d78 = CPG_Dual.d78;
    CPG_Dual_cpp.d79 = CPG_Dual.d79;
    CPG_Dual_cpp.d80 = CPG_Dual.d80;
    CPG_Dual_cpp.d81 = CPG_Dual.d81;
    CPG_Dual_cpp.d82 = CPG_Dual.d82;
    CPG_Dual_cpp.d83 = CPG_Dual.d83;
    CPG_Dual_cpp.d84 = CPG_Dual.d84;
    CPG_Dual_cpp.d85 = CPG_Dual.d85;
    CPG_Dual_cpp.d86 = CPG_Dual.d86;
    CPG_Dual_cpp.d87 = CPG_Dual.d87;
    CPG_Dual_cpp.d88 = CPG_Dual.d88;
    CPG_Dual_cpp.d89 = CPG_Dual.d89;
    CPG_Dual_cpp.d90 = CPG_Dual.d90;
    CPG_Dual_cpp.d91 = CPG_Dual.d91;
    CPG_Dual_cpp.d92 = CPG_Dual.d92;
    CPG_Dual_cpp.d93 = CPG_Dual.d93;
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    std::chrono::duration<double> elapsed = ASA_end - ASA_start;
    CPG_Info_cpp.time = elapsed.count();
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("sqrt_tau", &CPG_Params_cpp_t::sqrt_tau)
            .def_readwrite("sqrt_tau_sqrt_lamb", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb)
            .def_readwrite("sqrt_tau_sqrt_lamb_ox", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_ox)
            .def_readwrite("sqrt_tau_sqrt_lamb_etta", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_etta)
            .def_readwrite("sqrt_tau_sqrt_lamb_C_discrete", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_C_discrete)
            .def_readwrite("sqrt_tau_sqrt_lamb_z_discrete", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_z_discrete)
            .def_readwrite("sqrt_tau_sqrt_lamb_S_x_scaling", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_S_x_scaling)
            .def_readwrite("sqrt_tau_sqrt_lamb_c_x_scaling", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_c_x_scaling)
            .def_readwrite("sqrt_tau_sqrt_lamb_vel_max", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_vel_max)
            .def_readwrite("sqrt_tau_sqrt_lamb_omega_max", &CPG_Params_cpp_t::sqrt_tau_sqrt_lamb_omega_max)
            .def_readwrite("start_pos", &CPG_Params_cpp_t::start_pos)
            .def_readwrite("end_pos", &CPG_Params_cpp_t::end_pos)
            .def_readwrite("A_discrete", &CPG_Params_cpp_t::A_discrete)
            .def_readwrite("B_discrete_l", &CPG_Params_cpp_t::B_discrete_l)
            .def_readwrite("B_discrete_r", &CPG_Params_cpp_t::B_discrete_r)
            .def_readwrite("y_discrete", &CPG_Params_cpp_t::y_discrete)
            .def_readwrite("S_u_scaling", &CPG_Params_cpp_t::S_u_scaling)
            .def_readwrite("c_u_scaling", &CPG_Params_cpp_t::c_u_scaling)
            .def_readwrite("acc_max", &CPG_Params_cpp_t::acc_max)
            .def_readwrite("torq_max", &CPG_Params_cpp_t::torq_max)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("sqrt_tau", &CPG_Updated_cpp_t::sqrt_tau)
            .def_readwrite("sqrt_tau_sqrt_lamb", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb)
            .def_readwrite("sqrt_tau_sqrt_lamb_ox", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_ox)
            .def_readwrite("sqrt_tau_sqrt_lamb_etta", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_etta)
            .def_readwrite("sqrt_tau_sqrt_lamb_C_discrete", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_C_discrete)
            .def_readwrite("sqrt_tau_sqrt_lamb_z_discrete", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_z_discrete)
            .def_readwrite("sqrt_tau_sqrt_lamb_S_x_scaling", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_S_x_scaling)
            .def_readwrite("sqrt_tau_sqrt_lamb_c_x_scaling", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_c_x_scaling)
            .def_readwrite("sqrt_tau_sqrt_lamb_vel_max", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_vel_max)
            .def_readwrite("sqrt_tau_sqrt_lamb_omega_max", &CPG_Updated_cpp_t::sqrt_tau_sqrt_lamb_omega_max)
            .def_readwrite("start_pos", &CPG_Updated_cpp_t::start_pos)
            .def_readwrite("end_pos", &CPG_Updated_cpp_t::end_pos)
            .def_readwrite("A_discrete", &CPG_Updated_cpp_t::A_discrete)
            .def_readwrite("B_discrete_l", &CPG_Updated_cpp_t::B_discrete_l)
            .def_readwrite("B_discrete_r", &CPG_Updated_cpp_t::B_discrete_r)
            .def_readwrite("y_discrete", &CPG_Updated_cpp_t::y_discrete)
            .def_readwrite("S_u_scaling", &CPG_Updated_cpp_t::S_u_scaling)
            .def_readwrite("c_u_scaling", &CPG_Updated_cpp_t::c_u_scaling)
            .def_readwrite("acc_max", &CPG_Updated_cpp_t::acc_max)
            .def_readwrite("torq_max", &CPG_Updated_cpp_t::torq_max)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("u", &CPG_Prim_cpp_t::u)
            .def_readwrite("x", &CPG_Prim_cpp_t::x)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &CPG_Dual_cpp_t::d50)
            .def_readwrite("d51", &CPG_Dual_cpp_t::d51)
            .def_readwrite("d52", &CPG_Dual_cpp_t::d52)
            .def_readwrite("d53", &CPG_Dual_cpp_t::d53)
            .def_readwrite("d54", &CPG_Dual_cpp_t::d54)
            .def_readwrite("d55", &CPG_Dual_cpp_t::d55)
            .def_readwrite("d56", &CPG_Dual_cpp_t::d56)
            .def_readwrite("d57", &CPG_Dual_cpp_t::d57)
            .def_readwrite("d58", &CPG_Dual_cpp_t::d58)
            .def_readwrite("d59", &CPG_Dual_cpp_t::d59)
            .def_readwrite("d60", &CPG_Dual_cpp_t::d60)
            .def_readwrite("d61", &CPG_Dual_cpp_t::d61)
            .def_readwrite("d62", &CPG_Dual_cpp_t::d62)
            .def_readwrite("d63", &CPG_Dual_cpp_t::d63)
            .def_readwrite("d64", &CPG_Dual_cpp_t::d64)
            .def_readwrite("d65", &CPG_Dual_cpp_t::d65)
            .def_readwrite("d66", &CPG_Dual_cpp_t::d66)
            .def_readwrite("d67", &CPG_Dual_cpp_t::d67)
            .def_readwrite("d68", &CPG_Dual_cpp_t::d68)
            .def_readwrite("d69", &CPG_Dual_cpp_t::d69)
            .def_readwrite("d70", &CPG_Dual_cpp_t::d70)
            .def_readwrite("d71", &CPG_Dual_cpp_t::d71)
            .def_readwrite("d72", &CPG_Dual_cpp_t::d72)
            .def_readwrite("d73", &CPG_Dual_cpp_t::d73)
            .def_readwrite("d74", &CPG_Dual_cpp_t::d74)
            .def_readwrite("d75", &CPG_Dual_cpp_t::d75)
            .def_readwrite("d76", &CPG_Dual_cpp_t::d76)
            .def_readwrite("d77", &CPG_Dual_cpp_t::d77)
            .def_readwrite("d78", &CPG_Dual_cpp_t::d78)
            .def_readwrite("d79", &CPG_Dual_cpp_t::d79)
            .def_readwrite("d80", &CPG_Dual_cpp_t::d80)
            .def_readwrite("d81", &CPG_Dual_cpp_t::d81)
            .def_readwrite("d82", &CPG_Dual_cpp_t::d82)
            .def_readwrite("d83", &CPG_Dual_cpp_t::d83)
            .def_readwrite("d84", &CPG_Dual_cpp_t::d84)
            .def_readwrite("d85", &CPG_Dual_cpp_t::d85)
            .def_readwrite("d86", &CPG_Dual_cpp_t::d86)
            .def_readwrite("d87", &CPG_Dual_cpp_t::d87)
            .def_readwrite("d88", &CPG_Dual_cpp_t::d88)
            .def_readwrite("d89", &CPG_Dual_cpp_t::d89)
            .def_readwrite("d90", &CPG_Dual_cpp_t::d90)
            .def_readwrite("d91", &CPG_Dual_cpp_t::d91)
            .def_readwrite("d92", &CPG_Dual_cpp_t::d92)
            .def_readwrite("d93", &CPG_Dual_cpp_t::d93)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_feastol", &cpg_set_solver_feastol);
    m.def("set_solver_abstol", &cpg_set_solver_abstol);
    m.def("set_solver_reltol", &cpg_set_solver_reltol);
    m.def("set_solver_feastol_inacc", &cpg_set_solver_feastol_inacc);
    m.def("set_solver_abstol_inacc", &cpg_set_solver_abstol_inacc);
    m.def("set_solver_reltol_inacc", &cpg_set_solver_reltol_inacc);
    m.def("set_solver_maxit", &cpg_set_solver_maxit);

}
