
/*
Auto-generated by CVXPYgen on February 27, 2026 at 17:27:29.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include <time.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_sqrt_tau(2.00000000000000000000);
  cpg_update_sqrt_alpha_m_sqrt_tau(14.14213562373095101066);
  cpg_update_sqrt_alpha_q_sqrt_tau(20.00000000000000000000);
  cpg_update_sqrt_alpha_q_sqrt_tau_xq_goal(0, 10.00000000000000000000);
  cpg_update_tau_lamb(40000.00000000000000000000);
  cpg_update_start_pos(0, 1.00000000000000000000);
  cpg_update_end_pos(0, 0.50000000000000000000);
  cpg_update_A_discrete(0, 0.99993297366267963611);
  cpg_update_B_discrete_l(0, 0.00000232688044429168);
  cpg_update_B_discrete_r(0, 0.00000077484571791902);
  cpg_update_y_discrete(0, 0.00386180012621373898);
  cpg_update_ox_cvxpy(0, 1.00000011439603619934);
  cpg_update_ou_cvxpy(0, -1.26041367339431653605);
  cpg_update_etta(0.31250000000000000000);
  cpg_update_inv_Jb_S_b_scaling(0, 0.17456749301983293110);
  cpg_update_inv_Jb_c_b_scaling(0, -0.08555535548991811956);
  cpg_update_omega_max(0.08726646259971647390);
  cpg_update_S_u_scaling(0, 0.04000000000000000777);
  cpg_update_c_u_scaling(0, -0.02000000000000000389);
  cpg_update_m_max(0.20000000000000001110);

    double start = clock();
  cpg_solve();
  double  end = clock();

  double cpu_time_used = ((double)(end - start)) / CLOCKS_PER_SEC;

  printf("obj = %f\n", CPG_Result.info->obj_val);
  
  printf("Solver time = %.1f ms\n", cpu_time_used*1000);

  return 0;

}
