
/*
Auto-generated by CVXPYgen on February 20, 2026 at 23:27:11.
Content: Type definitions and variable declarations.
*/

#include "ecos.h"

#ifndef CPG_TYPES_H
# define CPG_TYPES_H

typedef double cpg_float;
typedef int cpg_int;

// Compressed sparse column matrix
typedef struct {
  cpg_int      *p;
  cpg_int      *i;
  cpg_float    *x;
  cpg_int      nnz;
} cpg_csc;

// Canonical parameters
typedef struct {
  cpg_float    *c;         // Canonical parameter c
  cpg_float    d;          // Canonical parameter d
  cpg_csc      *A;         // Canonical parameter A
  cpg_float    *b;         // Canonical parameter b
  cpg_csc      *G;         // Canonical parameter G
  cpg_float    *h;         // Canonical parameter h
} Canon_Params_t;

// Flags indicating outdated canonical parameters
typedef struct {
  int        c;            // Bool, if canonical parameter c outdated
  int        d;            // Bool, if canonical parameter d outdated
  int        A;            // Bool, if canonical parameter A outdated
  int        b;            // Bool, if canonical parameter b outdated
  int        G;            // Bool, if canonical parameter G outdated
  int        h;            // Bool, if canonical parameter h outdated
} Canon_Outdated_t;

// Primal solution
typedef struct {
  cpg_float    *u;         // Your variable u
  cpg_float    *x;         // Your variable x
  cpg_float    *vc;        // Your variable vc
} CPG_Prim_t;

// Dual solution
typedef struct {
  cpg_float    *d0;        // Your dual variable for constraint d0
  cpg_float    *d1;        // Your dual variable for constraint d1
  cpg_float    *d2;        // Your dual variable for constraint d2
  cpg_float    *d3;        // Your dual variable for constraint d3
  cpg_float    *d4;        // Your dual variable for constraint d4
  cpg_float    *d5;        // Your dual variable for constraint d5
  cpg_float    *d6;        // Your dual variable for constraint d6
  cpg_float    *d7;        // Your dual variable for constraint d7
  cpg_float    *d8;        // Your dual variable for constraint d8
  cpg_float    *d9;        // Your dual variable for constraint d9
  cpg_float    *d10;       // Your dual variable for constraint d10
  cpg_float    *d11;       // Your dual variable for constraint d11
  cpg_float    *d12;       // Your dual variable for constraint d12
  cpg_float    *d13;       // Your dual variable for constraint d13
  cpg_float    *d14;       // Your dual variable for constraint d14
  cpg_float    *d15;       // Your dual variable for constraint d15
  cpg_float    *d16;       // Your dual variable for constraint d16
  cpg_float    *d17;       // Your dual variable for constraint d17
  cpg_float    *d18;       // Your dual variable for constraint d18
  cpg_float    *d19;       // Your dual variable for constraint d19
  cpg_float    *d20;       // Your dual variable for constraint d20
  cpg_float    *d21;       // Your dual variable for constraint d21
  cpg_float    *d22;       // Your dual variable for constraint d22
  cpg_float    *d23;       // Your dual variable for constraint d23
  cpg_float    *d24;       // Your dual variable for constraint d24
  cpg_float    *d25;       // Your dual variable for constraint d25
  cpg_float    *d26;       // Your dual variable for constraint d26
  cpg_float    *d27;       // Your dual variable for constraint d27
  cpg_float    *d28;       // Your dual variable for constraint d28
  cpg_float    *d29;       // Your dual variable for constraint d29
  cpg_float    *d30;       // Your dual variable for constraint d30
  cpg_float    *d31;       // Your dual variable for constraint d31
  cpg_float    *d32;       // Your dual variable for constraint d32
  cpg_float    *d33;       // Your dual variable for constraint d33
  cpg_float    *d34;       // Your dual variable for constraint d34
  cpg_float    *d35;       // Your dual variable for constraint d35
  cpg_float    *d36;       // Your dual variable for constraint d36
  cpg_float    *d37;       // Your dual variable for constraint d37
  cpg_float    *d38;       // Your dual variable for constraint d38
  cpg_float    *d39;       // Your dual variable for constraint d39
  cpg_float    *d40;       // Your dual variable for constraint d40
  cpg_float    *d41;       // Your dual variable for constraint d41
  cpg_float    *d42;       // Your dual variable for constraint d42
  cpg_float    *d43;       // Your dual variable for constraint d43
  cpg_float    *d44;       // Your dual variable for constraint d44
  cpg_float    *d45;       // Your dual variable for constraint d45
  cpg_float    *d46;       // Your dual variable for constraint d46
  cpg_float    *d47;       // Your dual variable for constraint d47
  cpg_float    *d48;       // Your dual variable for constraint d48
  cpg_float    *d49;       // Your dual variable for constraint d49
  cpg_float    *d50;       // Your dual variable for constraint d50
  cpg_float    *d51;       // Your dual variable for constraint d51
  cpg_float    *d52;       // Your dual variable for constraint d52
  cpg_float    *d53;       // Your dual variable for constraint d53
  cpg_float    *d54;       // Your dual variable for constraint d54
  cpg_float    *d55;       // Your dual variable for constraint d55
  cpg_float    *d56;       // Your dual variable for constraint d56
  cpg_float    *d57;       // Your dual variable for constraint d57
  cpg_float    *d58;       // Your dual variable for constraint d58
  cpg_float    *d59;       // Your dual variable for constraint d59
  cpg_float    *d60;       // Your dual variable for constraint d60
  cpg_float    *d61;       // Your dual variable for constraint d61
  cpg_float    *d62;       // Your dual variable for constraint d62
  cpg_float    *d63;       // Your dual variable for constraint d63
  cpg_float    *d64;       // Your dual variable for constraint d64
  cpg_float    *d65;       // Your dual variable for constraint d65
  cpg_float    *d66;       // Your dual variable for constraint d66
  cpg_float    *d67;       // Your dual variable for constraint d67
  cpg_float    *d68;       // Your dual variable for constraint d68
  cpg_float    *d69;       // Your dual variable for constraint d69
  cpg_float    *d70;       // Your dual variable for constraint d70
  cpg_float    *d71;       // Your dual variable for constraint d71
  cpg_float    *d72;       // Your dual variable for constraint d72
  cpg_float    *d73;       // Your dual variable for constraint d73
  cpg_float    *d74;       // Your dual variable for constraint d74
  cpg_float    *d75;       // Your dual variable for constraint d75
  cpg_float    *d76;       // Your dual variable for constraint d76
  cpg_float    *d77;       // Your dual variable for constraint d77
  cpg_float    *d78;       // Your dual variable for constraint d78
  cpg_float    *d79;       // Your dual variable for constraint d79
  cpg_float    *d80;       // Your dual variable for constraint d80
  cpg_float    *d81;       // Your dual variable for constraint d81
  cpg_float    *d82;       // Your dual variable for constraint d82
  cpg_float    *d83;       // Your dual variable for constraint d83
  cpg_float    *d84;       // Your dual variable for constraint d84
  cpg_float    *d85;       // Your dual variable for constraint d85
  cpg_float    *d86;       // Your dual variable for constraint d86
  cpg_float    *d87;       // Your dual variable for constraint d87
  cpg_float    *d88;       // Your dual variable for constraint d88
  cpg_float    *d89;       // Your dual variable for constraint d89
  cpg_float    *d90;       // Your dual variable for constraint d90
  cpg_float    *d91;       // Your dual variable for constraint d91
  cpg_float    *d92;       // Your dual variable for constraint d92
  cpg_float    *d93;       // Your dual variable for constraint d93
  cpg_float    *d94;       // Your dual variable for constraint d94
  cpg_float    *d95;       // Your dual variable for constraint d95
  cpg_float    *d96;       // Your dual variable for constraint d96
  cpg_float    *d97;       // Your dual variable for constraint d97
  cpg_float    *d98;       // Your dual variable for constraint d98
  cpg_float    *d99;       // Your dual variable for constraint d99
  cpg_float    *d100;      // Your dual variable for constraint d100
  cpg_float    *d101;      // Your dual variable for constraint d101
  cpg_float    d102;       // Your dual variable for constraint d102
  cpg_float    d103;       // Your dual variable for constraint d103
  cpg_float    d104;       // Your dual variable for constraint d104
  cpg_float    d105;       // Your dual variable for constraint d105
  cpg_float    d106;       // Your dual variable for constraint d106
  cpg_float    d107;       // Your dual variable for constraint d107
  cpg_float    d108;       // Your dual variable for constraint d108
  cpg_float    d109;       // Your dual variable for constraint d109
  cpg_float    d110;       // Your dual variable for constraint d110
  cpg_float    d111;       // Your dual variable for constraint d111
  cpg_float    d112;       // Your dual variable for constraint d112
  cpg_float    d113;       // Your dual variable for constraint d113
  cpg_float    d114;       // Your dual variable for constraint d114
  cpg_float    d115;       // Your dual variable for constraint d115
  cpg_float    d116;       // Your dual variable for constraint d116
  cpg_float    d117;       // Your dual variable for constraint d117
  cpg_float    d118;       // Your dual variable for constraint d118
  cpg_float    d119;       // Your dual variable for constraint d119
  cpg_float    d120;       // Your dual variable for constraint d120
  cpg_float    d121;       // Your dual variable for constraint d121
  cpg_float    d122;       // Your dual variable for constraint d122
  cpg_float    d123;       // Your dual variable for constraint d123
  cpg_float    d124;       // Your dual variable for constraint d124
  cpg_float    d125;       // Your dual variable for constraint d125
  cpg_float    d126;       // Your dual variable for constraint d126
  cpg_float    d127;       // Your dual variable for constraint d127
  cpg_float    d128;       // Your dual variable for constraint d128
  cpg_float    d129;       // Your dual variable for constraint d129
  cpg_float    d130;       // Your dual variable for constraint d130
  cpg_float    d131;       // Your dual variable for constraint d131
  cpg_float    d132;       // Your dual variable for constraint d132
  cpg_float    d133;       // Your dual variable for constraint d133
  cpg_float    d134;       // Your dual variable for constraint d134
  cpg_float    d135;       // Your dual variable for constraint d135
  cpg_float    d136;       // Your dual variable for constraint d136
  cpg_float    d137;       // Your dual variable for constraint d137
  cpg_float    d138;       // Your dual variable for constraint d138
  cpg_float    d139;       // Your dual variable for constraint d139
  cpg_float    d140;       // Your dual variable for constraint d140
  cpg_float    d141;       // Your dual variable for constraint d141
  cpg_float    d142;       // Your dual variable for constraint d142
  cpg_float    d143;       // Your dual variable for constraint d143
  cpg_float    d144;       // Your dual variable for constraint d144
  cpg_float    d145;       // Your dual variable for constraint d145
  cpg_float    d146;       // Your dual variable for constraint d146
  cpg_float    d147;       // Your dual variable for constraint d147
  cpg_float    d148;       // Your dual variable for constraint d148
  cpg_float    d149;       // Your dual variable for constraint d149
  cpg_float    d150;       // Your dual variable for constraint d150
  cpg_float    d151;       // Your dual variable for constraint d151
  cpg_float    d152;       // Your dual variable for constraint d152
  cpg_float    d153;       // Your dual variable for constraint d153
  cpg_float    d154;       // Your dual variable for constraint d154
  cpg_float    d155;       // Your dual variable for constraint d155
  cpg_float    d156;       // Your dual variable for constraint d156
  cpg_float    d157;       // Your dual variable for constraint d157
  cpg_float    d158;       // Your dual variable for constraint d158
  cpg_float    d159;       // Your dual variable for constraint d159
  cpg_float    d160;       // Your dual variable for constraint d160
  cpg_float    d161;       // Your dual variable for constraint d161
  cpg_float    d162;       // Your dual variable for constraint d162
  cpg_float    d163;       // Your dual variable for constraint d163
  cpg_float    d164;       // Your dual variable for constraint d164
  cpg_float    d165;       // Your dual variable for constraint d165
  cpg_float    d166;       // Your dual variable for constraint d166
  cpg_float    d167;       // Your dual variable for constraint d167
  cpg_float    d168;       // Your dual variable for constraint d168
  cpg_float    d169;       // Your dual variable for constraint d169
  cpg_float    d170;       // Your dual variable for constraint d170
  cpg_float    d171;       // Your dual variable for constraint d171
  cpg_float    d172;       // Your dual variable for constraint d172
  cpg_float    d173;       // Your dual variable for constraint d173
  cpg_float    d174;       // Your dual variable for constraint d174
  cpg_float    d175;       // Your dual variable for constraint d175
  cpg_float    d176;       // Your dual variable for constraint d176
  cpg_float    d177;       // Your dual variable for constraint d177
  cpg_float    d178;       // Your dual variable for constraint d178
  cpg_float    d179;       // Your dual variable for constraint d179
  cpg_float    d180;       // Your dual variable for constraint d180
  cpg_float    d181;       // Your dual variable for constraint d181
  cpg_float    d182;       // Your dual variable for constraint d182
  cpg_float    d183;       // Your dual variable for constraint d183
  cpg_float    d184;       // Your dual variable for constraint d184
  cpg_float    d185;       // Your dual variable for constraint d185
  cpg_float    d186;       // Your dual variable for constraint d186
  cpg_float    d187;       // Your dual variable for constraint d187
  cpg_float    d188;       // Your dual variable for constraint d188
  cpg_float    d189;       // Your dual variable for constraint d189
  cpg_float    d190;       // Your dual variable for constraint d190
  cpg_float    d191;       // Your dual variable for constraint d191
  cpg_float    d192;       // Your dual variable for constraint d192
  cpg_float    d193;       // Your dual variable for constraint d193
  cpg_float    d194;       // Your dual variable for constraint d194
  cpg_float    d195;       // Your dual variable for constraint d195
  cpg_float    d196;       // Your dual variable for constraint d196
  cpg_float    d197;       // Your dual variable for constraint d197
  cpg_float    d198;       // Your dual variable for constraint d198
  cpg_float    d199;       // Your dual variable for constraint d199
  cpg_float    d200;       // Your dual variable for constraint d200
  cpg_float    d201;       // Your dual variable for constraint d201
  cpg_float    d202;       // Your dual variable for constraint d202
  cpg_float    d203;       // Your dual variable for constraint d203
  cpg_float    d204;       // Your dual variable for constraint d204
  cpg_float    d205;       // Your dual variable for constraint d205
  cpg_float    d206;       // Your dual variable for constraint d206
  cpg_float    d207;       // Your dual variable for constraint d207
  cpg_float    d208;       // Your dual variable for constraint d208
  cpg_float    d209;       // Your dual variable for constraint d209
  cpg_float    d210;       // Your dual variable for constraint d210
  cpg_float    d211;       // Your dual variable for constraint d211
  cpg_float    d212;       // Your dual variable for constraint d212
  cpg_float    d213;       // Your dual variable for constraint d213
  cpg_float    d214;       // Your dual variable for constraint d214
  cpg_float    d215;       // Your dual variable for constraint d215
  cpg_float    d216;       // Your dual variable for constraint d216
  cpg_float    d217;       // Your dual variable for constraint d217
  cpg_float    d218;       // Your dual variable for constraint d218
  cpg_float    d219;       // Your dual variable for constraint d219
  cpg_float    d220;       // Your dual variable for constraint d220
  cpg_float    d221;       // Your dual variable for constraint d221
  cpg_float    d222;       // Your dual variable for constraint d222
  cpg_float    d223;       // Your dual variable for constraint d223
  cpg_float    d224;       // Your dual variable for constraint d224
  cpg_float    d225;       // Your dual variable for constraint d225
  cpg_float    d226;       // Your dual variable for constraint d226
  cpg_float    d227;       // Your dual variable for constraint d227
  cpg_float    d228;       // Your dual variable for constraint d228
  cpg_float    d229;       // Your dual variable for constraint d229
  cpg_float    d230;       // Your dual variable for constraint d230
  cpg_float    d231;       // Your dual variable for constraint d231
  cpg_float    d232;       // Your dual variable for constraint d232
  cpg_float    d233;       // Your dual variable for constraint d233
  cpg_float    d234;       // Your dual variable for constraint d234
  cpg_float    d235;       // Your dual variable for constraint d235
  cpg_float    d236;       // Your dual variable for constraint d236
  cpg_float    d237;       // Your dual variable for constraint d237
  cpg_float    d238;       // Your dual variable for constraint d238
  cpg_float    d239;       // Your dual variable for constraint d239
  cpg_float    d240;       // Your dual variable for constraint d240
  cpg_float    d241;       // Your dual variable for constraint d241
  cpg_float    d242;       // Your dual variable for constraint d242
  cpg_float    d243;       // Your dual variable for constraint d243
  cpg_float    d244;       // Your dual variable for constraint d244
  cpg_float    d245;       // Your dual variable for constraint d245
  cpg_float    d246;       // Your dual variable for constraint d246
  cpg_float    d247;       // Your dual variable for constraint d247
  cpg_float    d248;       // Your dual variable for constraint d248
  cpg_float    d249;       // Your dual variable for constraint d249
  cpg_float    d250;       // Your dual variable for constraint d250
  cpg_float    d251;       // Your dual variable for constraint d251
  cpg_float    d252;       // Your dual variable for constraint d252
  cpg_float    d253;       // Your dual variable for constraint d253
  cpg_float    d254;       // Your dual variable for constraint d254
  cpg_float    d255;       // Your dual variable for constraint d255
  cpg_float    d256;       // Your dual variable for constraint d256
  cpg_float    d257;       // Your dual variable for constraint d257
  cpg_float    d258;       // Your dual variable for constraint d258
  cpg_float    d259;       // Your dual variable for constraint d259
  cpg_float    d260;       // Your dual variable for constraint d260
  cpg_float    d261;       // Your dual variable for constraint d261
  cpg_float    d262;       // Your dual variable for constraint d262
  cpg_float    d263;       // Your dual variable for constraint d263
  cpg_float    d264;       // Your dual variable for constraint d264
  cpg_float    d265;       // Your dual variable for constraint d265
  cpg_float    d266;       // Your dual variable for constraint d266
  cpg_float    d267;       // Your dual variable for constraint d267
  cpg_float    d268;       // Your dual variable for constraint d268
  cpg_float    d269;       // Your dual variable for constraint d269
  cpg_float    d270;       // Your dual variable for constraint d270
  cpg_float    d271;       // Your dual variable for constraint d271
  cpg_float    d272;       // Your dual variable for constraint d272
  cpg_float    d273;       // Your dual variable for constraint d273
  cpg_float    d274;       // Your dual variable for constraint d274
  cpg_float    d275;       // Your dual variable for constraint d275
  cpg_float    d276;       // Your dual variable for constraint d276
  cpg_float    d277;       // Your dual variable for constraint d277
  cpg_float    d278;       // Your dual variable for constraint d278
  cpg_float    d279;       // Your dual variable for constraint d279
  cpg_float    d280;       // Your dual variable for constraint d280
  cpg_float    d281;       // Your dual variable for constraint d281
  cpg_float    d282;       // Your dual variable for constraint d282
  cpg_float    d283;       // Your dual variable for constraint d283
  cpg_float    d284;       // Your dual variable for constraint d284
  cpg_float    d285;       // Your dual variable for constraint d285
  cpg_float    d286;       // Your dual variable for constraint d286
  cpg_float    d287;       // Your dual variable for constraint d287
  cpg_float    d288;       // Your dual variable for constraint d288
  cpg_float    d289;       // Your dual variable for constraint d289
  cpg_float    d290;       // Your dual variable for constraint d290
  cpg_float    d291;       // Your dual variable for constraint d291
  cpg_float    d292;       // Your dual variable for constraint d292
  cpg_float    d293;       // Your dual variable for constraint d293
  cpg_float    d294;       // Your dual variable for constraint d294
  cpg_float    d295;       // Your dual variable for constraint d295
  cpg_float    d296;       // Your dual variable for constraint d296
  cpg_float    d297;       // Your dual variable for constraint d297
  cpg_float    d298;       // Your dual variable for constraint d298
  cpg_float    d299;       // Your dual variable for constraint d299
  cpg_float    d300;       // Your dual variable for constraint d300
  cpg_float    d301;       // Your dual variable for constraint d301
  cpg_float    d302;       // Your dual variable for constraint d302
  cpg_float    d303;       // Your dual variable for constraint d303
  cpg_float    d304;       // Your dual variable for constraint d304
  cpg_float    d305;       // Your dual variable for constraint d305
  cpg_float    d306;       // Your dual variable for constraint d306
  cpg_float    d307;       // Your dual variable for constraint d307
  cpg_float    d308;       // Your dual variable for constraint d308
  cpg_float    d309;       // Your dual variable for constraint d309
  cpg_float    d310;       // Your dual variable for constraint d310
  cpg_float    d311;       // Your dual variable for constraint d311
  cpg_float    d312;       // Your dual variable for constraint d312
  cpg_float    d313;       // Your dual variable for constraint d313
  cpg_float    d314;       // Your dual variable for constraint d314
  cpg_float    d315;       // Your dual variable for constraint d315
  cpg_float    d316;       // Your dual variable for constraint d316
  cpg_float    d317;       // Your dual variable for constraint d317
  cpg_float    d318;       // Your dual variable for constraint d318
  cpg_float    d319;       // Your dual variable for constraint d319
  cpg_float    d320;       // Your dual variable for constraint d320
  cpg_float    d321;       // Your dual variable for constraint d321
  cpg_float    d322;       // Your dual variable for constraint d322
  cpg_float    d323;       // Your dual variable for constraint d323
  cpg_float    d324;       // Your dual variable for constraint d324
  cpg_float    d325;       // Your dual variable for constraint d325
  cpg_float    d326;       // Your dual variable for constraint d326
  cpg_float    d327;       // Your dual variable for constraint d327
  cpg_float    d328;       // Your dual variable for constraint d328
  cpg_float    d329;       // Your dual variable for constraint d329
  cpg_float    d330;       // Your dual variable for constraint d330
  cpg_float    d331;       // Your dual variable for constraint d331
  cpg_float    d332;       // Your dual variable for constraint d332
  cpg_float    d333;       // Your dual variable for constraint d333
  cpg_float    d334;       // Your dual variable for constraint d334
  cpg_float    d335;       // Your dual variable for constraint d335
  cpg_float    d336;       // Your dual variable for constraint d336
  cpg_float    d337;       // Your dual variable for constraint d337
  cpg_float    d338;       // Your dual variable for constraint d338
  cpg_float    d339;       // Your dual variable for constraint d339
  cpg_float    d340;       // Your dual variable for constraint d340
  cpg_float    d341;       // Your dual variable for constraint d341
  cpg_float    d342;       // Your dual variable for constraint d342
  cpg_float    d343;       // Your dual variable for constraint d343
  cpg_float    d344;       // Your dual variable for constraint d344
  cpg_float    d345;       // Your dual variable for constraint d345
  cpg_float    d346;       // Your dual variable for constraint d346
  cpg_float    d347;       // Your dual variable for constraint d347
  cpg_float    d348;       // Your dual variable for constraint d348
  cpg_float    d349;       // Your dual variable for constraint d349
  cpg_float    d350;       // Your dual variable for constraint d350
  cpg_float    d351;       // Your dual variable for constraint d351
  cpg_float    d352;       // Your dual variable for constraint d352
  cpg_float    d353;       // Your dual variable for constraint d353
  cpg_float    d354;       // Your dual variable for constraint d354
  cpg_float    d355;       // Your dual variable for constraint d355
  cpg_float    d356;       // Your dual variable for constraint d356
  cpg_float    d357;       // Your dual variable for constraint d357
  cpg_float    d358;       // Your dual variable for constraint d358
  cpg_float    d359;       // Your dual variable for constraint d359
  cpg_float    d360;       // Your dual variable for constraint d360
  cpg_float    d361;       // Your dual variable for constraint d361
  cpg_float    d362;       // Your dual variable for constraint d362
  cpg_float    d363;       // Your dual variable for constraint d363
  cpg_float    d364;       // Your dual variable for constraint d364
  cpg_float    d365;       // Your dual variable for constraint d365
  cpg_float    d366;       // Your dual variable for constraint d366
  cpg_float    d367;       // Your dual variable for constraint d367
  cpg_float    d368;       // Your dual variable for constraint d368
  cpg_float    d369;       // Your dual variable for constraint d369
  cpg_float    d370;       // Your dual variable for constraint d370
  cpg_float    d371;       // Your dual variable for constraint d371
  cpg_float    d372;       // Your dual variable for constraint d372
  cpg_float    d373;       // Your dual variable for constraint d373
  cpg_float    d374;       // Your dual variable for constraint d374
  cpg_float    d375;       // Your dual variable for constraint d375
  cpg_float    d376;       // Your dual variable for constraint d376
  cpg_float    d377;       // Your dual variable for constraint d377
  cpg_float    d378;       // Your dual variable for constraint d378
  cpg_float    d379;       // Your dual variable for constraint d379
  cpg_float    d380;       // Your dual variable for constraint d380
  cpg_float    d381;       // Your dual variable for constraint d381
  cpg_float    d382;       // Your dual variable for constraint d382
  cpg_float    d383;       // Your dual variable for constraint d383
  cpg_float    d384;       // Your dual variable for constraint d384
  cpg_float    d385;       // Your dual variable for constraint d385
  cpg_float    d386;       // Your dual variable for constraint d386
  cpg_float    d387;       // Your dual variable for constraint d387
  cpg_float    d388;       // Your dual variable for constraint d388
  cpg_float    d389;       // Your dual variable for constraint d389
  cpg_float    d390;       // Your dual variable for constraint d390
  cpg_float    d391;       // Your dual variable for constraint d391
  cpg_float    d392;       // Your dual variable for constraint d392
  cpg_float    d393;       // Your dual variable for constraint d393
  cpg_float    d394;       // Your dual variable for constraint d394
  cpg_float    d395;       // Your dual variable for constraint d395
  cpg_float    d396;       // Your dual variable for constraint d396
  cpg_float    d397;       // Your dual variable for constraint d397
  cpg_float    d398;       // Your dual variable for constraint d398
  cpg_float    d399;       // Your dual variable for constraint d399
  cpg_float    d400;       // Your dual variable for constraint d400
  cpg_float    d401;       // Your dual variable for constraint d401
  cpg_float    d402;       // Your dual variable for constraint d402
  cpg_float    d403;       // Your dual variable for constraint d403
} CPG_Dual_t;

// Solver information
typedef struct {
  cpg_float    obj_val;    // Objective function value
  cpg_int      iter;       // Number of iterations
  cpg_int      status;     // Solver status
  cpg_float    pri_res;    // Primal residual
  cpg_float    dua_res;    // Dual residual
} CPG_Info_t;

// Solution and solver information
typedef struct {
  CPG_Prim_t *prim;        // Primal solution
  CPG_Dual_t *dual;        // Dual solution
  CPG_Info_t *info;        // Solver info
} CPG_Result_t;

// Parameter deltas
typedef struct {
  cpg_float    *sqrt_tau;   // Delta of your parameter sqrt_tau
  cpg_float    *sqrt_tau_xq_goal;   // Delta of your parameter sqrt_tau_xq_goal
  cpg_float    *tau_lamb;   // Delta of your parameter tau_lamb
  cpg_float    *start_pos;   // Delta of your parameter start_pos
  cpg_float    *end_pos;   // Delta of your parameter end_pos
  cpg_float    *A_discrete;   // Delta of your parameter A_discrete
  cpg_float    *B_discrete;   // Delta of your parameter B_discrete
  cpg_float    *y_discrete;   // Delta of your parameter y_discrete
  cpg_float    *ox_cvxpy;   // Delta of your parameter ox_cvxpy
  cpg_float    *ou_cvxpy;   // Delta of your parameter ou_cvxpy
  cpg_float    *etta;      // Delta of your parameter etta
  cpg_float    *S_x_scaling;   // Delta of your parameter S_x_scaling
  cpg_float    *c_x_scaling;   // Delta of your parameter c_x_scaling
  cpg_float    *omega_max;   // Delta of your parameter omega_max
  cpg_float    *S_u_scaling;   // Delta of your parameter S_u_scaling
  cpg_float    *c_u_scaling;   // Delta of your parameter c_u_scaling
  cpg_float    *m_max;     // Delta of your parameter m_max
} CPG_Delta_t;

// Solver settings
typedef struct {
  cpg_float  feastol;
  cpg_float  abstol;
  cpg_float  reltol;
  cpg_float  feastol_inacc;
  cpg_float  abstol_inacc;
  cpg_float  reltol_inacc;
  cpg_int    maxit;
} Canon_Settings_t;

#endif // ifndef CPG_TYPES_H

// Vector containing flattened user-defined parameters
extern cpg_float cpg_params_vec[8802];

// Sparse mappings from user-defined to canonical parameters
extern cpg_csc canon_A_map;
extern cpg_csc canon_b_map;
extern cpg_csc canon_G_map;
extern cpg_csc canon_h_map;

// Canonical parameters
extern cpg_float canon_c[4520];
extern cpg_float canon_c_conditioning[4520];
extern cpg_csc canon_A;
extern cpg_csc canon_A_conditioning;
extern cpg_float canon_b[714];
extern cpg_float canon_b_conditioning[714];
extern cpg_csc canon_G;
extern cpg_csc canon_G_conditioning;
extern cpg_float canon_h[8040];
extern cpg_float canon_h_conditioning[8040];

// Struct containing canonical parameters
extern Canon_Params_t Canon_Params;
extern Canon_Params_t Canon_Params_conditioning;

// Struct containing flags for outdated canonical parameters
extern Canon_Outdated_t Canon_Outdated;

// User-defined variables
extern cpg_float cpg_u[300];
extern cpg_float cpg_x[707];
extern cpg_float cpg_vc[700];

// Dual variables associated with user-defined constraints
extern cpg_float cpg_d0[7];
extern cpg_float cpg_d1[7];
extern cpg_float cpg_d2[7];
extern cpg_float cpg_d3[7];
extern cpg_float cpg_d4[7];
extern cpg_float cpg_d5[7];
extern cpg_float cpg_d6[7];
extern cpg_float cpg_d7[7];
extern cpg_float cpg_d8[7];
extern cpg_float cpg_d9[7];
extern cpg_float cpg_d10[7];
extern cpg_float cpg_d11[7];
extern cpg_float cpg_d12[7];
extern cpg_float cpg_d13[7];
extern cpg_float cpg_d14[7];
extern cpg_float cpg_d15[7];
extern cpg_float cpg_d16[7];
extern cpg_float cpg_d17[7];
extern cpg_float cpg_d18[7];
extern cpg_float cpg_d19[7];
extern cpg_float cpg_d20[7];
extern cpg_float cpg_d21[7];
extern cpg_float cpg_d22[7];
extern cpg_float cpg_d23[7];
extern cpg_float cpg_d24[7];
extern cpg_float cpg_d25[7];
extern cpg_float cpg_d26[7];
extern cpg_float cpg_d27[7];
extern cpg_float cpg_d28[7];
extern cpg_float cpg_d29[7];
extern cpg_float cpg_d30[7];
extern cpg_float cpg_d31[7];
extern cpg_float cpg_d32[7];
extern cpg_float cpg_d33[7];
extern cpg_float cpg_d34[7];
extern cpg_float cpg_d35[7];
extern cpg_float cpg_d36[7];
extern cpg_float cpg_d37[7];
extern cpg_float cpg_d38[7];
extern cpg_float cpg_d39[7];
extern cpg_float cpg_d40[7];
extern cpg_float cpg_d41[7];
extern cpg_float cpg_d42[7];
extern cpg_float cpg_d43[7];
extern cpg_float cpg_d44[7];
extern cpg_float cpg_d45[7];
extern cpg_float cpg_d46[7];
extern cpg_float cpg_d47[7];
extern cpg_float cpg_d48[7];
extern cpg_float cpg_d49[7];
extern cpg_float cpg_d50[7];
extern cpg_float cpg_d51[7];
extern cpg_float cpg_d52[7];
extern cpg_float cpg_d53[7];
extern cpg_float cpg_d54[7];
extern cpg_float cpg_d55[7];
extern cpg_float cpg_d56[7];
extern cpg_float cpg_d57[7];
extern cpg_float cpg_d58[7];
extern cpg_float cpg_d59[7];
extern cpg_float cpg_d60[7];
extern cpg_float cpg_d61[7];
extern cpg_float cpg_d62[7];
extern cpg_float cpg_d63[7];
extern cpg_float cpg_d64[7];
extern cpg_float cpg_d65[7];
extern cpg_float cpg_d66[7];
extern cpg_float cpg_d67[7];
extern cpg_float cpg_d68[7];
extern cpg_float cpg_d69[7];
extern cpg_float cpg_d70[7];
extern cpg_float cpg_d71[7];
extern cpg_float cpg_d72[7];
extern cpg_float cpg_d73[7];
extern cpg_float cpg_d74[7];
extern cpg_float cpg_d75[7];
extern cpg_float cpg_d76[7];
extern cpg_float cpg_d77[7];
extern cpg_float cpg_d78[7];
extern cpg_float cpg_d79[7];
extern cpg_float cpg_d80[7];
extern cpg_float cpg_d81[7];
extern cpg_float cpg_d82[7];
extern cpg_float cpg_d83[7];
extern cpg_float cpg_d84[7];
extern cpg_float cpg_d85[7];
extern cpg_float cpg_d86[7];
extern cpg_float cpg_d87[7];
extern cpg_float cpg_d88[7];
extern cpg_float cpg_d89[7];
extern cpg_float cpg_d90[7];
extern cpg_float cpg_d91[7];
extern cpg_float cpg_d92[7];
extern cpg_float cpg_d93[7];
extern cpg_float cpg_d94[7];
extern cpg_float cpg_d95[7];
extern cpg_float cpg_d96[7];
extern cpg_float cpg_d97[7];
extern cpg_float cpg_d98[7];
extern cpg_float cpg_d99[7];
extern cpg_float cpg_d100[7];
extern cpg_float cpg_d101[7];

// Struct containing primal solution
extern CPG_Prim_t CPG_Prim;

// Struct containing dual solution
extern CPG_Dual_t CPG_Dual;

// Struct containing solver info
extern CPG_Info_t CPG_Info;

// Struct containing solution and info
extern CPG_Result_t CPG_Result;

// Struct containing solver settings
extern Canon_Settings_t Canon_Settings;

// ECOS array of SOC dimensions
extern cpg_int ecos_q[401];

// ECOS workspace
extern pwork* ecos_workspace;

// ECOS exit flag
extern cpg_int ecos_flag;
