
"""
Auto-generated by CVXPYgen on April 17, 2026 at 13:06:24.
Content: Custom solve method for CVXPY interface.
"""

import time
import warnings
import numpy as np
from cvxpy.reductions import Solution
from cvxpy.problems.problem import SolverStats
from Astrobee_GuSTO_ECOS_T31_l2 import cpg_module


standard_settings_names = {'max_iters': 'maxit'}


def squeeze_scalar(val):
    if isinstance(val, np.ndarray):
        val = val.squeeze()
        if val.shape == ():
            return val.item()
    return val


def cpg_solve(prob, updated_params=None, **kwargs):

    # set flags for updated parameters
    upd = cpg_module.cpg_updated()
    if updated_params is None:
        updated_params = ["sqrt_tau", "sqrt_tau_sqrt_lamb", "sqrt_tau_sqrt_lamb_ox", "sqrt_tau_sqrt_lamb_etta", "sqrt_tau_sqrt_lamb_C_discrete", "sqrt_tau_sqrt_lamb_z_discrete", "sqrt_tau_sqrt_lamb_S_x_scaling", "sqrt_tau_sqrt_lamb_c_x_scaling", "sqrt_tau_sqrt_lamb_vel_max", "sqrt_tau_sqrt_lamb_omega_max", "start_pos", "end_pos", "A_discrete", "B_discrete_l", "B_discrete_r", "y_discrete", "S_u_scaling", "c_u_scaling", "acc_max", "torq_max"]
    for p in updated_params:
        try:
            setattr(upd, p, True)
        except AttributeError:
            raise AttributeError(f"{p} is not a parameter.")

    # set solver settings
    cpg_module.set_solver_default_settings()
    for key, value in kwargs.items():
        try:
            eval(f'cpg_module.set_solver_{standard_settings_names.get(key, key)}(value)')
        except AttributeError:
            raise AttributeError(f'Solver setting "{key}" not available.')

    # set parameter values
    par = cpg_module.cpg_params()
    param_dict = prob.param_dict
    par.sqrt_tau = squeeze_scalar(param_dict["sqrt_tau"].value)
    par.sqrt_tau_sqrt_lamb = squeeze_scalar(param_dict["sqrt_tau_sqrt_lamb"].value)
    par.sqrt_tau_sqrt_lamb_ox = list(param_dict["sqrt_tau_sqrt_lamb_ox"].value.flatten(order="F"))
    par.sqrt_tau_sqrt_lamb_etta = squeeze_scalar(param_dict["sqrt_tau_sqrt_lamb_etta"].value)
    par.sqrt_tau_sqrt_lamb_C_discrete = list(param_dict["sqrt_tau_sqrt_lamb_C_discrete"].value.flatten(order="F"))
    par.sqrt_tau_sqrt_lamb_z_discrete = list(param_dict["sqrt_tau_sqrt_lamb_z_discrete"].value.flatten(order="F"))
    par.sqrt_tau_sqrt_lamb_S_x_scaling = list(param_dict["sqrt_tau_sqrt_lamb_S_x_scaling"].value.flatten(order="F"))
    par.sqrt_tau_sqrt_lamb_c_x_scaling = list(param_dict["sqrt_tau_sqrt_lamb_c_x_scaling"].value.flatten(order="F"))
    par.sqrt_tau_sqrt_lamb_vel_max = squeeze_scalar(param_dict["sqrt_tau_sqrt_lamb_vel_max"].value)
    par.sqrt_tau_sqrt_lamb_omega_max = squeeze_scalar(param_dict["sqrt_tau_sqrt_lamb_omega_max"].value)
    par.start_pos = list(param_dict["start_pos"].value.flatten(order="F"))
    par.end_pos = list(param_dict["end_pos"].value.flatten(order="F"))
    par.A_discrete = list(param_dict["A_discrete"].value.flatten(order="F"))
    par.B_discrete_l = list(param_dict["B_discrete_l"].value.flatten(order="F"))
    par.B_discrete_r = list(param_dict["B_discrete_r"].value.flatten(order="F"))
    par.y_discrete = list(param_dict["y_discrete"].value.flatten(order="F"))
    par.S_u_scaling = list(param_dict["S_u_scaling"].value.flatten(order="F"))
    par.c_u_scaling = list(param_dict["c_u_scaling"].value.flatten(order="F"))
    par.acc_max = squeeze_scalar(param_dict["acc_max"].value)
    par.torq_max = squeeze_scalar(param_dict["torq_max"].value)

    # solve
    t0 = time.time()
    res = cpg_module.solve(upd, par)
    t1 = time.time()

    # store solution in problem object
    prob._clear_solution()
    prob.var_dict['u'].save_value(np.array(res.cpg_prim.u).reshape((6, 31), order='F'))
    prob.var_dict['x'].save_value(np.array(res.cpg_prim.x).reshape((13, 31), order='F'))
    prob.constraints[0].save_dual_value(np.array(res.cpg_dual.d0).reshape((13,), order='F'))
    prob.constraints[1].save_dual_value(np.array(res.cpg_dual.d1).reshape((13,), order='F'))
    prob.constraints[2].save_dual_value(np.array(res.cpg_dual.d2).reshape((13, 1), order='F'))
    prob.constraints[3].save_dual_value(np.array(res.cpg_dual.d3).reshape((13, 1), order='F'))
    prob.constraints[4].save_dual_value(np.array(res.cpg_dual.d4).reshape((13, 1), order='F'))
    prob.constraints[5].save_dual_value(np.array(res.cpg_dual.d5).reshape((13, 1), order='F'))
    prob.constraints[6].save_dual_value(np.array(res.cpg_dual.d6).reshape((13, 1), order='F'))
    prob.constraints[7].save_dual_value(np.array(res.cpg_dual.d7).reshape((13, 1), order='F'))
    prob.constraints[8].save_dual_value(np.array(res.cpg_dual.d8).reshape((13, 1), order='F'))
    prob.constraints[9].save_dual_value(np.array(res.cpg_dual.d9).reshape((13, 1), order='F'))
    prob.constraints[10].save_dual_value(np.array(res.cpg_dual.d10).reshape((13, 1), order='F'))
    prob.constraints[11].save_dual_value(np.array(res.cpg_dual.d11).reshape((13, 1), order='F'))
    prob.constraints[12].save_dual_value(np.array(res.cpg_dual.d12).reshape((13, 1), order='F'))
    prob.constraints[13].save_dual_value(np.array(res.cpg_dual.d13).reshape((13, 1), order='F'))
    prob.constraints[14].save_dual_value(np.array(res.cpg_dual.d14).reshape((13, 1), order='F'))
    prob.constraints[15].save_dual_value(np.array(res.cpg_dual.d15).reshape((13, 1), order='F'))
    prob.constraints[16].save_dual_value(np.array(res.cpg_dual.d16).reshape((13, 1), order='F'))
    prob.constraints[17].save_dual_value(np.array(res.cpg_dual.d17).reshape((13, 1), order='F'))
    prob.constraints[18].save_dual_value(np.array(res.cpg_dual.d18).reshape((13, 1), order='F'))
    prob.constraints[19].save_dual_value(np.array(res.cpg_dual.d19).reshape((13, 1), order='F'))
    prob.constraints[20].save_dual_value(np.array(res.cpg_dual.d20).reshape((13, 1), order='F'))
    prob.constraints[21].save_dual_value(np.array(res.cpg_dual.d21).reshape((13, 1), order='F'))
    prob.constraints[22].save_dual_value(np.array(res.cpg_dual.d22).reshape((13, 1), order='F'))
    prob.constraints[23].save_dual_value(np.array(res.cpg_dual.d23).reshape((13, 1), order='F'))
    prob.constraints[24].save_dual_value(np.array(res.cpg_dual.d24).reshape((13, 1), order='F'))
    prob.constraints[25].save_dual_value(np.array(res.cpg_dual.d25).reshape((13, 1), order='F'))
    prob.constraints[26].save_dual_value(np.array(res.cpg_dual.d26).reshape((13, 1), order='F'))
    prob.constraints[27].save_dual_value(np.array(res.cpg_dual.d27).reshape((13, 1), order='F'))
    prob.constraints[28].save_dual_value(np.array(res.cpg_dual.d28).reshape((13, 1), order='F'))
    prob.constraints[29].save_dual_value(np.array(res.cpg_dual.d29).reshape((13, 1), order='F'))
    prob.constraints[30].save_dual_value(np.array(res.cpg_dual.d30).reshape((13, 1), order='F'))
    prob.constraints[31].save_dual_value(np.array(res.cpg_dual.d31).reshape((13, 1), order='F'))
    prob.constraints[32].save_dual_value(np.array(res.cpg_dual.d32))
    prob.constraints[33].save_dual_value(np.array(res.cpg_dual.d33))
    prob.constraints[34].save_dual_value(np.array(res.cpg_dual.d34))
    prob.constraints[35].save_dual_value(np.array(res.cpg_dual.d35))
    prob.constraints[36].save_dual_value(np.array(res.cpg_dual.d36))
    prob.constraints[37].save_dual_value(np.array(res.cpg_dual.d37))
    prob.constraints[38].save_dual_value(np.array(res.cpg_dual.d38))
    prob.constraints[39].save_dual_value(np.array(res.cpg_dual.d39))
    prob.constraints[40].save_dual_value(np.array(res.cpg_dual.d40))
    prob.constraints[41].save_dual_value(np.array(res.cpg_dual.d41))
    prob.constraints[42].save_dual_value(np.array(res.cpg_dual.d42))
    prob.constraints[43].save_dual_value(np.array(res.cpg_dual.d43))
    prob.constraints[44].save_dual_value(np.array(res.cpg_dual.d44))
    prob.constraints[45].save_dual_value(np.array(res.cpg_dual.d45))
    prob.constraints[46].save_dual_value(np.array(res.cpg_dual.d46))
    prob.constraints[47].save_dual_value(np.array(res.cpg_dual.d47))
    prob.constraints[48].save_dual_value(np.array(res.cpg_dual.d48))
    prob.constraints[49].save_dual_value(np.array(res.cpg_dual.d49))
    prob.constraints[50].save_dual_value(np.array(res.cpg_dual.d50))
    prob.constraints[51].save_dual_value(np.array(res.cpg_dual.d51))
    prob.constraints[52].save_dual_value(np.array(res.cpg_dual.d52))
    prob.constraints[53].save_dual_value(np.array(res.cpg_dual.d53))
    prob.constraints[54].save_dual_value(np.array(res.cpg_dual.d54))
    prob.constraints[55].save_dual_value(np.array(res.cpg_dual.d55))
    prob.constraints[56].save_dual_value(np.array(res.cpg_dual.d56))
    prob.constraints[57].save_dual_value(np.array(res.cpg_dual.d57))
    prob.constraints[58].save_dual_value(np.array(res.cpg_dual.d58))
    prob.constraints[59].save_dual_value(np.array(res.cpg_dual.d59))
    prob.constraints[60].save_dual_value(np.array(res.cpg_dual.d60))
    prob.constraints[61].save_dual_value(np.array(res.cpg_dual.d61))
    prob.constraints[62].save_dual_value(np.array(res.cpg_dual.d62))
    prob.constraints[63].save_dual_value(np.array(res.cpg_dual.d63))
    prob.constraints[64].save_dual_value(np.array(res.cpg_dual.d64))
    prob.constraints[65].save_dual_value(np.array(res.cpg_dual.d65))
    prob.constraints[66].save_dual_value(np.array(res.cpg_dual.d66))
    prob.constraints[67].save_dual_value(np.array(res.cpg_dual.d67))
    prob.constraints[68].save_dual_value(np.array(res.cpg_dual.d68))
    prob.constraints[69].save_dual_value(np.array(res.cpg_dual.d69))
    prob.constraints[70].save_dual_value(np.array(res.cpg_dual.d70))
    prob.constraints[71].save_dual_value(np.array(res.cpg_dual.d71))
    prob.constraints[72].save_dual_value(np.array(res.cpg_dual.d72))
    prob.constraints[73].save_dual_value(np.array(res.cpg_dual.d73))
    prob.constraints[74].save_dual_value(np.array(res.cpg_dual.d74))
    prob.constraints[75].save_dual_value(np.array(res.cpg_dual.d75))
    prob.constraints[76].save_dual_value(np.array(res.cpg_dual.d76))
    prob.constraints[77].save_dual_value(np.array(res.cpg_dual.d77))
    prob.constraints[78].save_dual_value(np.array(res.cpg_dual.d78))
    prob.constraints[79].save_dual_value(np.array(res.cpg_dual.d79))
    prob.constraints[80].save_dual_value(np.array(res.cpg_dual.d80))
    prob.constraints[81].save_dual_value(np.array(res.cpg_dual.d81))
    prob.constraints[82].save_dual_value(np.array(res.cpg_dual.d82))
    prob.constraints[83].save_dual_value(np.array(res.cpg_dual.d83))
    prob.constraints[84].save_dual_value(np.array(res.cpg_dual.d84))
    prob.constraints[85].save_dual_value(np.array(res.cpg_dual.d85))
    prob.constraints[86].save_dual_value(np.array(res.cpg_dual.d86))
    prob.constraints[87].save_dual_value(np.array(res.cpg_dual.d87))
    prob.constraints[88].save_dual_value(np.array(res.cpg_dual.d88))
    prob.constraints[89].save_dual_value(np.array(res.cpg_dual.d89))
    prob.constraints[90].save_dual_value(np.array(res.cpg_dual.d90))
    prob.constraints[91].save_dual_value(np.array(res.cpg_dual.d91))
    prob.constraints[92].save_dual_value(np.array(res.cpg_dual.d92))
    prob.constraints[93].save_dual_value(np.array(res.cpg_dual.d93))

    # store additional solver information in problem object
    prob._status = "%d (for description visit https://github.com/embotech/ecos/wiki/Usage-from-C)" % res.cpg_info.status
    if abs(res.cpg_info.obj_val) == 1e30:
        prob._value = np.sign(res.cpg_info.obj_val) * np.inf
    else:
        prob._value = res.cpg_info.obj_val
    primal_vars = {var.id: var.value for var in prob.variables()}
    dual_vars = {c.id: c.dual_value for c in prob.constraints}
    solver_specific_stats = {'obj_val': res.cpg_info.obj_val,
                             'status': prob._status,
                             'iter': res.cpg_info.iter,
                             'pri_res': res.cpg_info.pri_res,
                             'dua_res': res.cpg_info.dua_res,
                             'time': res.cpg_info.time}
    attr = {'solve_time': t1 - t0, 'solver_specific_stats': solver_specific_stats, 'num_iters': res.cpg_info.iter}
    prob._solution = Solution(prob.status, prob.value, primal_vars, dual_vars, attr)
    results_dict = {'solver_specific_stats': solver_specific_stats,
                    'num_iters': res.cpg_info.iter,
                    'solve_time': t1 - t0}
    prob._solver_stats = SolverStats.from_dict(results_dict, 'ECOS')

    return prob.value


