
/*
Auto-generated by CVXPYgen on May 29, 2026 at 14:48:01.
Content: Type definitions and variable declarations.
*/

#include "ecos.h"

#ifndef CPG_TYPES_H
# define CPG_TYPES_H

typedef double cpg_float;
typedef int cpg_int;

// Compressed sparse column matrix
typedef struct {
  cpg_int      *p;
  cpg_int      *i;
  cpg_float    *x;
  cpg_int      nnz;
} cpg_csc;

// Canonical parameters
typedef struct {
  cpg_float    *c;         // Canonical parameter c
  cpg_float    d;          // Canonical parameter d
  cpg_csc      *A;         // Canonical parameter A
  cpg_float    *b;         // Canonical parameter b
  cpg_csc      *G;         // Canonical parameter G
  cpg_float    *h;         // Canonical parameter h
} Canon_Params_t;

// Flags indicating outdated canonical parameters
typedef struct {
  int        c;            // Bool, if canonical parameter c outdated
  int        d;            // Bool, if canonical parameter d outdated
  int        A;            // Bool, if canonical parameter A outdated
  int        b;            // Bool, if canonical parameter b outdated
  int        G;            // Bool, if canonical parameter G outdated
  int        h;            // Bool, if canonical parameter h outdated
} Canon_Outdated_t;

// Primal solution
typedef struct {
  cpg_float    *u;         // Your variable u
  cpg_float    *vc;        // Your variable vc
  cpg_float    *vi;        // Your variable vi
  cpg_float    *x;         // Your variable x
} CPG_Prim_t;

// Dual solution
typedef struct {
  cpg_float    *d0;        // Your dual variable for constraint d0
  cpg_float    *d1;        // Your dual variable for constraint d1
  cpg_float    *d2;        // Your dual variable for constraint d2
  cpg_float    *d3;        // Your dual variable for constraint d3
  cpg_float    *d4;        // Your dual variable for constraint d4
  cpg_float    *d5;        // Your dual variable for constraint d5
  cpg_float    *d6;        // Your dual variable for constraint d6
  cpg_float    *d7;        // Your dual variable for constraint d7
  cpg_float    *d8;        // Your dual variable for constraint d8
  cpg_float    *d9;        // Your dual variable for constraint d9
  cpg_float    *d10;       // Your dual variable for constraint d10
  cpg_float    *d11;       // Your dual variable for constraint d11
  cpg_float    *d12;       // Your dual variable for constraint d12
  cpg_float    *d13;       // Your dual variable for constraint d13
  cpg_float    *d14;       // Your dual variable for constraint d14
  cpg_float    *d15;       // Your dual variable for constraint d15
  cpg_float    *d16;       // Your dual variable for constraint d16
  cpg_float    *d17;       // Your dual variable for constraint d17
  cpg_float    *d18;       // Your dual variable for constraint d18
  cpg_float    *d19;       // Your dual variable for constraint d19
  cpg_float    *d20;       // Your dual variable for constraint d20
  cpg_float    *d21;       // Your dual variable for constraint d21
  cpg_float    *d22;       // Your dual variable for constraint d22
  cpg_float    *d23;       // Your dual variable for constraint d23
  cpg_float    *d24;       // Your dual variable for constraint d24
  cpg_float    *d25;       // Your dual variable for constraint d25
  cpg_float    *d26;       // Your dual variable for constraint d26
  cpg_float    *d27;       // Your dual variable for constraint d27
  cpg_float    *d28;       // Your dual variable for constraint d28
  cpg_float    *d29;       // Your dual variable for constraint d29
  cpg_float    *d30;       // Your dual variable for constraint d30
  cpg_float    *d31;       // Your dual variable for constraint d31
  cpg_float    d32;        // Your dual variable for constraint d32
  cpg_float    d33;        // Your dual variable for constraint d33
  cpg_float    d34;        // Your dual variable for constraint d34
  cpg_float    d35;        // Your dual variable for constraint d35
  cpg_float    d36;        // Your dual variable for constraint d36
  cpg_float    d37;        // Your dual variable for constraint d37
  cpg_float    d38;        // Your dual variable for constraint d38
  cpg_float    d39;        // Your dual variable for constraint d39
  cpg_float    d40;        // Your dual variable for constraint d40
  cpg_float    d41;        // Your dual variable for constraint d41
  cpg_float    d42;        // Your dual variable for constraint d42
  cpg_float    d43;        // Your dual variable for constraint d43
  cpg_float    d44;        // Your dual variable for constraint d44
  cpg_float    d45;        // Your dual variable for constraint d45
  cpg_float    d46;        // Your dual variable for constraint d46
  cpg_float    d47;        // Your dual variable for constraint d47
  cpg_float    d48;        // Your dual variable for constraint d48
  cpg_float    d49;        // Your dual variable for constraint d49
  cpg_float    d50;        // Your dual variable for constraint d50
  cpg_float    d51;        // Your dual variable for constraint d51
  cpg_float    d52;        // Your dual variable for constraint d52
  cpg_float    d53;        // Your dual variable for constraint d53
  cpg_float    d54;        // Your dual variable for constraint d54
  cpg_float    d55;        // Your dual variable for constraint d55
  cpg_float    d56;        // Your dual variable for constraint d56
  cpg_float    d57;        // Your dual variable for constraint d57
  cpg_float    d58;        // Your dual variable for constraint d58
  cpg_float    d59;        // Your dual variable for constraint d59
  cpg_float    d60;        // Your dual variable for constraint d60
  cpg_float    d61;        // Your dual variable for constraint d61
  cpg_float    d62;        // Your dual variable for constraint d62
  cpg_float    *d63;       // Your dual variable for constraint d63
  cpg_float    *d64;       // Your dual variable for constraint d64
  cpg_float    *d65;       // Your dual variable for constraint d65
  cpg_float    *d66;       // Your dual variable for constraint d66
  cpg_float    *d67;       // Your dual variable for constraint d67
  cpg_float    *d68;       // Your dual variable for constraint d68
  cpg_float    *d69;       // Your dual variable for constraint d69
  cpg_float    *d70;       // Your dual variable for constraint d70
  cpg_float    *d71;       // Your dual variable for constraint d71
  cpg_float    *d72;       // Your dual variable for constraint d72
  cpg_float    *d73;       // Your dual variable for constraint d73
  cpg_float    *d74;       // Your dual variable for constraint d74
  cpg_float    *d75;       // Your dual variable for constraint d75
  cpg_float    *d76;       // Your dual variable for constraint d76
  cpg_float    *d77;       // Your dual variable for constraint d77
  cpg_float    *d78;       // Your dual variable for constraint d78
  cpg_float    *d79;       // Your dual variable for constraint d79
  cpg_float    *d80;       // Your dual variable for constraint d80
  cpg_float    *d81;       // Your dual variable for constraint d81
  cpg_float    *d82;       // Your dual variable for constraint d82
  cpg_float    *d83;       // Your dual variable for constraint d83
  cpg_float    *d84;       // Your dual variable for constraint d84
  cpg_float    *d85;       // Your dual variable for constraint d85
  cpg_float    *d86;       // Your dual variable for constraint d86
  cpg_float    *d87;       // Your dual variable for constraint d87
  cpg_float    *d88;       // Your dual variable for constraint d88
  cpg_float    *d89;       // Your dual variable for constraint d89
  cpg_float    *d90;       // Your dual variable for constraint d90
  cpg_float    *d91;       // Your dual variable for constraint d91
  cpg_float    *d92;       // Your dual variable for constraint d92
  cpg_float    *d93;       // Your dual variable for constraint d93
  cpg_float    d94;        // Your dual variable for constraint d94
  cpg_float    d95;        // Your dual variable for constraint d95
  cpg_float    d96;        // Your dual variable for constraint d96
  cpg_float    d97;        // Your dual variable for constraint d97
  cpg_float    d98;        // Your dual variable for constraint d98
  cpg_float    d99;        // Your dual variable for constraint d99
  cpg_float    d100;       // Your dual variable for constraint d100
  cpg_float    d101;       // Your dual variable for constraint d101
  cpg_float    d102;       // Your dual variable for constraint d102
  cpg_float    d103;       // Your dual variable for constraint d103
  cpg_float    d104;       // Your dual variable for constraint d104
  cpg_float    d105;       // Your dual variable for constraint d105
  cpg_float    d106;       // Your dual variable for constraint d106
  cpg_float    d107;       // Your dual variable for constraint d107
  cpg_float    d108;       // Your dual variable for constraint d108
  cpg_float    d109;       // Your dual variable for constraint d109
  cpg_float    d110;       // Your dual variable for constraint d110
  cpg_float    d111;       // Your dual variable for constraint d111
  cpg_float    d112;       // Your dual variable for constraint d112
  cpg_float    d113;       // Your dual variable for constraint d113
  cpg_float    d114;       // Your dual variable for constraint d114
  cpg_float    d115;       // Your dual variable for constraint d115
  cpg_float    d116;       // Your dual variable for constraint d116
  cpg_float    d117;       // Your dual variable for constraint d117
  cpg_float    d118;       // Your dual variable for constraint d118
  cpg_float    d119;       // Your dual variable for constraint d119
  cpg_float    d120;       // Your dual variable for constraint d120
  cpg_float    d121;       // Your dual variable for constraint d121
  cpg_float    d122;       // Your dual variable for constraint d122
  cpg_float    d123;       // Your dual variable for constraint d123
  cpg_float    d124;       // Your dual variable for constraint d124
  cpg_float    d125;       // Your dual variable for constraint d125
  cpg_float    d126;       // Your dual variable for constraint d126
  cpg_float    d127;       // Your dual variable for constraint d127
  cpg_float    d128;       // Your dual variable for constraint d128
  cpg_float    d129;       // Your dual variable for constraint d129
  cpg_float    d130;       // Your dual variable for constraint d130
  cpg_float    d131;       // Your dual variable for constraint d131
  cpg_float    d132;       // Your dual variable for constraint d132
  cpg_float    d133;       // Your dual variable for constraint d133
  cpg_float    d134;       // Your dual variable for constraint d134
  cpg_float    d135;       // Your dual variable for constraint d135
  cpg_float    d136;       // Your dual variable for constraint d136
  cpg_float    d137;       // Your dual variable for constraint d137
  cpg_float    d138;       // Your dual variable for constraint d138
  cpg_float    d139;       // Your dual variable for constraint d139
  cpg_float    d140;       // Your dual variable for constraint d140
  cpg_float    d141;       // Your dual variable for constraint d141
  cpg_float    d142;       // Your dual variable for constraint d142
  cpg_float    d143;       // Your dual variable for constraint d143
  cpg_float    d144;       // Your dual variable for constraint d144
  cpg_float    d145;       // Your dual variable for constraint d145
  cpg_float    d146;       // Your dual variable for constraint d146
  cpg_float    d147;       // Your dual variable for constraint d147
  cpg_float    d148;       // Your dual variable for constraint d148
  cpg_float    d149;       // Your dual variable for constraint d149
  cpg_float    d150;       // Your dual variable for constraint d150
  cpg_float    d151;       // Your dual variable for constraint d151
  cpg_float    d152;       // Your dual variable for constraint d152
  cpg_float    d153;       // Your dual variable for constraint d153
  cpg_float    d154;       // Your dual variable for constraint d154
  cpg_float    d155;       // Your dual variable for constraint d155
  cpg_float    d156;       // Your dual variable for constraint d156
  cpg_float    d157;       // Your dual variable for constraint d157
  cpg_float    d158;       // Your dual variable for constraint d158
  cpg_float    d159;       // Your dual variable for constraint d159
  cpg_float    d160;       // Your dual variable for constraint d160
  cpg_float    d161;       // Your dual variable for constraint d161
  cpg_float    d162;       // Your dual variable for constraint d162
  cpg_float    d163;       // Your dual variable for constraint d163
  cpg_float    d164;       // Your dual variable for constraint d164
  cpg_float    d165;       // Your dual variable for constraint d165
  cpg_float    d166;       // Your dual variable for constraint d166
  cpg_float    d167;       // Your dual variable for constraint d167
  cpg_float    d168;       // Your dual variable for constraint d168
  cpg_float    d169;       // Your dual variable for constraint d169
  cpg_float    d170;       // Your dual variable for constraint d170
  cpg_float    d171;       // Your dual variable for constraint d171
  cpg_float    d172;       // Your dual variable for constraint d172
  cpg_float    d173;       // Your dual variable for constraint d173
  cpg_float    d174;       // Your dual variable for constraint d174
  cpg_float    d175;       // Your dual variable for constraint d175
  cpg_float    d176;       // Your dual variable for constraint d176
  cpg_float    d177;       // Your dual variable for constraint d177
  cpg_float    d178;       // Your dual variable for constraint d178
  cpg_float    d179;       // Your dual variable for constraint d179
  cpg_float    d180;       // Your dual variable for constraint d180
  cpg_float    d181;       // Your dual variable for constraint d181
  cpg_float    d182;       // Your dual variable for constraint d182
  cpg_float    d183;       // Your dual variable for constraint d183
  cpg_float    d184;       // Your dual variable for constraint d184
  cpg_float    d185;       // Your dual variable for constraint d185
  cpg_float    d186;       // Your dual variable for constraint d186
  cpg_float    d187;       // Your dual variable for constraint d187
  cpg_float    d188;       // Your dual variable for constraint d188
  cpg_float    d189;       // Your dual variable for constraint d189
  cpg_float    d190;       // Your dual variable for constraint d190
  cpg_float    d191;       // Your dual variable for constraint d191
  cpg_float    d192;       // Your dual variable for constraint d192
  cpg_float    d193;       // Your dual variable for constraint d193
  cpg_float    d194;       // Your dual variable for constraint d194
  cpg_float    d195;       // Your dual variable for constraint d195
  cpg_float    d196;       // Your dual variable for constraint d196
  cpg_float    d197;       // Your dual variable for constraint d197
  cpg_float    d198;       // Your dual variable for constraint d198
  cpg_float    d199;       // Your dual variable for constraint d199
  cpg_float    d200;       // Your dual variable for constraint d200
  cpg_float    d201;       // Your dual variable for constraint d201
  cpg_float    d202;       // Your dual variable for constraint d202
  cpg_float    d203;       // Your dual variable for constraint d203
  cpg_float    d204;       // Your dual variable for constraint d204
  cpg_float    d205;       // Your dual variable for constraint d205
  cpg_float    d206;       // Your dual variable for constraint d206
  cpg_float    d207;       // Your dual variable for constraint d207
  cpg_float    d208;       // Your dual variable for constraint d208
  cpg_float    d209;       // Your dual variable for constraint d209
  cpg_float    d210;       // Your dual variable for constraint d210
  cpg_float    d211;       // Your dual variable for constraint d211
  cpg_float    d212;       // Your dual variable for constraint d212
  cpg_float    d213;       // Your dual variable for constraint d213
  cpg_float    d214;       // Your dual variable for constraint d214
  cpg_float    d215;       // Your dual variable for constraint d215
} CPG_Dual_t;

// Solver information
typedef struct {
  cpg_float    obj_val;    // Objective function value
  cpg_int      iter;       // Number of iterations
  cpg_int      status;     // Solver status
  cpg_float    pri_res;    // Primal residual
  cpg_float    dua_res;    // Dual residual
} CPG_Info_t;

// Solution and solver information
typedef struct {
  CPG_Prim_t *prim;        // Primal solution
  CPG_Dual_t *dual;        // Dual solution
  CPG_Info_t *info;        // Solver info
} CPG_Result_t;

// Parameter deltas
typedef struct {
  cpg_float    *start_pos;   // Delta of your parameter start_pos
  cpg_float    *end_pos;   // Delta of your parameter end_pos
  cpg_float    *A_0;       // Delta of your parameter A_0
  cpg_float    *B_0;       // Delta of your parameter B_0
  cpg_float    *y_0;       // Delta of your parameter y_0
  cpg_float    *A_1;       // Delta of your parameter A_1
  cpg_float    *B_1;       // Delta of your parameter B_1
  cpg_float    *y_1;       // Delta of your parameter y_1
  cpg_float    *A_2;       // Delta of your parameter A_2
  cpg_float    *B_2;       // Delta of your parameter B_2
  cpg_float    *y_2;       // Delta of your parameter y_2
  cpg_float    *A_3;       // Delta of your parameter A_3
  cpg_float    *B_3;       // Delta of your parameter B_3
  cpg_float    *y_3;       // Delta of your parameter y_3
  cpg_float    *A_4;       // Delta of your parameter A_4
  cpg_float    *B_4;       // Delta of your parameter B_4
  cpg_float    *y_4;       // Delta of your parameter y_4
  cpg_float    *A_5;       // Delta of your parameter A_5
  cpg_float    *B_5;       // Delta of your parameter B_5
  cpg_float    *y_5;       // Delta of your parameter y_5
  cpg_float    *A_6;       // Delta of your parameter A_6
  cpg_float    *B_6;       // Delta of your parameter B_6
  cpg_float    *y_6;       // Delta of your parameter y_6
  cpg_float    *A_7;       // Delta of your parameter A_7
  cpg_float    *B_7;       // Delta of your parameter B_7
  cpg_float    *y_7;       // Delta of your parameter y_7
  cpg_float    *A_8;       // Delta of your parameter A_8
  cpg_float    *B_8;       // Delta of your parameter B_8
  cpg_float    *y_8;       // Delta of your parameter y_8
  cpg_float    *A_9;       // Delta of your parameter A_9
  cpg_float    *B_9;       // Delta of your parameter B_9
  cpg_float    *y_9;       // Delta of your parameter y_9
  cpg_float    *A_10;      // Delta of your parameter A_10
  cpg_float    *B_10;      // Delta of your parameter B_10
  cpg_float    *y_10;      // Delta of your parameter y_10
  cpg_float    *A_11;      // Delta of your parameter A_11
  cpg_float    *B_11;      // Delta of your parameter B_11
  cpg_float    *y_11;      // Delta of your parameter y_11
  cpg_float    *A_12;      // Delta of your parameter A_12
  cpg_float    *B_12;      // Delta of your parameter B_12
  cpg_float    *y_12;      // Delta of your parameter y_12
  cpg_float    *A_13;      // Delta of your parameter A_13
  cpg_float    *B_13;      // Delta of your parameter B_13
  cpg_float    *y_13;      // Delta of your parameter y_13
  cpg_float    *A_14;      // Delta of your parameter A_14
  cpg_float    *B_14;      // Delta of your parameter B_14
  cpg_float    *y_14;      // Delta of your parameter y_14
  cpg_float    *A_15;      // Delta of your parameter A_15
  cpg_float    *B_15;      // Delta of your parameter B_15
  cpg_float    *y_15;      // Delta of your parameter y_15
  cpg_float    *A_16;      // Delta of your parameter A_16
  cpg_float    *B_16;      // Delta of your parameter B_16
  cpg_float    *y_16;      // Delta of your parameter y_16
  cpg_float    *A_17;      // Delta of your parameter A_17
  cpg_float    *B_17;      // Delta of your parameter B_17
  cpg_float    *y_17;      // Delta of your parameter y_17
  cpg_float    *A_18;      // Delta of your parameter A_18
  cpg_float    *B_18;      // Delta of your parameter B_18
  cpg_float    *y_18;      // Delta of your parameter y_18
  cpg_float    *A_19;      // Delta of your parameter A_19
  cpg_float    *B_19;      // Delta of your parameter B_19
  cpg_float    *y_19;      // Delta of your parameter y_19
  cpg_float    *A_20;      // Delta of your parameter A_20
  cpg_float    *B_20;      // Delta of your parameter B_20
  cpg_float    *y_20;      // Delta of your parameter y_20
  cpg_float    *A_21;      // Delta of your parameter A_21
  cpg_float    *B_21;      // Delta of your parameter B_21
  cpg_float    *y_21;      // Delta of your parameter y_21
  cpg_float    *A_22;      // Delta of your parameter A_22
  cpg_float    *B_22;      // Delta of your parameter B_22
  cpg_float    *y_22;      // Delta of your parameter y_22
  cpg_float    *A_23;      // Delta of your parameter A_23
  cpg_float    *B_23;      // Delta of your parameter B_23
  cpg_float    *y_23;      // Delta of your parameter y_23
  cpg_float    *A_24;      // Delta of your parameter A_24
  cpg_float    *B_24;      // Delta of your parameter B_24
  cpg_float    *y_24;      // Delta of your parameter y_24
  cpg_float    *A_25;      // Delta of your parameter A_25
  cpg_float    *B_25;      // Delta of your parameter B_25
  cpg_float    *y_25;      // Delta of your parameter y_25
  cpg_float    *A_26;      // Delta of your parameter A_26
  cpg_float    *B_26;      // Delta of your parameter B_26
  cpg_float    *y_26;      // Delta of your parameter y_26
  cpg_float    *A_27;      // Delta of your parameter A_27
  cpg_float    *B_27;      // Delta of your parameter B_27
  cpg_float    *y_27;      // Delta of your parameter y_27
  cpg_float    *A_28;      // Delta of your parameter A_28
  cpg_float    *B_28;      // Delta of your parameter B_28
  cpg_float    *y_28;      // Delta of your parameter y_28
  cpg_float    *A_29;      // Delta of your parameter A_29
  cpg_float    *B_29;      // Delta of your parameter B_29
  cpg_float    *y_29;      // Delta of your parameter y_29
  cpg_float    *ox_0;      // Delta of your parameter ox_0
  cpg_float    *ou_0;      // Delta of your parameter ou_0
  cpg_float    *etta;      // Delta of your parameter etta
  cpg_float    *ox_1;      // Delta of your parameter ox_1
  cpg_float    *ou_1;      // Delta of your parameter ou_1
  cpg_float    *ox_2;      // Delta of your parameter ox_2
  cpg_float    *ou_2;      // Delta of your parameter ou_2
  cpg_float    *ox_3;      // Delta of your parameter ox_3
  cpg_float    *ou_3;      // Delta of your parameter ou_3
  cpg_float    *ox_4;      // Delta of your parameter ox_4
  cpg_float    *ou_4;      // Delta of your parameter ou_4
  cpg_float    *ox_5;      // Delta of your parameter ox_5
  cpg_float    *ou_5;      // Delta of your parameter ou_5
  cpg_float    *ox_6;      // Delta of your parameter ox_6
  cpg_float    *ou_6;      // Delta of your parameter ou_6
  cpg_float    *ox_7;      // Delta of your parameter ox_7
  cpg_float    *ou_7;      // Delta of your parameter ou_7
  cpg_float    *ox_8;      // Delta of your parameter ox_8
  cpg_float    *ou_8;      // Delta of your parameter ou_8
  cpg_float    *ox_9;      // Delta of your parameter ox_9
  cpg_float    *ou_9;      // Delta of your parameter ou_9
  cpg_float    *ox_10;     // Delta of your parameter ox_10
  cpg_float    *ou_10;     // Delta of your parameter ou_10
  cpg_float    *ox_11;     // Delta of your parameter ox_11
  cpg_float    *ou_11;     // Delta of your parameter ou_11
  cpg_float    *ox_12;     // Delta of your parameter ox_12
  cpg_float    *ou_12;     // Delta of your parameter ou_12
  cpg_float    *ox_13;     // Delta of your parameter ox_13
  cpg_float    *ou_13;     // Delta of your parameter ou_13
  cpg_float    *ox_14;     // Delta of your parameter ox_14
  cpg_float    *ou_14;     // Delta of your parameter ou_14
  cpg_float    *ox_15;     // Delta of your parameter ox_15
  cpg_float    *ou_15;     // Delta of your parameter ou_15
  cpg_float    *ox_16;     // Delta of your parameter ox_16
  cpg_float    *ou_16;     // Delta of your parameter ou_16
  cpg_float    *ox_17;     // Delta of your parameter ox_17
  cpg_float    *ou_17;     // Delta of your parameter ou_17
  cpg_float    *ox_18;     // Delta of your parameter ox_18
  cpg_float    *ou_18;     // Delta of your parameter ou_18
  cpg_float    *ox_19;     // Delta of your parameter ox_19
  cpg_float    *ou_19;     // Delta of your parameter ou_19
  cpg_float    *ox_20;     // Delta of your parameter ox_20
  cpg_float    *ou_20;     // Delta of your parameter ou_20
  cpg_float    *ox_21;     // Delta of your parameter ox_21
  cpg_float    *ou_21;     // Delta of your parameter ou_21
  cpg_float    *ox_22;     // Delta of your parameter ox_22
  cpg_float    *ou_22;     // Delta of your parameter ou_22
  cpg_float    *ox_23;     // Delta of your parameter ox_23
  cpg_float    *ou_23;     // Delta of your parameter ou_23
  cpg_float    *ox_24;     // Delta of your parameter ox_24
  cpg_float    *ou_24;     // Delta of your parameter ou_24
  cpg_float    *ox_25;     // Delta of your parameter ox_25
  cpg_float    *ou_25;     // Delta of your parameter ou_25
  cpg_float    *ox_26;     // Delta of your parameter ox_26
  cpg_float    *ou_26;     // Delta of your parameter ou_26
  cpg_float    *ox_27;     // Delta of your parameter ox_27
  cpg_float    *ou_27;     // Delta of your parameter ou_27
  cpg_float    *ox_28;     // Delta of your parameter ox_28
  cpg_float    *ou_28;     // Delta of your parameter ou_28
  cpg_float    *ox_29;     // Delta of your parameter ox_29
  cpg_float    *ou_29;     // Delta of your parameter ou_29
  cpg_float    *ox_30;     // Delta of your parameter ox_30
  cpg_float    *C_0;       // Delta of your parameter C_0
  cpg_float    *D_0;       // Delta of your parameter D_0
  cpg_float    *z_0;       // Delta of your parameter z_0
  cpg_float    *C_1;       // Delta of your parameter C_1
  cpg_float    *D_1;       // Delta of your parameter D_1
  cpg_float    *z_1;       // Delta of your parameter z_1
  cpg_float    *C_2;       // Delta of your parameter C_2
  cpg_float    *D_2;       // Delta of your parameter D_2
  cpg_float    *z_2;       // Delta of your parameter z_2
  cpg_float    *C_3;       // Delta of your parameter C_3
  cpg_float    *D_3;       // Delta of your parameter D_3
  cpg_float    *z_3;       // Delta of your parameter z_3
  cpg_float    *C_4;       // Delta of your parameter C_4
  cpg_float    *D_4;       // Delta of your parameter D_4
  cpg_float    *z_4;       // Delta of your parameter z_4
  cpg_float    *C_5;       // Delta of your parameter C_5
  cpg_float    *D_5;       // Delta of your parameter D_5
  cpg_float    *z_5;       // Delta of your parameter z_5
  cpg_float    *C_6;       // Delta of your parameter C_6
  cpg_float    *D_6;       // Delta of your parameter D_6
  cpg_float    *z_6;       // Delta of your parameter z_6
  cpg_float    *C_7;       // Delta of your parameter C_7
  cpg_float    *D_7;       // Delta of your parameter D_7
  cpg_float    *z_7;       // Delta of your parameter z_7
  cpg_float    *C_8;       // Delta of your parameter C_8
  cpg_float    *D_8;       // Delta of your parameter D_8
  cpg_float    *z_8;       // Delta of your parameter z_8
  cpg_float    *C_9;       // Delta of your parameter C_9
  cpg_float    *D_9;       // Delta of your parameter D_9
  cpg_float    *z_9;       // Delta of your parameter z_9
  cpg_float    *C_10;      // Delta of your parameter C_10
  cpg_float    *D_10;      // Delta of your parameter D_10
  cpg_float    *z_10;      // Delta of your parameter z_10
  cpg_float    *C_11;      // Delta of your parameter C_11
  cpg_float    *D_11;      // Delta of your parameter D_11
  cpg_float    *z_11;      // Delta of your parameter z_11
  cpg_float    *C_12;      // Delta of your parameter C_12
  cpg_float    *D_12;      // Delta of your parameter D_12
  cpg_float    *z_12;      // Delta of your parameter z_12
  cpg_float    *C_13;      // Delta of your parameter C_13
  cpg_float    *D_13;      // Delta of your parameter D_13
  cpg_float    *z_13;      // Delta of your parameter z_13
  cpg_float    *C_14;      // Delta of your parameter C_14
  cpg_float    *D_14;      // Delta of your parameter D_14
  cpg_float    *z_14;      // Delta of your parameter z_14
  cpg_float    *C_15;      // Delta of your parameter C_15
  cpg_float    *D_15;      // Delta of your parameter D_15
  cpg_float    *z_15;      // Delta of your parameter z_15
  cpg_float    *C_16;      // Delta of your parameter C_16
  cpg_float    *D_16;      // Delta of your parameter D_16
  cpg_float    *z_16;      // Delta of your parameter z_16
  cpg_float    *C_17;      // Delta of your parameter C_17
  cpg_float    *D_17;      // Delta of your parameter D_17
  cpg_float    *z_17;      // Delta of your parameter z_17
  cpg_float    *C_18;      // Delta of your parameter C_18
  cpg_float    *D_18;      // Delta of your parameter D_18
  cpg_float    *z_18;      // Delta of your parameter z_18
  cpg_float    *C_19;      // Delta of your parameter C_19
  cpg_float    *D_19;      // Delta of your parameter D_19
  cpg_float    *z_19;      // Delta of your parameter z_19
  cpg_float    *C_20;      // Delta of your parameter C_20
  cpg_float    *D_20;      // Delta of your parameter D_20
  cpg_float    *z_20;      // Delta of your parameter z_20
  cpg_float    *C_21;      // Delta of your parameter C_21
  cpg_float    *D_21;      // Delta of your parameter D_21
  cpg_float    *z_21;      // Delta of your parameter z_21
  cpg_float    *C_22;      // Delta of your parameter C_22
  cpg_float    *D_22;      // Delta of your parameter D_22
  cpg_float    *z_22;      // Delta of your parameter z_22
  cpg_float    *C_23;      // Delta of your parameter C_23
  cpg_float    *D_23;      // Delta of your parameter D_23
  cpg_float    *z_23;      // Delta of your parameter z_23
  cpg_float    *C_24;      // Delta of your parameter C_24
  cpg_float    *D_24;      // Delta of your parameter D_24
  cpg_float    *z_24;      // Delta of your parameter z_24
  cpg_float    *C_25;      // Delta of your parameter C_25
  cpg_float    *D_25;      // Delta of your parameter D_25
  cpg_float    *z_25;      // Delta of your parameter z_25
  cpg_float    *C_26;      // Delta of your parameter C_26
  cpg_float    *D_26;      // Delta of your parameter D_26
  cpg_float    *z_26;      // Delta of your parameter z_26
  cpg_float    *C_27;      // Delta of your parameter C_27
  cpg_float    *D_27;      // Delta of your parameter D_27
  cpg_float    *z_27;      // Delta of your parameter z_27
  cpg_float    *C_28;      // Delta of your parameter C_28
  cpg_float    *D_28;      // Delta of your parameter D_28
  cpg_float    *z_28;      // Delta of your parameter z_28
  cpg_float    *C_29;      // Delta of your parameter C_29
  cpg_float    *D_29;      // Delta of your parameter D_29
  cpg_float    *z_29;      // Delta of your parameter z_29
  cpg_float    *C_30;      // Delta of your parameter C_30
  cpg_float    *D_30;      // Delta of your parameter D_30
  cpg_float    *z_30;      // Delta of your parameter z_30
} CPG_Delta_t;

// Solver settings
typedef struct {
  cpg_float  feastol;
  cpg_float  abstol;
  cpg_float  reltol;
  cpg_float  feastol_inacc;
  cpg_float  abstol_inacc;
  cpg_float  reltol_inacc;
  cpg_int    maxit;
} Canon_Settings_t;

#endif // ifndef CPG_TYPES_H

// Vector containing flattened user-defined parameters
extern cpg_float cpg_params_vec[10271];

// Sparse mappings from user-defined to canonical parameters
extern cpg_csc canon_A_map;
extern cpg_csc canon_b_map;
extern cpg_csc canon_G_map;
extern cpg_csc canon_h_map;

// Canonical parameters
extern cpg_float canon_c[2593];
extern cpg_float canon_c_conditioning[2593];
extern cpg_csc canon_A;
extern cpg_csc canon_A_conditioning;
extern cpg_float canon_b[416];
extern cpg_float canon_b_conditioning[416];
extern cpg_csc canon_G;
extern cpg_csc canon_G_conditioning;
extern cpg_float canon_h[3948];
extern cpg_float canon_h_conditioning[3948];

// Struct containing canonical parameters
extern Canon_Params_t Canon_Params;
extern Canon_Params_t Canon_Params_conditioning;

// Struct containing flags for outdated canonical parameters
extern Canon_Outdated_t Canon_Outdated;

// User-defined variables
extern cpg_float cpg_u[180];
extern cpg_float cpg_vc[390];
extern cpg_float cpg_vi[93];
extern cpg_float cpg_x[403];

// Dual variables associated with user-defined constraints
extern cpg_float cpg_d0[13];
extern cpg_float cpg_d1[13];
extern cpg_float cpg_d2[13];
extern cpg_float cpg_d3[13];
extern cpg_float cpg_d4[13];
extern cpg_float cpg_d5[13];
extern cpg_float cpg_d6[13];
extern cpg_float cpg_d7[13];
extern cpg_float cpg_d8[13];
extern cpg_float cpg_d9[13];
extern cpg_float cpg_d10[13];
extern cpg_float cpg_d11[13];
extern cpg_float cpg_d12[13];
extern cpg_float cpg_d13[13];
extern cpg_float cpg_d14[13];
extern cpg_float cpg_d15[13];
extern cpg_float cpg_d16[13];
extern cpg_float cpg_d17[13];
extern cpg_float cpg_d18[13];
extern cpg_float cpg_d19[13];
extern cpg_float cpg_d20[13];
extern cpg_float cpg_d21[13];
extern cpg_float cpg_d22[13];
extern cpg_float cpg_d23[13];
extern cpg_float cpg_d24[13];
extern cpg_float cpg_d25[13];
extern cpg_float cpg_d26[13];
extern cpg_float cpg_d27[13];
extern cpg_float cpg_d28[13];
extern cpg_float cpg_d29[13];
extern cpg_float cpg_d30[13];
extern cpg_float cpg_d31[13];
extern cpg_float cpg_d63[3];
extern cpg_float cpg_d64[3];
extern cpg_float cpg_d65[3];
extern cpg_float cpg_d66[3];
extern cpg_float cpg_d67[3];
extern cpg_float cpg_d68[3];
extern cpg_float cpg_d69[3];
extern cpg_float cpg_d70[3];
extern cpg_float cpg_d71[3];
extern cpg_float cpg_d72[3];
extern cpg_float cpg_d73[3];
extern cpg_float cpg_d74[3];
extern cpg_float cpg_d75[3];
extern cpg_float cpg_d76[3];
extern cpg_float cpg_d77[3];
extern cpg_float cpg_d78[3];
extern cpg_float cpg_d79[3];
extern cpg_float cpg_d80[3];
extern cpg_float cpg_d81[3];
extern cpg_float cpg_d82[3];
extern cpg_float cpg_d83[3];
extern cpg_float cpg_d84[3];
extern cpg_float cpg_d85[3];
extern cpg_float cpg_d86[3];
extern cpg_float cpg_d87[3];
extern cpg_float cpg_d88[3];
extern cpg_float cpg_d89[3];
extern cpg_float cpg_d90[3];
extern cpg_float cpg_d91[3];
extern cpg_float cpg_d92[3];
extern cpg_float cpg_d93[3];

// Struct containing primal solution
extern CPG_Prim_t CPG_Prim;

// Struct containing dual solution
extern CPG_Dual_t CPG_Dual;

// Struct containing solver info
extern CPG_Info_t CPG_Info;

// Struct containing solution and info
extern CPG_Result_t CPG_Result;

// Struct containing solver settings
extern Canon_Settings_t Canon_Settings;

// ECOS array of SOC dimensions
extern cpg_int ecos_q[92];

// ECOS workspace
extern pwork* ecos_workspace;

// ECOS exit flag
extern cpg_int ecos_flag;
