
/*
Auto-generated by CVXPYgen on August 22, 2026 at 15:05:10
Content: Example program for updating parameters, solving, and inspecting the result
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_start_pos(0, 1.00000000000000000000);
  cpg_update_end_pos(0, 1.00000000000000000000);
  cpg_update_A_0(0, 1.00000000000000000000);
  cpg_update_B_0(0, 1.00000000000000000000);
  cpg_update_y_0(0, 1.00000000000000000000);
  cpg_update_A_1(0, 1.00000000000000000000);
  cpg_update_B_1(0, 1.00000000000000000000);
  cpg_update_y_1(0, 1.00000000000000000000);
  cpg_update_A_2(0, 1.00000000000000000000);
  cpg_update_B_2(0, 1.00000000000000000000);
  cpg_update_y_2(0, 1.00000000000000000000);
  cpg_update_A_3(0, 1.00000000000000000000);
  cpg_update_B_3(0, 1.00000000000000000000);
  cpg_update_y_3(0, 1.00000000000000000000);
  cpg_update_A_4(0, 1.00000000000000000000);
  cpg_update_B_4(0, 1.00000000000000000000);
  cpg_update_y_4(0, 1.00000000000000000000);
  cpg_update_A_5(0, 1.00000000000000000000);
  cpg_update_B_5(0, 1.00000000000000000000);
  cpg_update_y_5(0, 1.00000000000000000000);
  cpg_update_A_6(0, 1.00000000000000000000);
  cpg_update_B_6(0, 1.00000000000000000000);
  cpg_update_y_6(0, 1.00000000000000000000);
  cpg_update_A_7(0, 1.00000000000000000000);
  cpg_update_B_7(0, 1.00000000000000000000);
  cpg_update_y_7(0, 1.00000000000000000000);
  cpg_update_A_8(0, 1.00000000000000000000);
  cpg_update_B_8(0, 1.00000000000000000000);
  cpg_update_y_8(0, 1.00000000000000000000);
  cpg_update_A_9(0, 1.00000000000000000000);
  cpg_update_B_9(0, 1.00000000000000000000);
  cpg_update_y_9(0, 1.00000000000000000000);
  cpg_update_A_10(0, 1.00000000000000000000);
  cpg_update_B_10(0, 1.00000000000000000000);
  cpg_update_y_10(0, 1.00000000000000000000);
  cpg_update_A_11(0, 1.00000000000000000000);
  cpg_update_B_11(0, 1.00000000000000000000);
  cpg_update_y_11(0, 1.00000000000000000000);
  cpg_update_A_12(0, 1.00000000000000000000);
  cpg_update_B_12(0, 1.00000000000000000000);
  cpg_update_y_12(0, 1.00000000000000000000);
  cpg_update_A_13(0, 1.00000000000000000000);
  cpg_update_B_13(0, 1.00000000000000000000);
  cpg_update_y_13(0, 1.00000000000000000000);
  cpg_update_A_14(0, 1.00000000000000000000);
  cpg_update_B_14(0, 1.00000000000000000000);
  cpg_update_y_14(0, 1.00000000000000000000);
  cpg_update_A_15(0, 1.00000000000000000000);
  cpg_update_B_15(0, 1.00000000000000000000);
  cpg_update_y_15(0, 1.00000000000000000000);
  cpg_update_A_16(0, 1.00000000000000000000);
  cpg_update_B_16(0, 1.00000000000000000000);
  cpg_update_y_16(0, 1.00000000000000000000);
  cpg_update_A_17(0, 1.00000000000000000000);
  cpg_update_B_17(0, 1.00000000000000000000);
  cpg_update_y_17(0, 1.00000000000000000000);
  cpg_update_A_18(0, 1.00000000000000000000);
  cpg_update_B_18(0, 1.00000000000000000000);
  cpg_update_y_18(0, 1.00000000000000000000);
  cpg_update_A_19(0, 1.00000000000000000000);
  cpg_update_B_19(0, 1.00000000000000000000);
  cpg_update_y_19(0, 1.00000000000000000000);
  cpg_update_A_20(0, 1.00000000000000000000);
  cpg_update_B_20(0, 1.00000000000000000000);
  cpg_update_y_20(0, 1.00000000000000000000);
  cpg_update_A_21(0, 1.00000000000000000000);
  cpg_update_B_21(0, 1.00000000000000000000);
  cpg_update_y_21(0, 1.00000000000000000000);
  cpg_update_A_22(0, 1.00000000000000000000);
  cpg_update_B_22(0, 1.00000000000000000000);
  cpg_update_y_22(0, 1.00000000000000000000);
  cpg_update_A_23(0, 1.00000000000000000000);
  cpg_update_B_23(0, 1.00000000000000000000);
  cpg_update_y_23(0, 1.00000000000000000000);
  cpg_update_A_24(0, 1.00000000000000000000);
  cpg_update_B_24(0, 1.00000000000000000000);
  cpg_update_y_24(0, 1.00000000000000000000);
  cpg_update_A_25(0, 1.00000000000000000000);
  cpg_update_B_25(0, 1.00000000000000000000);
  cpg_update_y_25(0, 1.00000000000000000000);
  cpg_update_A_26(0, 1.00000000000000000000);
  cpg_update_B_26(0, 1.00000000000000000000);
  cpg_update_y_26(0, 1.00000000000000000000);
  cpg_update_A_27(0, 1.00000000000000000000);
  cpg_update_B_27(0, 1.00000000000000000000);
  cpg_update_y_27(0, 1.00000000000000000000);
  cpg_update_A_28(0, 1.00000000000000000000);
  cpg_update_B_28(0, 1.00000000000000000000);
  cpg_update_y_28(0, 1.00000000000000000000);
  cpg_update_A_29(0, 1.00000000000000000000);
  cpg_update_B_29(0, 1.00000000000000000000);
  cpg_update_y_29(0, 1.00000000000000000000);
  cpg_update_ox_0(0, 1.00000000000000000000);
  cpg_update_ou_0(0, 1.00000000000000000000);
  cpg_update_etta(1.00000000000000000000);
  cpg_update_ox_1(0, 1.00000000000000000000);
  cpg_update_ou_1(0, 1.00000000000000000000);
  cpg_update_ox_2(0, 1.00000000000000000000);
  cpg_update_ou_2(0, 1.00000000000000000000);
  cpg_update_ox_3(0, 1.00000000000000000000);
  cpg_update_ou_3(0, 1.00000000000000000000);
  cpg_update_ox_4(0, 1.00000000000000000000);
  cpg_update_ou_4(0, 1.00000000000000000000);
  cpg_update_ox_5(0, 1.00000000000000000000);
  cpg_update_ou_5(0, 1.00000000000000000000);
  cpg_update_ox_6(0, 1.00000000000000000000);
  cpg_update_ou_6(0, 1.00000000000000000000);
  cpg_update_ox_7(0, 1.00000000000000000000);
  cpg_update_ou_7(0, 1.00000000000000000000);
  cpg_update_ox_8(0, 1.00000000000000000000);
  cpg_update_ou_8(0, 1.00000000000000000000);
  cpg_update_ox_9(0, 1.00000000000000000000);
  cpg_update_ou_9(0, 1.00000000000000000000);
  cpg_update_ox_10(0, 1.00000000000000000000);
  cpg_update_ou_10(0, 1.00000000000000000000);
  cpg_update_ox_11(0, 1.00000000000000000000);
  cpg_update_ou_11(0, 1.00000000000000000000);
  cpg_update_ox_12(0, 1.00000000000000000000);
  cpg_update_ou_12(0, 1.00000000000000000000);
  cpg_update_ox_13(0, 1.00000000000000000000);
  cpg_update_ou_13(0, 1.00000000000000000000);
  cpg_update_ox_14(0, 1.00000000000000000000);
  cpg_update_ou_14(0, 1.00000000000000000000);
  cpg_update_ox_15(0, 1.00000000000000000000);
  cpg_update_ou_15(0, 1.00000000000000000000);
  cpg_update_ox_16(0, 1.00000000000000000000);
  cpg_update_ou_16(0, 1.00000000000000000000);
  cpg_update_ox_17(0, 1.00000000000000000000);
  cpg_update_ou_17(0, 1.00000000000000000000);
  cpg_update_ox_18(0, 1.00000000000000000000);
  cpg_update_ou_18(0, 1.00000000000000000000);
  cpg_update_ox_19(0, 1.00000000000000000000);
  cpg_update_ou_19(0, 1.00000000000000000000);
  cpg_update_ox_20(0, 1.00000000000000000000);
  cpg_update_ou_20(0, 1.00000000000000000000);
  cpg_update_ox_21(0, 1.00000000000000000000);
  cpg_update_ou_21(0, 1.00000000000000000000);
  cpg_update_ox_22(0, 1.00000000000000000000);
  cpg_update_ou_22(0, 1.00000000000000000000);
  cpg_update_ox_23(0, 1.00000000000000000000);
  cpg_update_ou_23(0, 1.00000000000000000000);
  cpg_update_ox_24(0, 1.00000000000000000000);
  cpg_update_ou_24(0, 1.00000000000000000000);
  cpg_update_ox_25(0, 1.00000000000000000000);
  cpg_update_ou_25(0, 1.00000000000000000000);
  cpg_update_ox_26(0, 1.00000000000000000000);
  cpg_update_ou_26(0, 1.00000000000000000000);
  cpg_update_ox_27(0, 1.00000000000000000000);
  cpg_update_ou_27(0, 1.00000000000000000000);
  cpg_update_ox_28(0, 1.00000000000000000000);
  cpg_update_ou_28(0, 1.00000000000000000000);
  cpg_update_ox_29(0, 1.00000000000000000000);
  cpg_update_ou_29(0, 1.00000000000000000000);
  cpg_update_ox_30(0, 1.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<120; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<210; i++) {
    printf("vc[%d] = %f\n", i, CPG_Result.prim->vc[i]);
  }
  for(i=0; i<217; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<7; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<7; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<7; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<7; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<7; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<7; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<7; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<7; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<7; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<7; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<7; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<7; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<7; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<7; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<7; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<7; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<7; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<7; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<7; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<7; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<7; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<7; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<7; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<7; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<7; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<7; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<7; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<7; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  printf("d32 = %f\n", CPG_Result.dual->d32);
  printf("d33 = %f\n", CPG_Result.dual->d33);
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  printf("d63 = %f\n", CPG_Result.dual->d63);
  printf("d64 = %f\n", CPG_Result.dual->d64);
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  printf("d73 = %f\n", CPG_Result.dual->d73);
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  printf("d77 = %f\n", CPG_Result.dual->d77);
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  printf("d86 = %f\n", CPG_Result.dual->d86);
  printf("d87 = %f\n", CPG_Result.dual->d87);
  printf("d88 = %f\n", CPG_Result.dual->d88);
  printf("d89 = %f\n", CPG_Result.dual->d89);
  printf("d90 = %f\n", CPG_Result.dual->d90);
  printf("d91 = %f\n", CPG_Result.dual->d91);
  printf("d92 = %f\n", CPG_Result.dual->d92);
  printf("d93 = %f\n", CPG_Result.dual->d93);
  for(i=0; i<4; i++) {
    printf("d94[%d] = %f\n", i, CPG_Result.dual->d94[i]);
  }
  for(i=0; i<4; i++) {
    printf("d95[%d] = %f\n", i, CPG_Result.dual->d95[i]);
  }
  for(i=0; i<4; i++) {
    printf("d96[%d] = %f\n", i, CPG_Result.dual->d96[i]);
  }
  for(i=0; i<4; i++) {
    printf("d97[%d] = %f\n", i, CPG_Result.dual->d97[i]);
  }
  for(i=0; i<4; i++) {
    printf("d98[%d] = %f\n", i, CPG_Result.dual->d98[i]);
  }
  for(i=0; i<4; i++) {
    printf("d99[%d] = %f\n", i, CPG_Result.dual->d99[i]);
  }
  for(i=0; i<4; i++) {
    printf("d100[%d] = %f\n", i, CPG_Result.dual->d100[i]);
  }
  for(i=0; i<4; i++) {
    printf("d101[%d] = %f\n", i, CPG_Result.dual->d101[i]);
  }
  for(i=0; i<4; i++) {
    printf("d102[%d] = %f\n", i, CPG_Result.dual->d102[i]);
  }
  for(i=0; i<4; i++) {
    printf("d103[%d] = %f\n", i, CPG_Result.dual->d103[i]);
  }
  for(i=0; i<4; i++) {
    printf("d104[%d] = %f\n", i, CPG_Result.dual->d104[i]);
  }
  for(i=0; i<4; i++) {
    printf("d105[%d] = %f\n", i, CPG_Result.dual->d105[i]);
  }
  for(i=0; i<4; i++) {
    printf("d106[%d] = %f\n", i, CPG_Result.dual->d106[i]);
  }
  for(i=0; i<4; i++) {
    printf("d107[%d] = %f\n", i, CPG_Result.dual->d107[i]);
  }
  for(i=0; i<4; i++) {
    printf("d108[%d] = %f\n", i, CPG_Result.dual->d108[i]);
  }
  for(i=0; i<4; i++) {
    printf("d109[%d] = %f\n", i, CPG_Result.dual->d109[i]);
  }
  for(i=0; i<4; i++) {
    printf("d110[%d] = %f\n", i, CPG_Result.dual->d110[i]);
  }
  for(i=0; i<4; i++) {
    printf("d111[%d] = %f\n", i, CPG_Result.dual->d111[i]);
  }
  for(i=0; i<4; i++) {
    printf("d112[%d] = %f\n", i, CPG_Result.dual->d112[i]);
  }
  for(i=0; i<4; i++) {
    printf("d113[%d] = %f\n", i, CPG_Result.dual->d113[i]);
  }
  for(i=0; i<4; i++) {
    printf("d114[%d] = %f\n", i, CPG_Result.dual->d114[i]);
  }
  for(i=0; i<4; i++) {
    printf("d115[%d] = %f\n", i, CPG_Result.dual->d115[i]);
  }
  for(i=0; i<4; i++) {
    printf("d116[%d] = %f\n", i, CPG_Result.dual->d116[i]);
  }
  for(i=0; i<4; i++) {
    printf("d117[%d] = %f\n", i, CPG_Result.dual->d117[i]);
  }
  for(i=0; i<4; i++) {
    printf("d118[%d] = %f\n", i, CPG_Result.dual->d118[i]);
  }
  for(i=0; i<4; i++) {
    printf("d119[%d] = %f\n", i, CPG_Result.dual->d119[i]);
  }
  for(i=0; i<4; i++) {
    printf("d120[%d] = %f\n", i, CPG_Result.dual->d120[i]);
  }
  for(i=0; i<4; i++) {
    printf("d121[%d] = %f\n", i, CPG_Result.dual->d121[i]);
  }
  for(i=0; i<4; i++) {
    printf("d122[%d] = %f\n", i, CPG_Result.dual->d122[i]);
  }
  for(i=0; i<4; i++) {
    printf("d123[%d] = %f\n", i, CPG_Result.dual->d123[i]);
  }
  for(i=0; i<4; i++) {
    printf("d124[%d] = %f\n", i, CPG_Result.dual->d124[i]);
  }
  for(i=0; i<4; i++) {
    printf("d125[%d] = %f\n", i, CPG_Result.dual->d125[i]);
  }
  for(i=0; i<4; i++) {
    printf("d126[%d] = %f\n", i, CPG_Result.dual->d126[i]);
  }
  for(i=0; i<4; i++) {
    printf("d127[%d] = %f\n", i, CPG_Result.dual->d127[i]);
  }
  for(i=0; i<4; i++) {
    printf("d128[%d] = %f\n", i, CPG_Result.dual->d128[i]);
  }
  for(i=0; i<4; i++) {
    printf("d129[%d] = %f\n", i, CPG_Result.dual->d129[i]);
  }
  for(i=0; i<4; i++) {
    printf("d130[%d] = %f\n", i, CPG_Result.dual->d130[i]);
  }
  for(i=0; i<4; i++) {
    printf("d131[%d] = %f\n", i, CPG_Result.dual->d131[i]);
  }
  for(i=0; i<4; i++) {
    printf("d132[%d] = %f\n", i, CPG_Result.dual->d132[i]);
  }
  for(i=0; i<4; i++) {
    printf("d133[%d] = %f\n", i, CPG_Result.dual->d133[i]);
  }
  for(i=0; i<4; i++) {
    printf("d134[%d] = %f\n", i, CPG_Result.dual->d134[i]);
  }
  for(i=0; i<4; i++) {
    printf("d135[%d] = %f\n", i, CPG_Result.dual->d135[i]);
  }
  for(i=0; i<4; i++) {
    printf("d136[%d] = %f\n", i, CPG_Result.dual->d136[i]);
  }
  for(i=0; i<4; i++) {
    printf("d137[%d] = %f\n", i, CPG_Result.dual->d137[i]);
  }
  for(i=0; i<4; i++) {
    printf("d138[%d] = %f\n", i, CPG_Result.dual->d138[i]);
  }
  for(i=0; i<4; i++) {
    printf("d139[%d] = %f\n", i, CPG_Result.dual->d139[i]);
  }
  for(i=0; i<4; i++) {
    printf("d140[%d] = %f\n", i, CPG_Result.dual->d140[i]);
  }
  for(i=0; i<4; i++) {
    printf("d141[%d] = %f\n", i, CPG_Result.dual->d141[i]);
  }
  for(i=0; i<4; i++) {
    printf("d142[%d] = %f\n", i, CPG_Result.dual->d142[i]);
  }
  for(i=0; i<4; i++) {
    printf("d143[%d] = %f\n", i, CPG_Result.dual->d143[i]);
  }
  for(i=0; i<4; i++) {
    printf("d144[%d] = %f\n", i, CPG_Result.dual->d144[i]);
  }
  for(i=0; i<4; i++) {
    printf("d145[%d] = %f\n", i, CPG_Result.dual->d145[i]);
  }
  for(i=0; i<4; i++) {
    printf("d146[%d] = %f\n", i, CPG_Result.dual->d146[i]);
  }
  for(i=0; i<4; i++) {
    printf("d147[%d] = %f\n", i, CPG_Result.dual->d147[i]);
  }
  for(i=0; i<4; i++) {
    printf("d148[%d] = %f\n", i, CPG_Result.dual->d148[i]);
  }
  for(i=0; i<4; i++) {
    printf("d149[%d] = %f\n", i, CPG_Result.dual->d149[i]);
  }
  for(i=0; i<4; i++) {
    printf("d150[%d] = %f\n", i, CPG_Result.dual->d150[i]);
  }
  for(i=0; i<4; i++) {
    printf("d151[%d] = %f\n", i, CPG_Result.dual->d151[i]);
  }
  for(i=0; i<4; i++) {
    printf("d152[%d] = %f\n", i, CPG_Result.dual->d152[i]);
  }
  for(i=0; i<4; i++) {
    printf("d153[%d] = %f\n", i, CPG_Result.dual->d153[i]);
  }
  for(i=0; i<4; i++) {
    printf("d154[%d] = %f\n", i, CPG_Result.dual->d154[i]);
  }
  for(i=0; i<4; i++) {
    printf("d155[%d] = %f\n", i, CPG_Result.dual->d155[i]);
  }
  for(i=0; i<4; i++) {
    printf("d156[%d] = %f\n", i, CPG_Result.dual->d156[i]);
  }
  for(i=0; i<4; i++) {
    printf("d157[%d] = %f\n", i, CPG_Result.dual->d157[i]);
  }
  for(i=0; i<4; i++) {
    printf("d158[%d] = %f\n", i, CPG_Result.dual->d158[i]);
  }
  for(i=0; i<4; i++) {
    printf("d159[%d] = %f\n", i, CPG_Result.dual->d159[i]);
  }
  for(i=0; i<4; i++) {
    printf("d160[%d] = %f\n", i, CPG_Result.dual->d160[i]);
  }
  for(i=0; i<4; i++) {
    printf("d161[%d] = %f\n", i, CPG_Result.dual->d161[i]);
  }
  for(i=0; i<4; i++) {
    printf("d162[%d] = %f\n", i, CPG_Result.dual->d162[i]);
  }
  for(i=0; i<4; i++) {
    printf("d163[%d] = %f\n", i, CPG_Result.dual->d163[i]);
  }
  for(i=0; i<4; i++) {
    printf("d164[%d] = %f\n", i, CPG_Result.dual->d164[i]);
  }
  for(i=0; i<4; i++) {
    printf("d165[%d] = %f\n", i, CPG_Result.dual->d165[i]);
  }
  for(i=0; i<4; i++) {
    printf("d166[%d] = %f\n", i, CPG_Result.dual->d166[i]);
  }
  for(i=0; i<4; i++) {
    printf("d167[%d] = %f\n", i, CPG_Result.dual->d167[i]);
  }
  for(i=0; i<4; i++) {
    printf("d168[%d] = %f\n", i, CPG_Result.dual->d168[i]);
  }
  for(i=0; i<4; i++) {
    printf("d169[%d] = %f\n", i, CPG_Result.dual->d169[i]);
  }
  for(i=0; i<4; i++) {
    printf("d170[%d] = %f\n", i, CPG_Result.dual->d170[i]);
  }
  for(i=0; i<4; i++) {
    printf("d171[%d] = %f\n", i, CPG_Result.dual->d171[i]);
  }
  for(i=0; i<4; i++) {
    printf("d172[%d] = %f\n", i, CPG_Result.dual->d172[i]);
  }
  for(i=0; i<4; i++) {
    printf("d173[%d] = %f\n", i, CPG_Result.dual->d173[i]);
  }
  for(i=0; i<4; i++) {
    printf("d174[%d] = %f\n", i, CPG_Result.dual->d174[i]);
  }
  for(i=0; i<4; i++) {
    printf("d175[%d] = %f\n", i, CPG_Result.dual->d175[i]);
  }
  for(i=0; i<4; i++) {
    printf("d176[%d] = %f\n", i, CPG_Result.dual->d176[i]);
  }
  for(i=0; i<4; i++) {
    printf("d177[%d] = %f\n", i, CPG_Result.dual->d177[i]);
  }
  for(i=0; i<4; i++) {
    printf("d178[%d] = %f\n", i, CPG_Result.dual->d178[i]);
  }
  for(i=0; i<4; i++) {
    printf("d179[%d] = %f\n", i, CPG_Result.dual->d179[i]);
  }
  for(i=0; i<4; i++) {
    printf("d180[%d] = %f\n", i, CPG_Result.dual->d180[i]);
  }
  for(i=0; i<4; i++) {
    printf("d181[%d] = %f\n", i, CPG_Result.dual->d181[i]);
  }
  for(i=0; i<4; i++) {
    printf("d182[%d] = %f\n", i, CPG_Result.dual->d182[i]);
  }
  for(i=0; i<4; i++) {
    printf("d183[%d] = %f\n", i, CPG_Result.dual->d183[i]);
  }
  for(i=0; i<4; i++) {
    printf("d184[%d] = %f\n", i, CPG_Result.dual->d184[i]);
  }
  for(i=0; i<4; i++) {
    printf("d185[%d] = %f\n", i, CPG_Result.dual->d185[i]);
  }
  for(i=0; i<4; i++) {
    printf("d186[%d] = %f\n", i, CPG_Result.dual->d186[i]);
  }
  for(i=0; i<4; i++) {
    printf("d187[%d] = %f\n", i, CPG_Result.dual->d187[i]);
  }
  for(i=0; i<4; i++) {
    printf("d188[%d] = %f\n", i, CPG_Result.dual->d188[i]);
  }
  for(i=0; i<4; i++) {
    printf("d189[%d] = %f\n", i, CPG_Result.dual->d189[i]);
  }
  for(i=0; i<4; i++) {
    printf("d190[%d] = %f\n", i, CPG_Result.dual->d190[i]);
  }
  for(i=0; i<4; i++) {
    printf("d191[%d] = %f\n", i, CPG_Result.dual->d191[i]);
  }
  for(i=0; i<4; i++) {
    printf("d192[%d] = %f\n", i, CPG_Result.dual->d192[i]);
  }
  for(i=0; i<4; i++) {
    printf("d193[%d] = %f\n", i, CPG_Result.dual->d193[i]);
  }
  for(i=0; i<4; i++) {
    printf("d194[%d] = %f\n", i, CPG_Result.dual->d194[i]);
  }
  for(i=0; i<4; i++) {
    printf("d195[%d] = %f\n", i, CPG_Result.dual->d195[i]);
  }
  for(i=0; i<4; i++) {
    printf("d196[%d] = %f\n", i, CPG_Result.dual->d196[i]);
  }
  for(i=0; i<4; i++) {
    printf("d197[%d] = %f\n", i, CPG_Result.dual->d197[i]);
  }
  for(i=0; i<4; i++) {
    printf("d198[%d] = %f\n", i, CPG_Result.dual->d198[i]);
  }
  for(i=0; i<4; i++) {
    printf("d199[%d] = %f\n", i, CPG_Result.dual->d199[i]);
  }
  for(i=0; i<4; i++) {
    printf("d200[%d] = %f\n", i, CPG_Result.dual->d200[i]);
  }
  for(i=0; i<4; i++) {
    printf("d201[%d] = %f\n", i, CPG_Result.dual->d201[i]);
  }
  for(i=0; i<4; i++) {
    printf("d202[%d] = %f\n", i, CPG_Result.dual->d202[i]);
  }
  for(i=0; i<4; i++) {
    printf("d203[%d] = %f\n", i, CPG_Result.dual->d203[i]);
  }
  for(i=0; i<4; i++) {
    printf("d204[%d] = %f\n", i, CPG_Result.dual->d204[i]);
  }
  for(i=0; i<4; i++) {
    printf("d205[%d] = %f\n", i, CPG_Result.dual->d205[i]);
  }
  for(i=0; i<4; i++) {
    printf("d206[%d] = %f\n", i, CPG_Result.dual->d206[i]);
  }
  for(i=0; i<4; i++) {
    printf("d207[%d] = %f\n", i, CPG_Result.dual->d207[i]);
  }
  for(i=0; i<4; i++) {
    printf("d208[%d] = %f\n", i, CPG_Result.dual->d208[i]);
  }
  for(i=0; i<4; i++) {
    printf("d209[%d] = %f\n", i, CPG_Result.dual->d209[i]);
  }
  for(i=0; i<4; i++) {
    printf("d210[%d] = %f\n", i, CPG_Result.dual->d210[i]);
  }
  for(i=0; i<4; i++) {
    printf("d211[%d] = %f\n", i, CPG_Result.dual->d211[i]);
  }
  for(i=0; i<4; i++) {
    printf("d212[%d] = %f\n", i, CPG_Result.dual->d212[i]);
  }
  for(i=0; i<4; i++) {
    printf("d213[%d] = %f\n", i, CPG_Result.dual->d213[i]);
  }
  for(i=0; i<4; i++) {
    printf("d214[%d] = %f\n", i, CPG_Result.dual->d214[i]);
  }
  for(i=0; i<4; i++) {
    printf("d215[%d] = %f\n", i, CPG_Result.dual->d215[i]);
  }
  for(i=0; i<4; i++) {
    printf("d216[%d] = %f\n", i, CPG_Result.dual->d216[i]);
  }
  for(i=0; i<4; i++) {
    printf("d217[%d] = %f\n", i, CPG_Result.dual->d217[i]);
  }
  for(i=0; i<4; i++) {
    printf("d218[%d] = %f\n", i, CPG_Result.dual->d218[i]);
  }
  for(i=0; i<4; i++) {
    printf("d219[%d] = %f\n", i, CPG_Result.dual->d219[i]);
  }
  for(i=0; i<4; i++) {
    printf("d220[%d] = %f\n", i, CPG_Result.dual->d220[i]);
  }
  for(i=0; i<4; i++) {
    printf("d221[%d] = %f\n", i, CPG_Result.dual->d221[i]);
  }
  for(i=0; i<4; i++) {
    printf("d222[%d] = %f\n", i, CPG_Result.dual->d222[i]);
  }
  for(i=0; i<4; i++) {
    printf("d223[%d] = %f\n", i, CPG_Result.dual->d223[i]);
  }
  for(i=0; i<4; i++) {
    printf("d224[%d] = %f\n", i, CPG_Result.dual->d224[i]);
  }
  for(i=0; i<4; i++) {
    printf("d225[%d] = %f\n", i, CPG_Result.dual->d225[i]);
  }
  for(i=0; i<4; i++) {
    printf("d226[%d] = %f\n", i, CPG_Result.dual->d226[i]);
  }
  for(i=0; i<4; i++) {
    printf("d227[%d] = %f\n", i, CPG_Result.dual->d227[i]);
  }
  for(i=0; i<4; i++) {
    printf("d228[%d] = %f\n", i, CPG_Result.dual->d228[i]);
  }
  for(i=0; i<4; i++) {
    printf("d229[%d] = %f\n", i, CPG_Result.dual->d229[i]);
  }
  for(i=0; i<4; i++) {
    printf("d230[%d] = %f\n", i, CPG_Result.dual->d230[i]);
  }
  for(i=0; i<4; i++) {
    printf("d231[%d] = %f\n", i, CPG_Result.dual->d231[i]);
  }
  for(i=0; i<4; i++) {
    printf("d232[%d] = %f\n", i, CPG_Result.dual->d232[i]);
  }
  for(i=0; i<4; i++) {
    printf("d233[%d] = %f\n", i, CPG_Result.dual->d233[i]);
  }
  for(i=0; i<4; i++) {
    printf("d234[%d] = %f\n", i, CPG_Result.dual->d234[i]);
  }
  for(i=0; i<4; i++) {
    printf("d235[%d] = %f\n", i, CPG_Result.dual->d235[i]);
  }
  for(i=0; i<4; i++) {
    printf("d236[%d] = %f\n", i, CPG_Result.dual->d236[i]);
  }
  for(i=0; i<4; i++) {
    printf("d237[%d] = %f\n", i, CPG_Result.dual->d237[i]);
  }
  for(i=0; i<4; i++) {
    printf("d238[%d] = %f\n", i, CPG_Result.dual->d238[i]);
  }
  for(i=0; i<4; i++) {
    printf("d239[%d] = %f\n", i, CPG_Result.dual->d239[i]);
  }
  for(i=0; i<4; i++) {
    printf("d240[%d] = %f\n", i, CPG_Result.dual->d240[i]);
  }
  for(i=0; i<4; i++) {
    printf("d241[%d] = %f\n", i, CPG_Result.dual->d241[i]);
  }
  for(i=0; i<4; i++) {
    printf("d242[%d] = %f\n", i, CPG_Result.dual->d242[i]);
  }
  for(i=0; i<4; i++) {
    printf("d243[%d] = %f\n", i, CPG_Result.dual->d243[i]);
  }
  for(i=0; i<4; i++) {
    printf("d244[%d] = %f\n", i, CPG_Result.dual->d244[i]);
  }
  for(i=0; i<4; i++) {
    printf("d245[%d] = %f\n", i, CPG_Result.dual->d245[i]);
  }
  for(i=0; i<4; i++) {
    printf("d246[%d] = %f\n", i, CPG_Result.dual->d246[i]);
  }
  for(i=0; i<4; i++) {
    printf("d247[%d] = %f\n", i, CPG_Result.dual->d247[i]);
  }
  for(i=0; i<4; i++) {
    printf("d248[%d] = %f\n", i, CPG_Result.dual->d248[i]);
  }
  for(i=0; i<4; i++) {
    printf("d249[%d] = %f\n", i, CPG_Result.dual->d249[i]);
  }
  for(i=0; i<4; i++) {
    printf("d250[%d] = %f\n", i, CPG_Result.dual->d250[i]);
  }
  for(i=0; i<4; i++) {
    printf("d251[%d] = %f\n", i, CPG_Result.dual->d251[i]);
  }
  for(i=0; i<4; i++) {
    printf("d252[%d] = %f\n", i, CPG_Result.dual->d252[i]);
  }
  for(i=0; i<4; i++) {
    printf("d253[%d] = %f\n", i, CPG_Result.dual->d253[i]);
  }
  for(i=0; i<4; i++) {
    printf("d254[%d] = %f\n", i, CPG_Result.dual->d254[i]);
  }
  for(i=0; i<4; i++) {
    printf("d255[%d] = %f\n", i, CPG_Result.dual->d255[i]);
  }
  for(i=0; i<4; i++) {
    printf("d256[%d] = %f\n", i, CPG_Result.dual->d256[i]);
  }
  for(i=0; i<4; i++) {
    printf("d257[%d] = %f\n", i, CPG_Result.dual->d257[i]);
  }
  for(i=0; i<4; i++) {
    printf("d258[%d] = %f\n", i, CPG_Result.dual->d258[i]);
  }
  for(i=0; i<4; i++) {
    printf("d259[%d] = %f\n", i, CPG_Result.dual->d259[i]);
  }
  for(i=0; i<4; i++) {
    printf("d260[%d] = %f\n", i, CPG_Result.dual->d260[i]);
  }
  for(i=0; i<4; i++) {
    printf("d261[%d] = %f\n", i, CPG_Result.dual->d261[i]);
  }
  for(i=0; i<4; i++) {
    printf("d262[%d] = %f\n", i, CPG_Result.dual->d262[i]);
  }
  for(i=0; i<4; i++) {
    printf("d263[%d] = %f\n", i, CPG_Result.dual->d263[i]);
  }
  for(i=0; i<4; i++) {
    printf("d264[%d] = %f\n", i, CPG_Result.dual->d264[i]);
  }
  for(i=0; i<4; i++) {
    printf("d265[%d] = %f\n", i, CPG_Result.dual->d265[i]);
  }
  for(i=0; i<4; i++) {
    printf("d266[%d] = %f\n", i, CPG_Result.dual->d266[i]);
  }
  for(i=0; i<4; i++) {
    printf("d267[%d] = %f\n", i, CPG_Result.dual->d267[i]);
  }
  for(i=0; i<4; i++) {
    printf("d268[%d] = %f\n", i, CPG_Result.dual->d268[i]);
  }
  for(i=0; i<4; i++) {
    printf("d269[%d] = %f\n", i, CPG_Result.dual->d269[i]);
  }
  for(i=0; i<4; i++) {
    printf("d270[%d] = %f\n", i, CPG_Result.dual->d270[i]);
  }
  for(i=0; i<4; i++) {
    printf("d271[%d] = %f\n", i, CPG_Result.dual->d271[i]);
  }
  for(i=0; i<4; i++) {
    printf("d272[%d] = %f\n", i, CPG_Result.dual->d272[i]);
  }
  for(i=0; i<4; i++) {
    printf("d273[%d] = %f\n", i, CPG_Result.dual->d273[i]);
  }


  return 0;

}
