
/*
Auto-generated by CVXPYgen on May 29, 2026 at 14:48:01.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_start_pos(0, 1.02420518276338401442);
  cpg_update_end_pos(0, 0.24161765285303071771);
  cpg_update_A_0(0, -1.04403520971235264092);
  cpg_update_B_0(0, -0.04398271428251742526);
  cpg_update_y_0(0, -1.66267694625877826553);
  cpg_update_A_1(0, -0.78412211446616886246);
  cpg_update_B_1(0, -0.83446983149211417796);
  cpg_update_y_1(0, 1.50914946353296275383);
  cpg_update_A_2(0, -0.67413375538530673214);
  cpg_update_B_2(0, 0.01067654133904995771);
  cpg_update_y_2(0, 0.66907550078166388996);
  cpg_update_A_3(0, -0.76653019582253989483);
  cpg_update_B_3(0, -0.12872738819574680580);
  cpg_update_y_3(0, -0.43422258291412185738);
  cpg_update_A_4(0, -0.62447341548048806992);
  cpg_update_B_4(0, 0.12201924479561176984);
  cpg_update_y_4(0, -2.02694644238136190140);
  cpg_update_A_5(0, 1.07609566760507457950);
  cpg_update_B_5(0, -0.53509560673699485545);
  cpg_update_y_5(0, 1.46308147941635668943);
  cpg_update_A_6(0, -1.26823027498138363178);
  cpg_update_B_6(0, 0.20180532179760812816);
  cpg_update_y_6(0, 0.96824155279557588827);
  cpg_update_A_7(0, 0.45087203978052964315);
  cpg_update_B_7(0, -0.06180588076772772221);
  cpg_update_y_7(0, 1.23618569726414850862);
  cpg_update_A_8(0, 1.43674851399437919497);
  cpg_update_B_8(0, 2.24854815382328254714);
  cpg_update_y_8(0, -1.29577802334056335631);
  cpg_update_A_9(0, 0.32340926997764818385);
  cpg_update_B_9(0, -1.03176813988952842394);
  cpg_update_y_9(0, -2.64632056123912295931);
  cpg_update_A_10(0, -0.05881017050502849314);
  cpg_update_B_10(0, -2.44695375690068139818);
  cpg_update_y_10(0, -0.54550782241385886717);
  cpg_update_A_11(0, -1.17988839651230836836);
  cpg_update_B_11(0, 0.18172887080456204267);
  cpg_update_y_11(0, -1.17848273951869875198);
  cpg_update_A_12(0, -0.19698163087248460323);
  cpg_update_B_12(0, -1.77967456839111326516);
  cpg_update_y_12(0, -0.70336408817760165402);
  cpg_update_A_13(0, -0.56648355428791374866);
  cpg_update_B_13(0, -0.52885718019987371097);
  cpg_update_y_13(0, -2.08867132358874840747);
  cpg_update_A_14(0, -0.15499270596790490351);
  cpg_update_B_14(0, 0.24975277752764729611);
  cpg_update_y_14(0, -0.14272310133235704965);
  cpg_update_A_15(0, -0.95402527024375749498);
  cpg_update_B_15(0, 0.90788385049018194284);
  cpg_update_y_15(0, -0.24433712523990833154);
  cpg_update_A_16(0, -0.53118172925842066512);
  cpg_update_B_16(0, 1.96426536562181319745);
  cpg_update_y_16(0, -0.00064924171884567618);
  cpg_update_A_17(0, -0.11257003103172373570);
  cpg_update_B_17(0, 1.68127328319261337697);
  cpg_update_y_17(0, -0.10353955751564376808);
  cpg_update_A_18(0, -2.28445650910855491134);
  cpg_update_B_18(0, 0.78248415590803610531);
  cpg_update_y_18(0, -0.67456307458808850708);
  cpg_update_A_19(0, 0.09588456926244974532);
  cpg_update_B_19(0, 0.94766671822335157849);
  cpg_update_y_19(0, -1.40622614656302857838);
  cpg_update_A_20(0, 0.96421777004215147855);
  cpg_update_B_20(0, 1.66349228178867103445);
  cpg_update_y_20(0, 2.14284227352969391944);
  cpg_update_A_21(0, 0.98023526789835013773);
  cpg_update_B_21(0, -0.48948734819854261557);
  cpg_update_y_21(0, -1.09500135271196818998);
  cpg_update_A_22(0, -0.26176157584504800013);
  cpg_update_B_22(0, 0.30448483284362620749);
  cpg_update_y_22(0, -1.50606404743391308898);
  cpg_update_A_23(0, -0.53891935355960696175);
  cpg_update_B_23(0, 0.00565930214549470716);
  cpg_update_y_23(0, -0.65468392181855183942);
  cpg_update_A_24(0, -0.40396337085109057519);
  cpg_update_B_24(0, 0.85156404845342481558);
  cpg_update_y_24(0, 0.40049475212714902295);
  cpg_update_A_25(0, -0.63500830170837985200);
  cpg_update_B_25(0, 0.08195050437555800871);
  cpg_update_y_25(0, -0.31266104601063765545);
  cpg_update_A_26(0, -1.01133162323859937537);
  cpg_update_B_26(0, 1.79657720712799240381);
  cpg_update_y_26(0, 0.70896476672668762298);
  cpg_update_A_27(0, -0.41061603915344863092);
  cpg_update_B_27(0, -0.42376388853983099070);
  cpg_update_y_27(0, 0.10112020562033159632);
  cpg_update_A_28(0, -0.63035301764356488352);
  cpg_update_B_28(0, -0.32647505624063094531);
  cpg_update_y_28(0, 0.48795738120919890379);
  cpg_update_A_29(0, -0.08510878601522085807);
  cpg_update_B_29(0, -0.13454731513016676692);
  cpg_update_y_29(0, -0.64700733961591927468);
  cpg_update_ox_0(0, 0.90893963752551765189);
  cpg_update_ou_0(0, 2.10157280732205631324);
  cpg_update_etta(0.33460250065704255640);
  cpg_update_ox_1(0, 0.57077628478944464341);
  cpg_update_ou_1(0, 0.99972070284497493997);
  cpg_update_ox_2(0, 0.71284679782817639282);
  cpg_update_ou_2(0, -0.78075999813241603320);
  cpg_update_ox_3(0, -0.20514069785789415534);
  cpg_update_ou_3(0, 1.45479450952128486207);
  cpg_update_ox_4(0, 0.94719986093717223330);
  cpg_update_ou_4(0, -0.47984341753736603486);
  cpg_update_ox_5(0, -0.12465188758605297292);
  cpg_update_ou_5(0, 1.93026082308891377970);
  cpg_update_ox_6(0, -1.10546165727140355273);
  cpg_update_ou_6(0, -0.90226449904625583009);
  cpg_update_ox_7(0, 1.35124231934879635020);
  cpg_update_ou_7(0, -0.51014973989123335585);
  cpg_update_ox_8(0, -0.79544226392539763015);
  cpg_update_ou_8(0, -0.00828572570526104474);
  cpg_update_ox_9(0, 0.64577900432383261720);
  cpg_update_ou_9(0, -0.75370166644186809002);
  cpg_update_ox_10(0, -0.36898914979518382395);
  cpg_update_ou_10(0, -0.52294386605074427710);
  cpg_update_ox_11(0, 2.03552156554206620243);
  cpg_update_ou_11(0, -0.58635435898374843600);
  cpg_update_ox_12(0, -1.80492259363727458599);
  cpg_update_ou_12(0, 0.38796275061833646047);
  cpg_update_ox_13(0, 0.34108901672268443495);
  cpg_update_ou_13(0, -1.27141461646507125671);
  cpg_update_ox_14(0, 1.50319149516478112183);
  cpg_update_ou_14(0, -1.69802132410630135517);
  cpg_update_ox_15(0, -0.55767429734476670067);
  cpg_update_ou_15(0, -0.43495550790842957278);
  cpg_update_ox_16(0, -0.71958466036413615274);
  cpg_update_ou_16(0, 1.03805595890696422678);
  cpg_update_ox_17(0, -0.19240591891042654882);
  cpg_update_ou_17(0, -1.01686993961881255721);
  cpg_update_ox_18(0, -1.19231878591357487451);
  cpg_update_ou_18(0, -1.44646906430442312441);
  cpg_update_ox_19(0, -0.58404343969003980064);
  cpg_update_ou_19(0, -2.13868506170760275253);
  cpg_update_ox_20(0, -0.39614695197356641909);
  cpg_update_ou_20(0, -2.13461880227142453137);
  cpg_update_ox_21(0, 0.93725276244122068814);
  cpg_update_ou_21(0, -1.31600478456126523952);
  cpg_update_ox_22(0, -0.07981270228428449798);
  cpg_update_ou_22(0, 0.05033637066379037517);
  cpg_update_ox_23(0, 1.00465984205800795692);
  cpg_update_ou_23(0, 0.16059271263867069823);
  cpg_update_ox_24(0, -1.75937912072592350654);
  cpg_update_ou_24(0, 0.79815691764538188036);
  cpg_update_ox_25(0, -0.05562977816331505371);
  cpg_update_ou_25(0, -0.26389837947302996479);
  cpg_update_ox_26(0, -0.87077925404016010003);
  cpg_update_ou_26(0, 2.22880187256835293752);
  cpg_update_ox_27(0, 0.64902505671931653985);
  cpg_update_ou_27(0, -1.26472475942677853311);
  cpg_update_ox_28(0, -0.51564681811531642985);
  cpg_update_ou_28(0, 0.93430636976848535635);
  cpg_update_ox_29(0, -0.82933484654090394717);
  cpg_update_ou_29(0, -0.69914140135514912799);
  cpg_update_ox_30(0, -0.59037219617282887807);
  cpg_update_C_0(0, -0.81028772498296053328);
  cpg_update_D_0(0, -1.11248981961035831034);
  cpg_update_z_0(0, -0.61441241164591453572);
  cpg_update_C_1(0, -0.06468777600481318002);
  cpg_update_D_1(0, -1.57515923499548482489);
  cpg_update_z_1(0, -1.21282815995307791113);
  cpg_update_C_2(0, 0.95996965438757853040);
  cpg_update_D_2(0, -1.44215692661803718266);
  cpg_update_z_2(0, -0.46631762876238336268);
  cpg_update_C_3(0, 0.05905179778601099549);
  cpg_update_D_3(0, -1.08685841503717450784);
  cpg_update_z_3(0, 0.79669165129920704871);
  cpg_update_C_4(0, -0.92425033709887016720);
  cpg_update_D_4(0, 0.27439875616161185645);
  cpg_update_z_4(0, -1.12283777224227976355);
  cpg_update_C_5(0, -0.28094920301788905981);
  cpg_update_D_5(0, 0.59619620955005603324);
  cpg_update_z_5(0, -0.61829996883340820890);
  cpg_update_C_6(0, 1.01406695590530970819);
  cpg_update_D_6(0, 1.49941596408685784425);
  cpg_update_z_6(0, -0.28116162489739282559);
  cpg_update_C_7(0, 1.05138966508581832571);
  cpg_update_D_7(0, 0.25016267127230845668);
  cpg_update_z_7(0, -0.16049986825110329480);
  cpg_update_C_8(0, 1.00989315028069226443);
  cpg_update_D_8(0, -1.23550591127222375576);
  cpg_update_z_8(0, 0.95959357008200618644);
  cpg_update_C_9(0, 1.68592299772924048007);
  cpg_update_D_9(0, 1.16234934101533626816);
  cpg_update_z_9(0, -0.99413816591192194494);
  cpg_update_C_10(0, -1.78000250429569573107);
  cpg_update_D_10(0, -0.29322095890488963921);
  cpg_update_z_10(0, 1.20987378827195168896);
  cpg_update_C_11(0, 1.61007739910358393942);
  cpg_update_D_11(0, 1.91295898848064549469);
  cpg_update_z_11(0, 1.43835430396107932793);
  cpg_update_C_12(0, 0.47533139870262769433);
  cpg_update_D_12(0, -0.81084107309429587218);
  cpg_update_z_12(0, 0.07017793730330364188);
  cpg_update_C_13(0, 0.87228497458987608315);
  cpg_update_D_13(0, 0.84382264584019250897);
  cpg_update_z_13(0, 0.33973180575541023218);
  cpg_update_C_14(0, -0.75695241621802877852);
  cpg_update_D_14(0, 0.77046740941592761764);
  cpg_update_z_14(0, -0.04749320818736322419);
  cpg_update_C_15(0, -0.66307799897733843419);
  cpg_update_D_15(0, -0.00272542362375195789);
  cpg_update_z_15(0, -0.54369081742733404994);
  cpg_update_C_16(0, -0.37134157590215521871);
  cpg_update_D_16(0, -1.96717058165431590844);
  cpg_update_z_16(0, -0.98336242607749135836);
  cpg_update_C_17(0, -0.22391588692140229622);
  cpg_update_D_17(0, 1.25820120775392574330);
  cpg_update_z_17(0, -0.19561011469292222120);
  cpg_update_C_18(0, 0.81401281571376404855);
  cpg_update_D_18(0, -1.61350187620936003086);
  cpg_update_z_18(0, 0.18050746799902595008);
  cpg_update_C_19(0, 2.46741462082453111293);
  cpg_update_D_19(0, 1.29609717899710674693);
  cpg_update_z_19(0, 0.27980892168103954631);
  cpg_update_C_20(0, 0.28179627002323626161);
  cpg_update_D_20(0, -0.00148180300360552372);
  cpg_update_z_20(0, -1.18228303437846360424);
  cpg_update_C_21(0, -2.02705454395744588680);
  cpg_update_D_21(0, -0.27208219054913390655);
  cpg_update_z_21(0, 0.30751427108816431488);
  cpg_update_C_22(0, 0.94008178733643377178);
  cpg_update_D_22(0, 0.57586155866965904604);
  cpg_update_z_22(0, -1.66435750013479899501);
  cpg_update_C_23(0, 1.28850410462073994289);
  cpg_update_D_23(0, 1.19083004543043147194);
  cpg_update_z_23(0, 0.19198103694647225548);
  cpg_update_C_24(0, 0.45894592081530505290);
  cpg_update_D_24(0, -1.30540760558270774183);
  cpg_update_z_24(0, 1.18690001805054046180);
  cpg_update_C_25(0, -0.13450223146257672679);
  cpg_update_D_25(0, 0.08316116548177643342);
  cpg_update_z_25(0, -0.72583438062857918993);
  cpg_update_C_26(0, 1.37724491146689986820);
  cpg_update_D_26(0, 1.54903445602293410310);
  cpg_update_z_26(0, -0.14473144362601730872);
  cpg_update_C_27(0, -0.18432291544106396697);
  cpg_update_D_27(0, -1.84960742061686156390);
  cpg_update_z_27(0, 0.20558572962752491575);
  cpg_update_C_28(0, 0.37585340851522269778);
  cpg_update_D_28(0, -0.26037888490864569135);
  cpg_update_z_28(0, 0.43390992293163355153);
  cpg_update_C_29(0, 2.44941771036836275499);
  cpg_update_D_29(0, -0.00292067116458185911);
  cpg_update_z_29(0, 0.89913603590781632224);
  cpg_update_C_30(0, -0.12139644561225364228);
  cpg_update_D_30(0, -1.61489902649795702416);
  cpg_update_z_30(0, 0.49478932806099440445);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<180; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<390; i++) {
    printf("vc[%d] = %f\n", i, CPG_Result.prim->vc[i]);
  }
  for(i=0; i<93; i++) {
    printf("vi[%d] = %f\n", i, CPG_Result.prim->vi[i]);
  }
  for(i=0; i<403; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }

  // Print dual solution
  for(i=0; i<13; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<13; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<13; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<13; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<13; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<13; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<13; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<13; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<13; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<13; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<13; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<13; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<13; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<13; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<13; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<13; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<13; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<13; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<13; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<13; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<13; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<13; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<13; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<13; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<13; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<13; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<13; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<13; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<13; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<13; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<13; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<13; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  printf("d32 = %f\n", CPG_Result.dual->d32);
  printf("d33 = %f\n", CPG_Result.dual->d33);
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  for(i=0; i<3; i++) {
    printf("d63[%d] = %f\n", i, CPG_Result.dual->d63[i]);
  }
  for(i=0; i<3; i++) {
    printf("d64[%d] = %f\n", i, CPG_Result.dual->d64[i]);
  }
  for(i=0; i<3; i++) {
    printf("d65[%d] = %f\n", i, CPG_Result.dual->d65[i]);
  }
  for(i=0; i<3; i++) {
    printf("d66[%d] = %f\n", i, CPG_Result.dual->d66[i]);
  }
  for(i=0; i<3; i++) {
    printf("d67[%d] = %f\n", i, CPG_Result.dual->d67[i]);
  }
  for(i=0; i<3; i++) {
    printf("d68[%d] = %f\n", i, CPG_Result.dual->d68[i]);
  }
  for(i=0; i<3; i++) {
    printf("d69[%d] = %f\n", i, CPG_Result.dual->d69[i]);
  }
  for(i=0; i<3; i++) {
    printf("d70[%d] = %f\n", i, CPG_Result.dual->d70[i]);
  }
  for(i=0; i<3; i++) {
    printf("d71[%d] = %f\n", i, CPG_Result.dual->d71[i]);
  }
  for(i=0; i<3; i++) {
    printf("d72[%d] = %f\n", i, CPG_Result.dual->d72[i]);
  }
  for(i=0; i<3; i++) {
    printf("d73[%d] = %f\n", i, CPG_Result.dual->d73[i]);
  }
  for(i=0; i<3; i++) {
    printf("d74[%d] = %f\n", i, CPG_Result.dual->d74[i]);
  }
  for(i=0; i<3; i++) {
    printf("d75[%d] = %f\n", i, CPG_Result.dual->d75[i]);
  }
  for(i=0; i<3; i++) {
    printf("d76[%d] = %f\n", i, CPG_Result.dual->d76[i]);
  }
  for(i=0; i<3; i++) {
    printf("d77[%d] = %f\n", i, CPG_Result.dual->d77[i]);
  }
  for(i=0; i<3; i++) {
    printf("d78[%d] = %f\n", i, CPG_Result.dual->d78[i]);
  }
  for(i=0; i<3; i++) {
    printf("d79[%d] = %f\n", i, CPG_Result.dual->d79[i]);
  }
  for(i=0; i<3; i++) {
    printf("d80[%d] = %f\n", i, CPG_Result.dual->d80[i]);
  }
  for(i=0; i<3; i++) {
    printf("d81[%d] = %f\n", i, CPG_Result.dual->d81[i]);
  }
  for(i=0; i<3; i++) {
    printf("d82[%d] = %f\n", i, CPG_Result.dual->d82[i]);
  }
  for(i=0; i<3; i++) {
    printf("d83[%d] = %f\n", i, CPG_Result.dual->d83[i]);
  }
  for(i=0; i<3; i++) {
    printf("d84[%d] = %f\n", i, CPG_Result.dual->d84[i]);
  }
  for(i=0; i<3; i++) {
    printf("d85[%d] = %f\n", i, CPG_Result.dual->d85[i]);
  }
  for(i=0; i<3; i++) {
    printf("d86[%d] = %f\n", i, CPG_Result.dual->d86[i]);
  }
  for(i=0; i<3; i++) {
    printf("d87[%d] = %f\n", i, CPG_Result.dual->d87[i]);
  }
  for(i=0; i<3; i++) {
    printf("d88[%d] = %f\n", i, CPG_Result.dual->d88[i]);
  }
  for(i=0; i<3; i++) {
    printf("d89[%d] = %f\n", i, CPG_Result.dual->d89[i]);
  }
  for(i=0; i<3; i++) {
    printf("d90[%d] = %f\n", i, CPG_Result.dual->d90[i]);
  }
  for(i=0; i<3; i++) {
    printf("d91[%d] = %f\n", i, CPG_Result.dual->d91[i]);
  }
  for(i=0; i<3; i++) {
    printf("d92[%d] = %f\n", i, CPG_Result.dual->d92[i]);
  }
  for(i=0; i<3; i++) {
    printf("d93[%d] = %f\n", i, CPG_Result.dual->d93[i]);
  }
  printf("d94 = %f\n", CPG_Result.dual->d94);
  printf("d95 = %f\n", CPG_Result.dual->d95);
  printf("d96 = %f\n", CPG_Result.dual->d96);
  printf("d97 = %f\n", CPG_Result.dual->d97);
  printf("d98 = %f\n", CPG_Result.dual->d98);
  printf("d99 = %f\n", CPG_Result.dual->d99);
  printf("d100 = %f\n", CPG_Result.dual->d100);
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  printf("d109 = %f\n", CPG_Result.dual->d109);
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  printf("d122 = %f\n", CPG_Result.dual->d122);
  printf("d123 = %f\n", CPG_Result.dual->d123);
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  printf("d126 = %f\n", CPG_Result.dual->d126);
  printf("d127 = %f\n", CPG_Result.dual->d127);
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  printf("d131 = %f\n", CPG_Result.dual->d131);
  printf("d132 = %f\n", CPG_Result.dual->d132);
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  printf("d135 = %f\n", CPG_Result.dual->d135);
  printf("d136 = %f\n", CPG_Result.dual->d136);
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  printf("d140 = %f\n", CPG_Result.dual->d140);
  printf("d141 = %f\n", CPG_Result.dual->d141);
  printf("d142 = %f\n", CPG_Result.dual->d142);
  printf("d143 = %f\n", CPG_Result.dual->d143);
  printf("d144 = %f\n", CPG_Result.dual->d144);
  printf("d145 = %f\n", CPG_Result.dual->d145);
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  printf("d149 = %f\n", CPG_Result.dual->d149);
  printf("d150 = %f\n", CPG_Result.dual->d150);
  printf("d151 = %f\n", CPG_Result.dual->d151);
  printf("d152 = %f\n", CPG_Result.dual->d152);
  printf("d153 = %f\n", CPG_Result.dual->d153);
  printf("d154 = %f\n", CPG_Result.dual->d154);
  printf("d155 = %f\n", CPG_Result.dual->d155);
  printf("d156 = %f\n", CPG_Result.dual->d156);
  printf("d157 = %f\n", CPG_Result.dual->d157);
  printf("d158 = %f\n", CPG_Result.dual->d158);
  printf("d159 = %f\n", CPG_Result.dual->d159);
  printf("d160 = %f\n", CPG_Result.dual->d160);
  printf("d161 = %f\n", CPG_Result.dual->d161);
  printf("d162 = %f\n", CPG_Result.dual->d162);
  printf("d163 = %f\n", CPG_Result.dual->d163);
  printf("d164 = %f\n", CPG_Result.dual->d164);
  printf("d165 = %f\n", CPG_Result.dual->d165);
  printf("d166 = %f\n", CPG_Result.dual->d166);
  printf("d167 = %f\n", CPG_Result.dual->d167);
  printf("d168 = %f\n", CPG_Result.dual->d168);
  printf("d169 = %f\n", CPG_Result.dual->d169);
  printf("d170 = %f\n", CPG_Result.dual->d170);
  printf("d171 = %f\n", CPG_Result.dual->d171);
  printf("d172 = %f\n", CPG_Result.dual->d172);
  printf("d173 = %f\n", CPG_Result.dual->d173);
  printf("d174 = %f\n", CPG_Result.dual->d174);
  printf("d175 = %f\n", CPG_Result.dual->d175);
  printf("d176 = %f\n", CPG_Result.dual->d176);
  printf("d177 = %f\n", CPG_Result.dual->d177);
  printf("d178 = %f\n", CPG_Result.dual->d178);
  printf("d179 = %f\n", CPG_Result.dual->d179);
  printf("d180 = %f\n", CPG_Result.dual->d180);
  printf("d181 = %f\n", CPG_Result.dual->d181);
  printf("d182 = %f\n", CPG_Result.dual->d182);
  printf("d183 = %f\n", CPG_Result.dual->d183);
  printf("d184 = %f\n", CPG_Result.dual->d184);
  printf("d185 = %f\n", CPG_Result.dual->d185);
  printf("d186 = %f\n", CPG_Result.dual->d186);
  printf("d187 = %f\n", CPG_Result.dual->d187);
  printf("d188 = %f\n", CPG_Result.dual->d188);
  printf("d189 = %f\n", CPG_Result.dual->d189);
  printf("d190 = %f\n", CPG_Result.dual->d190);
  printf("d191 = %f\n", CPG_Result.dual->d191);
  printf("d192 = %f\n", CPG_Result.dual->d192);
  printf("d193 = %f\n", CPG_Result.dual->d193);
  printf("d194 = %f\n", CPG_Result.dual->d194);
  printf("d195 = %f\n", CPG_Result.dual->d195);
  printf("d196 = %f\n", CPG_Result.dual->d196);
  printf("d197 = %f\n", CPG_Result.dual->d197);
  printf("d198 = %f\n", CPG_Result.dual->d198);
  printf("d199 = %f\n", CPG_Result.dual->d199);
  printf("d200 = %f\n", CPG_Result.dual->d200);
  printf("d201 = %f\n", CPG_Result.dual->d201);
  printf("d202 = %f\n", CPG_Result.dual->d202);
  printf("d203 = %f\n", CPG_Result.dual->d203);
  printf("d204 = %f\n", CPG_Result.dual->d204);
  printf("d205 = %f\n", CPG_Result.dual->d205);
  printf("d206 = %f\n", CPG_Result.dual->d206);
  printf("d207 = %f\n", CPG_Result.dual->d207);
  printf("d208 = %f\n", CPG_Result.dual->d208);
  printf("d209 = %f\n", CPG_Result.dual->d209);
  printf("d210 = %f\n", CPG_Result.dual->d210);
  printf("d211 = %f\n", CPG_Result.dual->d211);
  printf("d212 = %f\n", CPG_Result.dual->d212);
  printf("d213 = %f\n", CPG_Result.dual->d213);
  printf("d214 = %f\n", CPG_Result.dual->d214);
  printf("d215 = %f\n", CPG_Result.dual->d215);

  return 0;

}
