
/*
Auto-generated by CVXPYgen on August 22, 2026 at 15:05:10
Content: Python binding with pybind11
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include <chrono>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.start_pos) {
        for(i=0; i<7; i++) {
            cpg_update_start_pos(i, CPG_Params_cpp.start_pos[i]);
        }
    }
    if (CPG_Updated_cpp.end_pos) {
        for(i=0; i<7; i++) {
            cpg_update_end_pos(i, CPG_Params_cpp.end_pos[i]);
        }
    }
    if (CPG_Updated_cpp.A_0) {
        for(i=0; i<49; i++) {
            cpg_update_A_0(i, CPG_Params_cpp.A_0[i]);
        }
    }
    if (CPG_Updated_cpp.B_0) {
        for(i=0; i<28; i++) {
            cpg_update_B_0(i, CPG_Params_cpp.B_0[i]);
        }
    }
    if (CPG_Updated_cpp.y_0) {
        for(i=0; i<7; i++) {
            cpg_update_y_0(i, CPG_Params_cpp.y_0[i]);
        }
    }
    if (CPG_Updated_cpp.A_1) {
        for(i=0; i<49; i++) {
            cpg_update_A_1(i, CPG_Params_cpp.A_1[i]);
        }
    }
    if (CPG_Updated_cpp.B_1) {
        for(i=0; i<28; i++) {
            cpg_update_B_1(i, CPG_Params_cpp.B_1[i]);
        }
    }
    if (CPG_Updated_cpp.y_1) {
        for(i=0; i<7; i++) {
            cpg_update_y_1(i, CPG_Params_cpp.y_1[i]);
        }
    }
    if (CPG_Updated_cpp.A_2) {
        for(i=0; i<49; i++) {
            cpg_update_A_2(i, CPG_Params_cpp.A_2[i]);
        }
    }
    if (CPG_Updated_cpp.B_2) {
        for(i=0; i<28; i++) {
            cpg_update_B_2(i, CPG_Params_cpp.B_2[i]);
        }
    }
    if (CPG_Updated_cpp.y_2) {
        for(i=0; i<7; i++) {
            cpg_update_y_2(i, CPG_Params_cpp.y_2[i]);
        }
    }
    if (CPG_Updated_cpp.A_3) {
        for(i=0; i<49; i++) {
            cpg_update_A_3(i, CPG_Params_cpp.A_3[i]);
        }
    }
    if (CPG_Updated_cpp.B_3) {
        for(i=0; i<28; i++) {
            cpg_update_B_3(i, CPG_Params_cpp.B_3[i]);
        }
    }
    if (CPG_Updated_cpp.y_3) {
        for(i=0; i<7; i++) {
            cpg_update_y_3(i, CPG_Params_cpp.y_3[i]);
        }
    }
    if (CPG_Updated_cpp.A_4) {
        for(i=0; i<49; i++) {
            cpg_update_A_4(i, CPG_Params_cpp.A_4[i]);
        }
    }
    if (CPG_Updated_cpp.B_4) {
        for(i=0; i<28; i++) {
            cpg_update_B_4(i, CPG_Params_cpp.B_4[i]);
        }
    }
    if (CPG_Updated_cpp.y_4) {
        for(i=0; i<7; i++) {
            cpg_update_y_4(i, CPG_Params_cpp.y_4[i]);
        }
    }
    if (CPG_Updated_cpp.A_5) {
        for(i=0; i<49; i++) {
            cpg_update_A_5(i, CPG_Params_cpp.A_5[i]);
        }
    }
    if (CPG_Updated_cpp.B_5) {
        for(i=0; i<28; i++) {
            cpg_update_B_5(i, CPG_Params_cpp.B_5[i]);
        }
    }
    if (CPG_Updated_cpp.y_5) {
        for(i=0; i<7; i++) {
            cpg_update_y_5(i, CPG_Params_cpp.y_5[i]);
        }
    }
    if (CPG_Updated_cpp.A_6) {
        for(i=0; i<49; i++) {
            cpg_update_A_6(i, CPG_Params_cpp.A_6[i]);
        }
    }
    if (CPG_Updated_cpp.B_6) {
        for(i=0; i<28; i++) {
            cpg_update_B_6(i, CPG_Params_cpp.B_6[i]);
        }
    }
    if (CPG_Updated_cpp.y_6) {
        for(i=0; i<7; i++) {
            cpg_update_y_6(i, CPG_Params_cpp.y_6[i]);
        }
    }
    if (CPG_Updated_cpp.A_7) {
        for(i=0; i<49; i++) {
            cpg_update_A_7(i, CPG_Params_cpp.A_7[i]);
        }
    }
    if (CPG_Updated_cpp.B_7) {
        for(i=0; i<28; i++) {
            cpg_update_B_7(i, CPG_Params_cpp.B_7[i]);
        }
    }
    if (CPG_Updated_cpp.y_7) {
        for(i=0; i<7; i++) {
            cpg_update_y_7(i, CPG_Params_cpp.y_7[i]);
        }
    }
    if (CPG_Updated_cpp.A_8) {
        for(i=0; i<49; i++) {
            cpg_update_A_8(i, CPG_Params_cpp.A_8[i]);
        }
    }
    if (CPG_Updated_cpp.B_8) {
        for(i=0; i<28; i++) {
            cpg_update_B_8(i, CPG_Params_cpp.B_8[i]);
        }
    }
    if (CPG_Updated_cpp.y_8) {
        for(i=0; i<7; i++) {
            cpg_update_y_8(i, CPG_Params_cpp.y_8[i]);
        }
    }
    if (CPG_Updated_cpp.A_9) {
        for(i=0; i<49; i++) {
            cpg_update_A_9(i, CPG_Params_cpp.A_9[i]);
        }
    }
    if (CPG_Updated_cpp.B_9) {
        for(i=0; i<28; i++) {
            cpg_update_B_9(i, CPG_Params_cpp.B_9[i]);
        }
    }
    if (CPG_Updated_cpp.y_9) {
        for(i=0; i<7; i++) {
            cpg_update_y_9(i, CPG_Params_cpp.y_9[i]);
        }
    }
    if (CPG_Updated_cpp.A_10) {
        for(i=0; i<49; i++) {
            cpg_update_A_10(i, CPG_Params_cpp.A_10[i]);
        }
    }
    if (CPG_Updated_cpp.B_10) {
        for(i=0; i<28; i++) {
            cpg_update_B_10(i, CPG_Params_cpp.B_10[i]);
        }
    }
    if (CPG_Updated_cpp.y_10) {
        for(i=0; i<7; i++) {
            cpg_update_y_10(i, CPG_Params_cpp.y_10[i]);
        }
    }
    if (CPG_Updated_cpp.A_11) {
        for(i=0; i<49; i++) {
            cpg_update_A_11(i, CPG_Params_cpp.A_11[i]);
        }
    }
    if (CPG_Updated_cpp.B_11) {
        for(i=0; i<28; i++) {
            cpg_update_B_11(i, CPG_Params_cpp.B_11[i]);
        }
    }
    if (CPG_Updated_cpp.y_11) {
        for(i=0; i<7; i++) {
            cpg_update_y_11(i, CPG_Params_cpp.y_11[i]);
        }
    }
    if (CPG_Updated_cpp.A_12) {
        for(i=0; i<49; i++) {
            cpg_update_A_12(i, CPG_Params_cpp.A_12[i]);
        }
    }
    if (CPG_Updated_cpp.B_12) {
        for(i=0; i<28; i++) {
            cpg_update_B_12(i, CPG_Params_cpp.B_12[i]);
        }
    }
    if (CPG_Updated_cpp.y_12) {
        for(i=0; i<7; i++) {
            cpg_update_y_12(i, CPG_Params_cpp.y_12[i]);
        }
    }
    if (CPG_Updated_cpp.A_13) {
        for(i=0; i<49; i++) {
            cpg_update_A_13(i, CPG_Params_cpp.A_13[i]);
        }
    }
    if (CPG_Updated_cpp.B_13) {
        for(i=0; i<28; i++) {
            cpg_update_B_13(i, CPG_Params_cpp.B_13[i]);
        }
    }
    if (CPG_Updated_cpp.y_13) {
        for(i=0; i<7; i++) {
            cpg_update_y_13(i, CPG_Params_cpp.y_13[i]);
        }
    }
    if (CPG_Updated_cpp.A_14) {
        for(i=0; i<49; i++) {
            cpg_update_A_14(i, CPG_Params_cpp.A_14[i]);
        }
    }
    if (CPG_Updated_cpp.B_14) {
        for(i=0; i<28; i++) {
            cpg_update_B_14(i, CPG_Params_cpp.B_14[i]);
        }
    }
    if (CPG_Updated_cpp.y_14) {
        for(i=0; i<7; i++) {
            cpg_update_y_14(i, CPG_Params_cpp.y_14[i]);
        }
    }
    if (CPG_Updated_cpp.A_15) {
        for(i=0; i<49; i++) {
            cpg_update_A_15(i, CPG_Params_cpp.A_15[i]);
        }
    }
    if (CPG_Updated_cpp.B_15) {
        for(i=0; i<28; i++) {
            cpg_update_B_15(i, CPG_Params_cpp.B_15[i]);
        }
    }
    if (CPG_Updated_cpp.y_15) {
        for(i=0; i<7; i++) {
            cpg_update_y_15(i, CPG_Params_cpp.y_15[i]);
        }
    }
    if (CPG_Updated_cpp.A_16) {
        for(i=0; i<49; i++) {
            cpg_update_A_16(i, CPG_Params_cpp.A_16[i]);
        }
    }
    if (CPG_Updated_cpp.B_16) {
        for(i=0; i<28; i++) {
            cpg_update_B_16(i, CPG_Params_cpp.B_16[i]);
        }
    }
    if (CPG_Updated_cpp.y_16) {
        for(i=0; i<7; i++) {
            cpg_update_y_16(i, CPG_Params_cpp.y_16[i]);
        }
    }
    if (CPG_Updated_cpp.A_17) {
        for(i=0; i<49; i++) {
            cpg_update_A_17(i, CPG_Params_cpp.A_17[i]);
        }
    }
    if (CPG_Updated_cpp.B_17) {
        for(i=0; i<28; i++) {
            cpg_update_B_17(i, CPG_Params_cpp.B_17[i]);
        }
    }
    if (CPG_Updated_cpp.y_17) {
        for(i=0; i<7; i++) {
            cpg_update_y_17(i, CPG_Params_cpp.y_17[i]);
        }
    }
    if (CPG_Updated_cpp.A_18) {
        for(i=0; i<49; i++) {
            cpg_update_A_18(i, CPG_Params_cpp.A_18[i]);
        }
    }
    if (CPG_Updated_cpp.B_18) {
        for(i=0; i<28; i++) {
            cpg_update_B_18(i, CPG_Params_cpp.B_18[i]);
        }
    }
    if (CPG_Updated_cpp.y_18) {
        for(i=0; i<7; i++) {
            cpg_update_y_18(i, CPG_Params_cpp.y_18[i]);
        }
    }
    if (CPG_Updated_cpp.A_19) {
        for(i=0; i<49; i++) {
            cpg_update_A_19(i, CPG_Params_cpp.A_19[i]);
        }
    }
    if (CPG_Updated_cpp.B_19) {
        for(i=0; i<28; i++) {
            cpg_update_B_19(i, CPG_Params_cpp.B_19[i]);
        }
    }
    if (CPG_Updated_cpp.y_19) {
        for(i=0; i<7; i++) {
            cpg_update_y_19(i, CPG_Params_cpp.y_19[i]);
        }
    }
    if (CPG_Updated_cpp.A_20) {
        for(i=0; i<49; i++) {
            cpg_update_A_20(i, CPG_Params_cpp.A_20[i]);
        }
    }
    if (CPG_Updated_cpp.B_20) {
        for(i=0; i<28; i++) {
            cpg_update_B_20(i, CPG_Params_cpp.B_20[i]);
        }
    }
    if (CPG_Updated_cpp.y_20) {
        for(i=0; i<7; i++) {
            cpg_update_y_20(i, CPG_Params_cpp.y_20[i]);
        }
    }
    if (CPG_Updated_cpp.A_21) {
        for(i=0; i<49; i++) {
            cpg_update_A_21(i, CPG_Params_cpp.A_21[i]);
        }
    }
    if (CPG_Updated_cpp.B_21) {
        for(i=0; i<28; i++) {
            cpg_update_B_21(i, CPG_Params_cpp.B_21[i]);
        }
    }
    if (CPG_Updated_cpp.y_21) {
        for(i=0; i<7; i++) {
            cpg_update_y_21(i, CPG_Params_cpp.y_21[i]);
        }
    }
    if (CPG_Updated_cpp.A_22) {
        for(i=0; i<49; i++) {
            cpg_update_A_22(i, CPG_Params_cpp.A_22[i]);
        }
    }
    if (CPG_Updated_cpp.B_22) {
        for(i=0; i<28; i++) {
            cpg_update_B_22(i, CPG_Params_cpp.B_22[i]);
        }
    }
    if (CPG_Updated_cpp.y_22) {
        for(i=0; i<7; i++) {
            cpg_update_y_22(i, CPG_Params_cpp.y_22[i]);
        }
    }
    if (CPG_Updated_cpp.A_23) {
        for(i=0; i<49; i++) {
            cpg_update_A_23(i, CPG_Params_cpp.A_23[i]);
        }
    }
    if (CPG_Updated_cpp.B_23) {
        for(i=0; i<28; i++) {
            cpg_update_B_23(i, CPG_Params_cpp.B_23[i]);
        }
    }
    if (CPG_Updated_cpp.y_23) {
        for(i=0; i<7; i++) {
            cpg_update_y_23(i, CPG_Params_cpp.y_23[i]);
        }
    }
    if (CPG_Updated_cpp.A_24) {
        for(i=0; i<49; i++) {
            cpg_update_A_24(i, CPG_Params_cpp.A_24[i]);
        }
    }
    if (CPG_Updated_cpp.B_24) {
        for(i=0; i<28; i++) {
            cpg_update_B_24(i, CPG_Params_cpp.B_24[i]);
        }
    }
    if (CPG_Updated_cpp.y_24) {
        for(i=0; i<7; i++) {
            cpg_update_y_24(i, CPG_Params_cpp.y_24[i]);
        }
    }
    if (CPG_Updated_cpp.A_25) {
        for(i=0; i<49; i++) {
            cpg_update_A_25(i, CPG_Params_cpp.A_25[i]);
        }
    }
    if (CPG_Updated_cpp.B_25) {
        for(i=0; i<28; i++) {
            cpg_update_B_25(i, CPG_Params_cpp.B_25[i]);
        }
    }
    if (CPG_Updated_cpp.y_25) {
        for(i=0; i<7; i++) {
            cpg_update_y_25(i, CPG_Params_cpp.y_25[i]);
        }
    }
    if (CPG_Updated_cpp.A_26) {
        for(i=0; i<49; i++) {
            cpg_update_A_26(i, CPG_Params_cpp.A_26[i]);
        }
    }
    if (CPG_Updated_cpp.B_26) {
        for(i=0; i<28; i++) {
            cpg_update_B_26(i, CPG_Params_cpp.B_26[i]);
        }
    }
    if (CPG_Updated_cpp.y_26) {
        for(i=0; i<7; i++) {
            cpg_update_y_26(i, CPG_Params_cpp.y_26[i]);
        }
    }
    if (CPG_Updated_cpp.A_27) {
        for(i=0; i<49; i++) {
            cpg_update_A_27(i, CPG_Params_cpp.A_27[i]);
        }
    }
    if (CPG_Updated_cpp.B_27) {
        for(i=0; i<28; i++) {
            cpg_update_B_27(i, CPG_Params_cpp.B_27[i]);
        }
    }
    if (CPG_Updated_cpp.y_27) {
        for(i=0; i<7; i++) {
            cpg_update_y_27(i, CPG_Params_cpp.y_27[i]);
        }
    }
    if (CPG_Updated_cpp.A_28) {
        for(i=0; i<49; i++) {
            cpg_update_A_28(i, CPG_Params_cpp.A_28[i]);
        }
    }
    if (CPG_Updated_cpp.B_28) {
        for(i=0; i<28; i++) {
            cpg_update_B_28(i, CPG_Params_cpp.B_28[i]);
        }
    }
    if (CPG_Updated_cpp.y_28) {
        for(i=0; i<7; i++) {
            cpg_update_y_28(i, CPG_Params_cpp.y_28[i]);
        }
    }
    if (CPG_Updated_cpp.A_29) {
        for(i=0; i<49; i++) {
            cpg_update_A_29(i, CPG_Params_cpp.A_29[i]);
        }
    }
    if (CPG_Updated_cpp.B_29) {
        for(i=0; i<28; i++) {
            cpg_update_B_29(i, CPG_Params_cpp.B_29[i]);
        }
    }
    if (CPG_Updated_cpp.y_29) {
        for(i=0; i<7; i++) {
            cpg_update_y_29(i, CPG_Params_cpp.y_29[i]);
        }
    }
    if (CPG_Updated_cpp.ox_0) {
        for(i=0; i<7; i++) {
            cpg_update_ox_0(i, CPG_Params_cpp.ox_0[i]);
        }
    }
    if (CPG_Updated_cpp.ou_0) {
        for(i=0; i<4; i++) {
            cpg_update_ou_0(i, CPG_Params_cpp.ou_0[i]);
        }
    }
    if (CPG_Updated_cpp.etta) {
        cpg_update_etta(CPG_Params_cpp.etta);
    }
    if (CPG_Updated_cpp.ox_1) {
        for(i=0; i<7; i++) {
            cpg_update_ox_1(i, CPG_Params_cpp.ox_1[i]);
        }
    }
    if (CPG_Updated_cpp.ou_1) {
        for(i=0; i<4; i++) {
            cpg_update_ou_1(i, CPG_Params_cpp.ou_1[i]);
        }
    }
    if (CPG_Updated_cpp.ox_2) {
        for(i=0; i<7; i++) {
            cpg_update_ox_2(i, CPG_Params_cpp.ox_2[i]);
        }
    }
    if (CPG_Updated_cpp.ou_2) {
        for(i=0; i<4; i++) {
            cpg_update_ou_2(i, CPG_Params_cpp.ou_2[i]);
        }
    }
    if (CPG_Updated_cpp.ox_3) {
        for(i=0; i<7; i++) {
            cpg_update_ox_3(i, CPG_Params_cpp.ox_3[i]);
        }
    }
    if (CPG_Updated_cpp.ou_3) {
        for(i=0; i<4; i++) {
            cpg_update_ou_3(i, CPG_Params_cpp.ou_3[i]);
        }
    }
    if (CPG_Updated_cpp.ox_4) {
        for(i=0; i<7; i++) {
            cpg_update_ox_4(i, CPG_Params_cpp.ox_4[i]);
        }
    }
    if (CPG_Updated_cpp.ou_4) {
        for(i=0; i<4; i++) {
            cpg_update_ou_4(i, CPG_Params_cpp.ou_4[i]);
        }
    }
    if (CPG_Updated_cpp.ox_5) {
        for(i=0; i<7; i++) {
            cpg_update_ox_5(i, CPG_Params_cpp.ox_5[i]);
        }
    }
    if (CPG_Updated_cpp.ou_5) {
        for(i=0; i<4; i++) {
            cpg_update_ou_5(i, CPG_Params_cpp.ou_5[i]);
        }
    }
    if (CPG_Updated_cpp.ox_6) {
        for(i=0; i<7; i++) {
            cpg_update_ox_6(i, CPG_Params_cpp.ox_6[i]);
        }
    }
    if (CPG_Updated_cpp.ou_6) {
        for(i=0; i<4; i++) {
            cpg_update_ou_6(i, CPG_Params_cpp.ou_6[i]);
        }
    }
    if (CPG_Updated_cpp.ox_7) {
        for(i=0; i<7; i++) {
            cpg_update_ox_7(i, CPG_Params_cpp.ox_7[i]);
        }
    }
    if (CPG_Updated_cpp.ou_7) {
        for(i=0; i<4; i++) {
            cpg_update_ou_7(i, CPG_Params_cpp.ou_7[i]);
        }
    }
    if (CPG_Updated_cpp.ox_8) {
        for(i=0; i<7; i++) {
            cpg_update_ox_8(i, CPG_Params_cpp.ox_8[i]);
        }
    }
    if (CPG_Updated_cpp.ou_8) {
        for(i=0; i<4; i++) {
            cpg_update_ou_8(i, CPG_Params_cpp.ou_8[i]);
        }
    }
    if (CPG_Updated_cpp.ox_9) {
        for(i=0; i<7; i++) {
            cpg_update_ox_9(i, CPG_Params_cpp.ox_9[i]);
        }
    }
    if (CPG_Updated_cpp.ou_9) {
        for(i=0; i<4; i++) {
            cpg_update_ou_9(i, CPG_Params_cpp.ou_9[i]);
        }
    }
    if (CPG_Updated_cpp.ox_10) {
        for(i=0; i<7; i++) {
            cpg_update_ox_10(i, CPG_Params_cpp.ox_10[i]);
        }
    }
    if (CPG_Updated_cpp.ou_10) {
        for(i=0; i<4; i++) {
            cpg_update_ou_10(i, CPG_Params_cpp.ou_10[i]);
        }
    }
    if (CPG_Updated_cpp.ox_11) {
        for(i=0; i<7; i++) {
            cpg_update_ox_11(i, CPG_Params_cpp.ox_11[i]);
        }
    }
    if (CPG_Updated_cpp.ou_11) {
        for(i=0; i<4; i++) {
            cpg_update_ou_11(i, CPG_Params_cpp.ou_11[i]);
        }
    }
    if (CPG_Updated_cpp.ox_12) {
        for(i=0; i<7; i++) {
            cpg_update_ox_12(i, CPG_Params_cpp.ox_12[i]);
        }
    }
    if (CPG_Updated_cpp.ou_12) {
        for(i=0; i<4; i++) {
            cpg_update_ou_12(i, CPG_Params_cpp.ou_12[i]);
        }
    }
    if (CPG_Updated_cpp.ox_13) {
        for(i=0; i<7; i++) {
            cpg_update_ox_13(i, CPG_Params_cpp.ox_13[i]);
        }
    }
    if (CPG_Updated_cpp.ou_13) {
        for(i=0; i<4; i++) {
            cpg_update_ou_13(i, CPG_Params_cpp.ou_13[i]);
        }
    }
    if (CPG_Updated_cpp.ox_14) {
        for(i=0; i<7; i++) {
            cpg_update_ox_14(i, CPG_Params_cpp.ox_14[i]);
        }
    }
    if (CPG_Updated_cpp.ou_14) {
        for(i=0; i<4; i++) {
            cpg_update_ou_14(i, CPG_Params_cpp.ou_14[i]);
        }
    }
    if (CPG_Updated_cpp.ox_15) {
        for(i=0; i<7; i++) {
            cpg_update_ox_15(i, CPG_Params_cpp.ox_15[i]);
        }
    }
    if (CPG_Updated_cpp.ou_15) {
        for(i=0; i<4; i++) {
            cpg_update_ou_15(i, CPG_Params_cpp.ou_15[i]);
        }
    }
    if (CPG_Updated_cpp.ox_16) {
        for(i=0; i<7; i++) {
            cpg_update_ox_16(i, CPG_Params_cpp.ox_16[i]);
        }
    }
    if (CPG_Updated_cpp.ou_16) {
        for(i=0; i<4; i++) {
            cpg_update_ou_16(i, CPG_Params_cpp.ou_16[i]);
        }
    }
    if (CPG_Updated_cpp.ox_17) {
        for(i=0; i<7; i++) {
            cpg_update_ox_17(i, CPG_Params_cpp.ox_17[i]);
        }
    }
    if (CPG_Updated_cpp.ou_17) {
        for(i=0; i<4; i++) {
            cpg_update_ou_17(i, CPG_Params_cpp.ou_17[i]);
        }
    }
    if (CPG_Updated_cpp.ox_18) {
        for(i=0; i<7; i++) {
            cpg_update_ox_18(i, CPG_Params_cpp.ox_18[i]);
        }
    }
    if (CPG_Updated_cpp.ou_18) {
        for(i=0; i<4; i++) {
            cpg_update_ou_18(i, CPG_Params_cpp.ou_18[i]);
        }
    }
    if (CPG_Updated_cpp.ox_19) {
        for(i=0; i<7; i++) {
            cpg_update_ox_19(i, CPG_Params_cpp.ox_19[i]);
        }
    }
    if (CPG_Updated_cpp.ou_19) {
        for(i=0; i<4; i++) {
            cpg_update_ou_19(i, CPG_Params_cpp.ou_19[i]);
        }
    }
    if (CPG_Updated_cpp.ox_20) {
        for(i=0; i<7; i++) {
            cpg_update_ox_20(i, CPG_Params_cpp.ox_20[i]);
        }
    }
    if (CPG_Updated_cpp.ou_20) {
        for(i=0; i<4; i++) {
            cpg_update_ou_20(i, CPG_Params_cpp.ou_20[i]);
        }
    }
    if (CPG_Updated_cpp.ox_21) {
        for(i=0; i<7; i++) {
            cpg_update_ox_21(i, CPG_Params_cpp.ox_21[i]);
        }
    }
    if (CPG_Updated_cpp.ou_21) {
        for(i=0; i<4; i++) {
            cpg_update_ou_21(i, CPG_Params_cpp.ou_21[i]);
        }
    }
    if (CPG_Updated_cpp.ox_22) {
        for(i=0; i<7; i++) {
            cpg_update_ox_22(i, CPG_Params_cpp.ox_22[i]);
        }
    }
    if (CPG_Updated_cpp.ou_22) {
        for(i=0; i<4; i++) {
            cpg_update_ou_22(i, CPG_Params_cpp.ou_22[i]);
        }
    }
    if (CPG_Updated_cpp.ox_23) {
        for(i=0; i<7; i++) {
            cpg_update_ox_23(i, CPG_Params_cpp.ox_23[i]);
        }
    }
    if (CPG_Updated_cpp.ou_23) {
        for(i=0; i<4; i++) {
            cpg_update_ou_23(i, CPG_Params_cpp.ou_23[i]);
        }
    }
    if (CPG_Updated_cpp.ox_24) {
        for(i=0; i<7; i++) {
            cpg_update_ox_24(i, CPG_Params_cpp.ox_24[i]);
        }
    }
    if (CPG_Updated_cpp.ou_24) {
        for(i=0; i<4; i++) {
            cpg_update_ou_24(i, CPG_Params_cpp.ou_24[i]);
        }
    }
    if (CPG_Updated_cpp.ox_25) {
        for(i=0; i<7; i++) {
            cpg_update_ox_25(i, CPG_Params_cpp.ox_25[i]);
        }
    }
    if (CPG_Updated_cpp.ou_25) {
        for(i=0; i<4; i++) {
            cpg_update_ou_25(i, CPG_Params_cpp.ou_25[i]);
        }
    }
    if (CPG_Updated_cpp.ox_26) {
        for(i=0; i<7; i++) {
            cpg_update_ox_26(i, CPG_Params_cpp.ox_26[i]);
        }
    }
    if (CPG_Updated_cpp.ou_26) {
        for(i=0; i<4; i++) {
            cpg_update_ou_26(i, CPG_Params_cpp.ou_26[i]);
        }
    }
    if (CPG_Updated_cpp.ox_27) {
        for(i=0; i<7; i++) {
            cpg_update_ox_27(i, CPG_Params_cpp.ox_27[i]);
        }
    }
    if (CPG_Updated_cpp.ou_27) {
        for(i=0; i<4; i++) {
            cpg_update_ou_27(i, CPG_Params_cpp.ou_27[i]);
        }
    }
    if (CPG_Updated_cpp.ox_28) {
        for(i=0; i<7; i++) {
            cpg_update_ox_28(i, CPG_Params_cpp.ox_28[i]);
        }
    }
    if (CPG_Updated_cpp.ou_28) {
        for(i=0; i<4; i++) {
            cpg_update_ou_28(i, CPG_Params_cpp.ou_28[i]);
        }
    }
    if (CPG_Updated_cpp.ox_29) {
        for(i=0; i<7; i++) {
            cpg_update_ox_29(i, CPG_Params_cpp.ox_29[i]);
        }
    }
    if (CPG_Updated_cpp.ou_29) {
        for(i=0; i<4; i++) {
            cpg_update_ou_29(i, CPG_Params_cpp.ou_29[i]);
        }
    }
    if (CPG_Updated_cpp.ox_30) {
        for(i=0; i<7; i++) {
            cpg_update_ox_30(i, CPG_Params_cpp.ox_30[i]);
        }
    }

    // Solve
    auto ASA_start = std::chrono::high_resolution_clock::now();
    cpg_solve();
    auto ASA_end = std::chrono::high_resolution_clock::now();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<120; i++) {
        CPG_Prim_cpp.u[i] = CPG_Prim.u[i];
    }
    for(i=0; i<210; i++) {
        CPG_Prim_cpp.vc[i] = CPG_Prim.vc[i];
    }
    for(i=0; i<217; i++) {
        CPG_Prim_cpp.x[i] = CPG_Prim.x[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d3[i] = CPG_Dual.d3[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d4[i] = CPG_Dual.d4[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d5[i] = CPG_Dual.d5[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d6[i] = CPG_Dual.d6[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d7[i] = CPG_Dual.d7[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d8[i] = CPG_Dual.d8[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d9[i] = CPG_Dual.d9[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d10[i] = CPG_Dual.d10[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d11[i] = CPG_Dual.d11[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d12[i] = CPG_Dual.d12[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d13[i] = CPG_Dual.d13[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d14[i] = CPG_Dual.d14[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d15[i] = CPG_Dual.d15[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d16[i] = CPG_Dual.d16[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d17[i] = CPG_Dual.d17[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d18[i] = CPG_Dual.d18[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d19[i] = CPG_Dual.d19[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d20[i] = CPG_Dual.d20[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d21[i] = CPG_Dual.d21[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d22[i] = CPG_Dual.d22[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d23[i] = CPG_Dual.d23[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d24[i] = CPG_Dual.d24[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d25[i] = CPG_Dual.d25[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d26[i] = CPG_Dual.d26[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d27[i] = CPG_Dual.d27[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d28[i] = CPG_Dual.d28[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d29[i] = CPG_Dual.d29[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d30[i] = CPG_Dual.d30[i];
    }
    for(i=0; i<7; i++) {
        CPG_Dual_cpp.d31[i] = CPG_Dual.d31[i];
    }
    CPG_Dual_cpp.d32 = CPG_Dual.d32;
    CPG_Dual_cpp.d33 = CPG_Dual.d33;
    CPG_Dual_cpp.d34 = CPG_Dual.d34;
    CPG_Dual_cpp.d35 = CPG_Dual.d35;
    CPG_Dual_cpp.d36 = CPG_Dual.d36;
    CPG_Dual_cpp.d37 = CPG_Dual.d37;
    CPG_Dual_cpp.d38 = CPG_Dual.d38;
    CPG_Dual_cpp.d39 = CPG_Dual.d39;
    CPG_Dual_cpp.d40 = CPG_Dual.d40;
    CPG_Dual_cpp.d41 = CPG_Dual.d41;
    CPG_Dual_cpp.d42 = CPG_Dual.d42;
    CPG_Dual_cpp.d43 = CPG_Dual.d43;
    CPG_Dual_cpp.d44 = CPG_Dual.d44;
    CPG_Dual_cpp.d45 = CPG_Dual.d45;
    CPG_Dual_cpp.d46 = CPG_Dual.d46;
    CPG_Dual_cpp.d47 = CPG_Dual.d47;
    CPG_Dual_cpp.d48 = CPG_Dual.d48;
    CPG_Dual_cpp.d49 = CPG_Dual.d49;
    CPG_Dual_cpp.d50 = CPG_Dual.d50;
    CPG_Dual_cpp.d51 = CPG_Dual.d51;
    CPG_Dual_cpp.d52 = CPG_Dual.d52;
    CPG_Dual_cpp.d53 = CPG_Dual.d53;
    CPG_Dual_cpp.d54 = CPG_Dual.d54;
    CPG_Dual_cpp.d55 = CPG_Dual.d55;
    CPG_Dual_cpp.d56 = CPG_Dual.d56;
    CPG_Dual_cpp.d57 = CPG_Dual.d57;
    CPG_Dual_cpp.d58 = CPG_Dual.d58;
    CPG_Dual_cpp.d59 = CPG_Dual.d59;
    CPG_Dual_cpp.d60 = CPG_Dual.d60;
    CPG_Dual_cpp.d61 = CPG_Dual.d61;
    CPG_Dual_cpp.d62 = CPG_Dual.d62;
    CPG_Dual_cpp.d63 = CPG_Dual.d63;
    CPG_Dual_cpp.d64 = CPG_Dual.d64;
    CPG_Dual_cpp.d65 = CPG_Dual.d65;
    CPG_Dual_cpp.d66 = CPG_Dual.d66;
    CPG_Dual_cpp.d67 = CPG_Dual.d67;
    CPG_Dual_cpp.d68 = CPG_Dual.d68;
    CPG_Dual_cpp.d69 = CPG_Dual.d69;
    CPG_Dual_cpp.d70 = CPG_Dual.d70;
    CPG_Dual_cpp.d71 = CPG_Dual.d71;
    CPG_Dual_cpp.d72 = CPG_Dual.d72;
    CPG_Dual_cpp.d73 = CPG_Dual.d73;
    CPG_Dual_cpp.d74 = CPG_Dual.d74;
    CPG_Dual_cpp.d75 = CPG_Dual.d75;
    CPG_Dual_cpp.d76 = CPG_Dual.d76;
    CPG_Dual_cpp.d77 = CPG_Dual.d77;
    CPG_Dual_cpp.d78 = CPG_Dual.d78;
    CPG_Dual_cpp.d79 = CPG_Dual.d79;
    CPG_Dual_cpp.d80 = CPG_Dual.d80;
    CPG_Dual_cpp.d81 = CPG_Dual.d81;
    CPG_Dual_cpp.d82 = CPG_Dual.d82;
    CPG_Dual_cpp.d83 = CPG_Dual.d83;
    CPG_Dual_cpp.d84 = CPG_Dual.d84;
    CPG_Dual_cpp.d85 = CPG_Dual.d85;
    CPG_Dual_cpp.d86 = CPG_Dual.d86;
    CPG_Dual_cpp.d87 = CPG_Dual.d87;
    CPG_Dual_cpp.d88 = CPG_Dual.d88;
    CPG_Dual_cpp.d89 = CPG_Dual.d89;
    CPG_Dual_cpp.d90 = CPG_Dual.d90;
    CPG_Dual_cpp.d91 = CPG_Dual.d91;
    CPG_Dual_cpp.d92 = CPG_Dual.d92;
    CPG_Dual_cpp.d93 = CPG_Dual.d93;
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d94[i] = CPG_Dual.d94[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d95[i] = CPG_Dual.d95[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d96[i] = CPG_Dual.d96[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d97[i] = CPG_Dual.d97[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d98[i] = CPG_Dual.d98[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d99[i] = CPG_Dual.d99[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d100[i] = CPG_Dual.d100[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d101[i] = CPG_Dual.d101[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d102[i] = CPG_Dual.d102[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d103[i] = CPG_Dual.d103[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d104[i] = CPG_Dual.d104[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d105[i] = CPG_Dual.d105[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d106[i] = CPG_Dual.d106[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d107[i] = CPG_Dual.d107[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d108[i] = CPG_Dual.d108[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d109[i] = CPG_Dual.d109[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d110[i] = CPG_Dual.d110[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d111[i] = CPG_Dual.d111[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d112[i] = CPG_Dual.d112[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d113[i] = CPG_Dual.d113[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d114[i] = CPG_Dual.d114[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d115[i] = CPG_Dual.d115[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d116[i] = CPG_Dual.d116[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d117[i] = CPG_Dual.d117[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d118[i] = CPG_Dual.d118[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d119[i] = CPG_Dual.d119[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d120[i] = CPG_Dual.d120[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d121[i] = CPG_Dual.d121[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d122[i] = CPG_Dual.d122[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d123[i] = CPG_Dual.d123[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d124[i] = CPG_Dual.d124[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d125[i] = CPG_Dual.d125[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d126[i] = CPG_Dual.d126[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d127[i] = CPG_Dual.d127[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d128[i] = CPG_Dual.d128[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d129[i] = CPG_Dual.d129[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d130[i] = CPG_Dual.d130[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d131[i] = CPG_Dual.d131[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d132[i] = CPG_Dual.d132[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d133[i] = CPG_Dual.d133[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d134[i] = CPG_Dual.d134[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d135[i] = CPG_Dual.d135[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d136[i] = CPG_Dual.d136[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d137[i] = CPG_Dual.d137[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d138[i] = CPG_Dual.d138[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d139[i] = CPG_Dual.d139[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d140[i] = CPG_Dual.d140[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d141[i] = CPG_Dual.d141[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d142[i] = CPG_Dual.d142[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d143[i] = CPG_Dual.d143[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d144[i] = CPG_Dual.d144[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d145[i] = CPG_Dual.d145[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d146[i] = CPG_Dual.d146[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d147[i] = CPG_Dual.d147[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d148[i] = CPG_Dual.d148[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d149[i] = CPG_Dual.d149[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d150[i] = CPG_Dual.d150[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d151[i] = CPG_Dual.d151[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d152[i] = CPG_Dual.d152[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d153[i] = CPG_Dual.d153[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d154[i] = CPG_Dual.d154[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d155[i] = CPG_Dual.d155[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d156[i] = CPG_Dual.d156[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d157[i] = CPG_Dual.d157[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d158[i] = CPG_Dual.d158[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d159[i] = CPG_Dual.d159[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d160[i] = CPG_Dual.d160[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d161[i] = CPG_Dual.d161[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d162[i] = CPG_Dual.d162[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d163[i] = CPG_Dual.d163[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d164[i] = CPG_Dual.d164[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d165[i] = CPG_Dual.d165[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d166[i] = CPG_Dual.d166[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d167[i] = CPG_Dual.d167[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d168[i] = CPG_Dual.d168[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d169[i] = CPG_Dual.d169[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d170[i] = CPG_Dual.d170[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d171[i] = CPG_Dual.d171[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d172[i] = CPG_Dual.d172[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d173[i] = CPG_Dual.d173[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d174[i] = CPG_Dual.d174[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d175[i] = CPG_Dual.d175[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d176[i] = CPG_Dual.d176[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d177[i] = CPG_Dual.d177[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d178[i] = CPG_Dual.d178[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d179[i] = CPG_Dual.d179[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d180[i] = CPG_Dual.d180[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d181[i] = CPG_Dual.d181[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d182[i] = CPG_Dual.d182[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d183[i] = CPG_Dual.d183[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d184[i] = CPG_Dual.d184[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d185[i] = CPG_Dual.d185[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d186[i] = CPG_Dual.d186[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d187[i] = CPG_Dual.d187[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d188[i] = CPG_Dual.d188[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d189[i] = CPG_Dual.d189[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d190[i] = CPG_Dual.d190[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d191[i] = CPG_Dual.d191[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d192[i] = CPG_Dual.d192[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d193[i] = CPG_Dual.d193[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d194[i] = CPG_Dual.d194[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d195[i] = CPG_Dual.d195[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d196[i] = CPG_Dual.d196[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d197[i] = CPG_Dual.d197[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d198[i] = CPG_Dual.d198[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d199[i] = CPG_Dual.d199[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d200[i] = CPG_Dual.d200[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d201[i] = CPG_Dual.d201[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d202[i] = CPG_Dual.d202[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d203[i] = CPG_Dual.d203[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d204[i] = CPG_Dual.d204[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d205[i] = CPG_Dual.d205[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d206[i] = CPG_Dual.d206[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d207[i] = CPG_Dual.d207[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d208[i] = CPG_Dual.d208[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d209[i] = CPG_Dual.d209[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d210[i] = CPG_Dual.d210[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d211[i] = CPG_Dual.d211[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d212[i] = CPG_Dual.d212[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d213[i] = CPG_Dual.d213[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d214[i] = CPG_Dual.d214[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d215[i] = CPG_Dual.d215[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d216[i] = CPG_Dual.d216[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d217[i] = CPG_Dual.d217[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d218[i] = CPG_Dual.d218[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d219[i] = CPG_Dual.d219[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d220[i] = CPG_Dual.d220[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d221[i] = CPG_Dual.d221[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d222[i] = CPG_Dual.d222[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d223[i] = CPG_Dual.d223[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d224[i] = CPG_Dual.d224[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d225[i] = CPG_Dual.d225[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d226[i] = CPG_Dual.d226[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d227[i] = CPG_Dual.d227[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d228[i] = CPG_Dual.d228[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d229[i] = CPG_Dual.d229[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d230[i] = CPG_Dual.d230[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d231[i] = CPG_Dual.d231[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d232[i] = CPG_Dual.d232[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d233[i] = CPG_Dual.d233[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d234[i] = CPG_Dual.d234[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d235[i] = CPG_Dual.d235[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d236[i] = CPG_Dual.d236[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d237[i] = CPG_Dual.d237[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d238[i] = CPG_Dual.d238[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d239[i] = CPG_Dual.d239[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d240[i] = CPG_Dual.d240[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d241[i] = CPG_Dual.d241[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d242[i] = CPG_Dual.d242[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d243[i] = CPG_Dual.d243[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d244[i] = CPG_Dual.d244[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d245[i] = CPG_Dual.d245[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d246[i] = CPG_Dual.d246[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d247[i] = CPG_Dual.d247[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d248[i] = CPG_Dual.d248[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d249[i] = CPG_Dual.d249[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d250[i] = CPG_Dual.d250[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d251[i] = CPG_Dual.d251[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d252[i] = CPG_Dual.d252[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d253[i] = CPG_Dual.d253[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d254[i] = CPG_Dual.d254[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d255[i] = CPG_Dual.d255[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d256[i] = CPG_Dual.d256[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d257[i] = CPG_Dual.d257[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d258[i] = CPG_Dual.d258[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d259[i] = CPG_Dual.d259[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d260[i] = CPG_Dual.d260[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d261[i] = CPG_Dual.d261[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d262[i] = CPG_Dual.d262[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d263[i] = CPG_Dual.d263[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d264[i] = CPG_Dual.d264[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d265[i] = CPG_Dual.d265[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d266[i] = CPG_Dual.d266[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d267[i] = CPG_Dual.d267[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d268[i] = CPG_Dual.d268[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d269[i] = CPG_Dual.d269[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d270[i] = CPG_Dual.d270[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d271[i] = CPG_Dual.d271[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d272[i] = CPG_Dual.d272[i];
    }
    for(i=0; i<4; i++) {
        CPG_Dual_cpp.d273[i] = CPG_Dual.d273[i];
    }
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    std::chrono::duration<double> elapsed = ASA_end - ASA_start;
    CPG_Info_cpp.time = elapsed.count();
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("start_pos", &CPG_Params_cpp_t::start_pos)
            .def_readwrite("end_pos", &CPG_Params_cpp_t::end_pos)
            .def_readwrite("A_0", &CPG_Params_cpp_t::A_0)
            .def_readwrite("B_0", &CPG_Params_cpp_t::B_0)
            .def_readwrite("y_0", &CPG_Params_cpp_t::y_0)
            .def_readwrite("A_1", &CPG_Params_cpp_t::A_1)
            .def_readwrite("B_1", &CPG_Params_cpp_t::B_1)
            .def_readwrite("y_1", &CPG_Params_cpp_t::y_1)
            .def_readwrite("A_2", &CPG_Params_cpp_t::A_2)
            .def_readwrite("B_2", &CPG_Params_cpp_t::B_2)
            .def_readwrite("y_2", &CPG_Params_cpp_t::y_2)
            .def_readwrite("A_3", &CPG_Params_cpp_t::A_3)
            .def_readwrite("B_3", &CPG_Params_cpp_t::B_3)
            .def_readwrite("y_3", &CPG_Params_cpp_t::y_3)
            .def_readwrite("A_4", &CPG_Params_cpp_t::A_4)
            .def_readwrite("B_4", &CPG_Params_cpp_t::B_4)
            .def_readwrite("y_4", &CPG_Params_cpp_t::y_4)
            .def_readwrite("A_5", &CPG_Params_cpp_t::A_5)
            .def_readwrite("B_5", &CPG_Params_cpp_t::B_5)
            .def_readwrite("y_5", &CPG_Params_cpp_t::y_5)
            .def_readwrite("A_6", &CPG_Params_cpp_t::A_6)
            .def_readwrite("B_6", &CPG_Params_cpp_t::B_6)
            .def_readwrite("y_6", &CPG_Params_cpp_t::y_6)
            .def_readwrite("A_7", &CPG_Params_cpp_t::A_7)
            .def_readwrite("B_7", &CPG_Params_cpp_t::B_7)
            .def_readwrite("y_7", &CPG_Params_cpp_t::y_7)
            .def_readwrite("A_8", &CPG_Params_cpp_t::A_8)
            .def_readwrite("B_8", &CPG_Params_cpp_t::B_8)
            .def_readwrite("y_8", &CPG_Params_cpp_t::y_8)
            .def_readwrite("A_9", &CPG_Params_cpp_t::A_9)
            .def_readwrite("B_9", &CPG_Params_cpp_t::B_9)
            .def_readwrite("y_9", &CPG_Params_cpp_t::y_9)
            .def_readwrite("A_10", &CPG_Params_cpp_t::A_10)
            .def_readwrite("B_10", &CPG_Params_cpp_t::B_10)
            .def_readwrite("y_10", &CPG_Params_cpp_t::y_10)
            .def_readwrite("A_11", &CPG_Params_cpp_t::A_11)
            .def_readwrite("B_11", &CPG_Params_cpp_t::B_11)
            .def_readwrite("y_11", &CPG_Params_cpp_t::y_11)
            .def_readwrite("A_12", &CPG_Params_cpp_t::A_12)
            .def_readwrite("B_12", &CPG_Params_cpp_t::B_12)
            .def_readwrite("y_12", &CPG_Params_cpp_t::y_12)
            .def_readwrite("A_13", &CPG_Params_cpp_t::A_13)
            .def_readwrite("B_13", &CPG_Params_cpp_t::B_13)
            .def_readwrite("y_13", &CPG_Params_cpp_t::y_13)
            .def_readwrite("A_14", &CPG_Params_cpp_t::A_14)
            .def_readwrite("B_14", &CPG_Params_cpp_t::B_14)
            .def_readwrite("y_14", &CPG_Params_cpp_t::y_14)
            .def_readwrite("A_15", &CPG_Params_cpp_t::A_15)
            .def_readwrite("B_15", &CPG_Params_cpp_t::B_15)
            .def_readwrite("y_15", &CPG_Params_cpp_t::y_15)
            .def_readwrite("A_16", &CPG_Params_cpp_t::A_16)
            .def_readwrite("B_16", &CPG_Params_cpp_t::B_16)
            .def_readwrite("y_16", &CPG_Params_cpp_t::y_16)
            .def_readwrite("A_17", &CPG_Params_cpp_t::A_17)
            .def_readwrite("B_17", &CPG_Params_cpp_t::B_17)
            .def_readwrite("y_17", &CPG_Params_cpp_t::y_17)
            .def_readwrite("A_18", &CPG_Params_cpp_t::A_18)
            .def_readwrite("B_18", &CPG_Params_cpp_t::B_18)
            .def_readwrite("y_18", &CPG_Params_cpp_t::y_18)
            .def_readwrite("A_19", &CPG_Params_cpp_t::A_19)
            .def_readwrite("B_19", &CPG_Params_cpp_t::B_19)
            .def_readwrite("y_19", &CPG_Params_cpp_t::y_19)
            .def_readwrite("A_20", &CPG_Params_cpp_t::A_20)
            .def_readwrite("B_20", &CPG_Params_cpp_t::B_20)
            .def_readwrite("y_20", &CPG_Params_cpp_t::y_20)
            .def_readwrite("A_21", &CPG_Params_cpp_t::A_21)
            .def_readwrite("B_21", &CPG_Params_cpp_t::B_21)
            .def_readwrite("y_21", &CPG_Params_cpp_t::y_21)
            .def_readwrite("A_22", &CPG_Params_cpp_t::A_22)
            .def_readwrite("B_22", &CPG_Params_cpp_t::B_22)
            .def_readwrite("y_22", &CPG_Params_cpp_t::y_22)
            .def_readwrite("A_23", &CPG_Params_cpp_t::A_23)
            .def_readwrite("B_23", &CPG_Params_cpp_t::B_23)
            .def_readwrite("y_23", &CPG_Params_cpp_t::y_23)
            .def_readwrite("A_24", &CPG_Params_cpp_t::A_24)
            .def_readwrite("B_24", &CPG_Params_cpp_t::B_24)
            .def_readwrite("y_24", &CPG_Params_cpp_t::y_24)
            .def_readwrite("A_25", &CPG_Params_cpp_t::A_25)
            .def_readwrite("B_25", &CPG_Params_cpp_t::B_25)
            .def_readwrite("y_25", &CPG_Params_cpp_t::y_25)
            .def_readwrite("A_26", &CPG_Params_cpp_t::A_26)
            .def_readwrite("B_26", &CPG_Params_cpp_t::B_26)
            .def_readwrite("y_26", &CPG_Params_cpp_t::y_26)
            .def_readwrite("A_27", &CPG_Params_cpp_t::A_27)
            .def_readwrite("B_27", &CPG_Params_cpp_t::B_27)
            .def_readwrite("y_27", &CPG_Params_cpp_t::y_27)
            .def_readwrite("A_28", &CPG_Params_cpp_t::A_28)
            .def_readwrite("B_28", &CPG_Params_cpp_t::B_28)
            .def_readwrite("y_28", &CPG_Params_cpp_t::y_28)
            .def_readwrite("A_29", &CPG_Params_cpp_t::A_29)
            .def_readwrite("B_29", &CPG_Params_cpp_t::B_29)
            .def_readwrite("y_29", &CPG_Params_cpp_t::y_29)
            .def_readwrite("ox_0", &CPG_Params_cpp_t::ox_0)
            .def_readwrite("ou_0", &CPG_Params_cpp_t::ou_0)
            .def_readwrite("etta", &CPG_Params_cpp_t::etta)
            .def_readwrite("ox_1", &CPG_Params_cpp_t::ox_1)
            .def_readwrite("ou_1", &CPG_Params_cpp_t::ou_1)
            .def_readwrite("ox_2", &CPG_Params_cpp_t::ox_2)
            .def_readwrite("ou_2", &CPG_Params_cpp_t::ou_2)
            .def_readwrite("ox_3", &CPG_Params_cpp_t::ox_3)
            .def_readwrite("ou_3", &CPG_Params_cpp_t::ou_3)
            .def_readwrite("ox_4", &CPG_Params_cpp_t::ox_4)
            .def_readwrite("ou_4", &CPG_Params_cpp_t::ou_4)
            .def_readwrite("ox_5", &CPG_Params_cpp_t::ox_5)
            .def_readwrite("ou_5", &CPG_Params_cpp_t::ou_5)
            .def_readwrite("ox_6", &CPG_Params_cpp_t::ox_6)
            .def_readwrite("ou_6", &CPG_Params_cpp_t::ou_6)
            .def_readwrite("ox_7", &CPG_Params_cpp_t::ox_7)
            .def_readwrite("ou_7", &CPG_Params_cpp_t::ou_7)
            .def_readwrite("ox_8", &CPG_Params_cpp_t::ox_8)
            .def_readwrite("ou_8", &CPG_Params_cpp_t::ou_8)
            .def_readwrite("ox_9", &CPG_Params_cpp_t::ox_9)
            .def_readwrite("ou_9", &CPG_Params_cpp_t::ou_9)
            .def_readwrite("ox_10", &CPG_Params_cpp_t::ox_10)
            .def_readwrite("ou_10", &CPG_Params_cpp_t::ou_10)
            .def_readwrite("ox_11", &CPG_Params_cpp_t::ox_11)
            .def_readwrite("ou_11", &CPG_Params_cpp_t::ou_11)
            .def_readwrite("ox_12", &CPG_Params_cpp_t::ox_12)
            .def_readwrite("ou_12", &CPG_Params_cpp_t::ou_12)
            .def_readwrite("ox_13", &CPG_Params_cpp_t::ox_13)
            .def_readwrite("ou_13", &CPG_Params_cpp_t::ou_13)
            .def_readwrite("ox_14", &CPG_Params_cpp_t::ox_14)
            .def_readwrite("ou_14", &CPG_Params_cpp_t::ou_14)
            .def_readwrite("ox_15", &CPG_Params_cpp_t::ox_15)
            .def_readwrite("ou_15", &CPG_Params_cpp_t::ou_15)
            .def_readwrite("ox_16", &CPG_Params_cpp_t::ox_16)
            .def_readwrite("ou_16", &CPG_Params_cpp_t::ou_16)
            .def_readwrite("ox_17", &CPG_Params_cpp_t::ox_17)
            .def_readwrite("ou_17", &CPG_Params_cpp_t::ou_17)
            .def_readwrite("ox_18", &CPG_Params_cpp_t::ox_18)
            .def_readwrite("ou_18", &CPG_Params_cpp_t::ou_18)
            .def_readwrite("ox_19", &CPG_Params_cpp_t::ox_19)
            .def_readwrite("ou_19", &CPG_Params_cpp_t::ou_19)
            .def_readwrite("ox_20", &CPG_Params_cpp_t::ox_20)
            .def_readwrite("ou_20", &CPG_Params_cpp_t::ou_20)
            .def_readwrite("ox_21", &CPG_Params_cpp_t::ox_21)
            .def_readwrite("ou_21", &CPG_Params_cpp_t::ou_21)
            .def_readwrite("ox_22", &CPG_Params_cpp_t::ox_22)
            .def_readwrite("ou_22", &CPG_Params_cpp_t::ou_22)
            .def_readwrite("ox_23", &CPG_Params_cpp_t::ox_23)
            .def_readwrite("ou_23", &CPG_Params_cpp_t::ou_23)
            .def_readwrite("ox_24", &CPG_Params_cpp_t::ox_24)
            .def_readwrite("ou_24", &CPG_Params_cpp_t::ou_24)
            .def_readwrite("ox_25", &CPG_Params_cpp_t::ox_25)
            .def_readwrite("ou_25", &CPG_Params_cpp_t::ou_25)
            .def_readwrite("ox_26", &CPG_Params_cpp_t::ox_26)
            .def_readwrite("ou_26", &CPG_Params_cpp_t::ou_26)
            .def_readwrite("ox_27", &CPG_Params_cpp_t::ox_27)
            .def_readwrite("ou_27", &CPG_Params_cpp_t::ou_27)
            .def_readwrite("ox_28", &CPG_Params_cpp_t::ox_28)
            .def_readwrite("ou_28", &CPG_Params_cpp_t::ou_28)
            .def_readwrite("ox_29", &CPG_Params_cpp_t::ox_29)
            .def_readwrite("ou_29", &CPG_Params_cpp_t::ou_29)
            .def_readwrite("ox_30", &CPG_Params_cpp_t::ox_30)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("start_pos", &CPG_Updated_cpp_t::start_pos)
            .def_readwrite("end_pos", &CPG_Updated_cpp_t::end_pos)
            .def_readwrite("A_0", &CPG_Updated_cpp_t::A_0)
            .def_readwrite("B_0", &CPG_Updated_cpp_t::B_0)
            .def_readwrite("y_0", &CPG_Updated_cpp_t::y_0)
            .def_readwrite("A_1", &CPG_Updated_cpp_t::A_1)
            .def_readwrite("B_1", &CPG_Updated_cpp_t::B_1)
            .def_readwrite("y_1", &CPG_Updated_cpp_t::y_1)
            .def_readwrite("A_2", &CPG_Updated_cpp_t::A_2)
            .def_readwrite("B_2", &CPG_Updated_cpp_t::B_2)
            .def_readwrite("y_2", &CPG_Updated_cpp_t::y_2)
            .def_readwrite("A_3", &CPG_Updated_cpp_t::A_3)
            .def_readwrite("B_3", &CPG_Updated_cpp_t::B_3)
            .def_readwrite("y_3", &CPG_Updated_cpp_t::y_3)
            .def_readwrite("A_4", &CPG_Updated_cpp_t::A_4)
            .def_readwrite("B_4", &CPG_Updated_cpp_t::B_4)
            .def_readwrite("y_4", &CPG_Updated_cpp_t::y_4)
            .def_readwrite("A_5", &CPG_Updated_cpp_t::A_5)
            .def_readwrite("B_5", &CPG_Updated_cpp_t::B_5)
            .def_readwrite("y_5", &CPG_Updated_cpp_t::y_5)
            .def_readwrite("A_6", &CPG_Updated_cpp_t::A_6)
            .def_readwrite("B_6", &CPG_Updated_cpp_t::B_6)
            .def_readwrite("y_6", &CPG_Updated_cpp_t::y_6)
            .def_readwrite("A_7", &CPG_Updated_cpp_t::A_7)
            .def_readwrite("B_7", &CPG_Updated_cpp_t::B_7)
            .def_readwrite("y_7", &CPG_Updated_cpp_t::y_7)
            .def_readwrite("A_8", &CPG_Updated_cpp_t::A_8)
            .def_readwrite("B_8", &CPG_Updated_cpp_t::B_8)
            .def_readwrite("y_8", &CPG_Updated_cpp_t::y_8)
            .def_readwrite("A_9", &CPG_Updated_cpp_t::A_9)
            .def_readwrite("B_9", &CPG_Updated_cpp_t::B_9)
            .def_readwrite("y_9", &CPG_Updated_cpp_t::y_9)
            .def_readwrite("A_10", &CPG_Updated_cpp_t::A_10)
            .def_readwrite("B_10", &CPG_Updated_cpp_t::B_10)
            .def_readwrite("y_10", &CPG_Updated_cpp_t::y_10)
            .def_readwrite("A_11", &CPG_Updated_cpp_t::A_11)
            .def_readwrite("B_11", &CPG_Updated_cpp_t::B_11)
            .def_readwrite("y_11", &CPG_Updated_cpp_t::y_11)
            .def_readwrite("A_12", &CPG_Updated_cpp_t::A_12)
            .def_readwrite("B_12", &CPG_Updated_cpp_t::B_12)
            .def_readwrite("y_12", &CPG_Updated_cpp_t::y_12)
            .def_readwrite("A_13", &CPG_Updated_cpp_t::A_13)
            .def_readwrite("B_13", &CPG_Updated_cpp_t::B_13)
            .def_readwrite("y_13", &CPG_Updated_cpp_t::y_13)
            .def_readwrite("A_14", &CPG_Updated_cpp_t::A_14)
            .def_readwrite("B_14", &CPG_Updated_cpp_t::B_14)
            .def_readwrite("y_14", &CPG_Updated_cpp_t::y_14)
            .def_readwrite("A_15", &CPG_Updated_cpp_t::A_15)
            .def_readwrite("B_15", &CPG_Updated_cpp_t::B_15)
            .def_readwrite("y_15", &CPG_Updated_cpp_t::y_15)
            .def_readwrite("A_16", &CPG_Updated_cpp_t::A_16)
            .def_readwrite("B_16", &CPG_Updated_cpp_t::B_16)
            .def_readwrite("y_16", &CPG_Updated_cpp_t::y_16)
            .def_readwrite("A_17", &CPG_Updated_cpp_t::A_17)
            .def_readwrite("B_17", &CPG_Updated_cpp_t::B_17)
            .def_readwrite("y_17", &CPG_Updated_cpp_t::y_17)
            .def_readwrite("A_18", &CPG_Updated_cpp_t::A_18)
            .def_readwrite("B_18", &CPG_Updated_cpp_t::B_18)
            .def_readwrite("y_18", &CPG_Updated_cpp_t::y_18)
            .def_readwrite("A_19", &CPG_Updated_cpp_t::A_19)
            .def_readwrite("B_19", &CPG_Updated_cpp_t::B_19)
            .def_readwrite("y_19", &CPG_Updated_cpp_t::y_19)
            .def_readwrite("A_20", &CPG_Updated_cpp_t::A_20)
            .def_readwrite("B_20", &CPG_Updated_cpp_t::B_20)
            .def_readwrite("y_20", &CPG_Updated_cpp_t::y_20)
            .def_readwrite("A_21", &CPG_Updated_cpp_t::A_21)
            .def_readwrite("B_21", &CPG_Updated_cpp_t::B_21)
            .def_readwrite("y_21", &CPG_Updated_cpp_t::y_21)
            .def_readwrite("A_22", &CPG_Updated_cpp_t::A_22)
            .def_readwrite("B_22", &CPG_Updated_cpp_t::B_22)
            .def_readwrite("y_22", &CPG_Updated_cpp_t::y_22)
            .def_readwrite("A_23", &CPG_Updated_cpp_t::A_23)
            .def_readwrite("B_23", &CPG_Updated_cpp_t::B_23)
            .def_readwrite("y_23", &CPG_Updated_cpp_t::y_23)
            .def_readwrite("A_24", &CPG_Updated_cpp_t::A_24)
            .def_readwrite("B_24", &CPG_Updated_cpp_t::B_24)
            .def_readwrite("y_24", &CPG_Updated_cpp_t::y_24)
            .def_readwrite("A_25", &CPG_Updated_cpp_t::A_25)
            .def_readwrite("B_25", &CPG_Updated_cpp_t::B_25)
            .def_readwrite("y_25", &CPG_Updated_cpp_t::y_25)
            .def_readwrite("A_26", &CPG_Updated_cpp_t::A_26)
            .def_readwrite("B_26", &CPG_Updated_cpp_t::B_26)
            .def_readwrite("y_26", &CPG_Updated_cpp_t::y_26)
            .def_readwrite("A_27", &CPG_Updated_cpp_t::A_27)
            .def_readwrite("B_27", &CPG_Updated_cpp_t::B_27)
            .def_readwrite("y_27", &CPG_Updated_cpp_t::y_27)
            .def_readwrite("A_28", &CPG_Updated_cpp_t::A_28)
            .def_readwrite("B_28", &CPG_Updated_cpp_t::B_28)
            .def_readwrite("y_28", &CPG_Updated_cpp_t::y_28)
            .def_readwrite("A_29", &CPG_Updated_cpp_t::A_29)
            .def_readwrite("B_29", &CPG_Updated_cpp_t::B_29)
            .def_readwrite("y_29", &CPG_Updated_cpp_t::y_29)
            .def_readwrite("ox_0", &CPG_Updated_cpp_t::ox_0)
            .def_readwrite("ou_0", &CPG_Updated_cpp_t::ou_0)
            .def_readwrite("etta", &CPG_Updated_cpp_t::etta)
            .def_readwrite("ox_1", &CPG_Updated_cpp_t::ox_1)
            .def_readwrite("ou_1", &CPG_Updated_cpp_t::ou_1)
            .def_readwrite("ox_2", &CPG_Updated_cpp_t::ox_2)
            .def_readwrite("ou_2", &CPG_Updated_cpp_t::ou_2)
            .def_readwrite("ox_3", &CPG_Updated_cpp_t::ox_3)
            .def_readwrite("ou_3", &CPG_Updated_cpp_t::ou_3)
            .def_readwrite("ox_4", &CPG_Updated_cpp_t::ox_4)
            .def_readwrite("ou_4", &CPG_Updated_cpp_t::ou_4)
            .def_readwrite("ox_5", &CPG_Updated_cpp_t::ox_5)
            .def_readwrite("ou_5", &CPG_Updated_cpp_t::ou_5)
            .def_readwrite("ox_6", &CPG_Updated_cpp_t::ox_6)
            .def_readwrite("ou_6", &CPG_Updated_cpp_t::ou_6)
            .def_readwrite("ox_7", &CPG_Updated_cpp_t::ox_7)
            .def_readwrite("ou_7", &CPG_Updated_cpp_t::ou_7)
            .def_readwrite("ox_8", &CPG_Updated_cpp_t::ox_8)
            .def_readwrite("ou_8", &CPG_Updated_cpp_t::ou_8)
            .def_readwrite("ox_9", &CPG_Updated_cpp_t::ox_9)
            .def_readwrite("ou_9", &CPG_Updated_cpp_t::ou_9)
            .def_readwrite("ox_10", &CPG_Updated_cpp_t::ox_10)
            .def_readwrite("ou_10", &CPG_Updated_cpp_t::ou_10)
            .def_readwrite("ox_11", &CPG_Updated_cpp_t::ox_11)
            .def_readwrite("ou_11", &CPG_Updated_cpp_t::ou_11)
            .def_readwrite("ox_12", &CPG_Updated_cpp_t::ox_12)
            .def_readwrite("ou_12", &CPG_Updated_cpp_t::ou_12)
            .def_readwrite("ox_13", &CPG_Updated_cpp_t::ox_13)
            .def_readwrite("ou_13", &CPG_Updated_cpp_t::ou_13)
            .def_readwrite("ox_14", &CPG_Updated_cpp_t::ox_14)
            .def_readwrite("ou_14", &CPG_Updated_cpp_t::ou_14)
            .def_readwrite("ox_15", &CPG_Updated_cpp_t::ox_15)
            .def_readwrite("ou_15", &CPG_Updated_cpp_t::ou_15)
            .def_readwrite("ox_16", &CPG_Updated_cpp_t::ox_16)
            .def_readwrite("ou_16", &CPG_Updated_cpp_t::ou_16)
            .def_readwrite("ox_17", &CPG_Updated_cpp_t::ox_17)
            .def_readwrite("ou_17", &CPG_Updated_cpp_t::ou_17)
            .def_readwrite("ox_18", &CPG_Updated_cpp_t::ox_18)
            .def_readwrite("ou_18", &CPG_Updated_cpp_t::ou_18)
            .def_readwrite("ox_19", &CPG_Updated_cpp_t::ox_19)
            .def_readwrite("ou_19", &CPG_Updated_cpp_t::ou_19)
            .def_readwrite("ox_20", &CPG_Updated_cpp_t::ox_20)
            .def_readwrite("ou_20", &CPG_Updated_cpp_t::ou_20)
            .def_readwrite("ox_21", &CPG_Updated_cpp_t::ox_21)
            .def_readwrite("ou_21", &CPG_Updated_cpp_t::ou_21)
            .def_readwrite("ox_22", &CPG_Updated_cpp_t::ox_22)
            .def_readwrite("ou_22", &CPG_Updated_cpp_t::ou_22)
            .def_readwrite("ox_23", &CPG_Updated_cpp_t::ox_23)
            .def_readwrite("ou_23", &CPG_Updated_cpp_t::ou_23)
            .def_readwrite("ox_24", &CPG_Updated_cpp_t::ox_24)
            .def_readwrite("ou_24", &CPG_Updated_cpp_t::ou_24)
            .def_readwrite("ox_25", &CPG_Updated_cpp_t::ox_25)
            .def_readwrite("ou_25", &CPG_Updated_cpp_t::ou_25)
            .def_readwrite("ox_26", &CPG_Updated_cpp_t::ox_26)
            .def_readwrite("ou_26", &CPG_Updated_cpp_t::ou_26)
            .def_readwrite("ox_27", &CPG_Updated_cpp_t::ox_27)
            .def_readwrite("ou_27", &CPG_Updated_cpp_t::ou_27)
            .def_readwrite("ox_28", &CPG_Updated_cpp_t::ox_28)
            .def_readwrite("ou_28", &CPG_Updated_cpp_t::ou_28)
            .def_readwrite("ox_29", &CPG_Updated_cpp_t::ox_29)
            .def_readwrite("ou_29", &CPG_Updated_cpp_t::ou_29)
            .def_readwrite("ox_30", &CPG_Updated_cpp_t::ox_30)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("u", &CPG_Prim_cpp_t::u)
            .def_readwrite("vc", &CPG_Prim_cpp_t::vc)
            .def_readwrite("x", &CPG_Prim_cpp_t::x)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &CPG_Dual_cpp_t::d50)
            .def_readwrite("d51", &CPG_Dual_cpp_t::d51)
            .def_readwrite("d52", &CPG_Dual_cpp_t::d52)
            .def_readwrite("d53", &CPG_Dual_cpp_t::d53)
            .def_readwrite("d54", &CPG_Dual_cpp_t::d54)
            .def_readwrite("d55", &CPG_Dual_cpp_t::d55)
            .def_readwrite("d56", &CPG_Dual_cpp_t::d56)
            .def_readwrite("d57", &CPG_Dual_cpp_t::d57)
            .def_readwrite("d58", &CPG_Dual_cpp_t::d58)
            .def_readwrite("d59", &CPG_Dual_cpp_t::d59)
            .def_readwrite("d60", &CPG_Dual_cpp_t::d60)
            .def_readwrite("d61", &CPG_Dual_cpp_t::d61)
            .def_readwrite("d62", &CPG_Dual_cpp_t::d62)
            .def_readwrite("d63", &CPG_Dual_cpp_t::d63)
            .def_readwrite("d64", &CPG_Dual_cpp_t::d64)
            .def_readwrite("d65", &CPG_Dual_cpp_t::d65)
            .def_readwrite("d66", &CPG_Dual_cpp_t::d66)
            .def_readwrite("d67", &CPG_Dual_cpp_t::d67)
            .def_readwrite("d68", &CPG_Dual_cpp_t::d68)
            .def_readwrite("d69", &CPG_Dual_cpp_t::d69)
            .def_readwrite("d70", &CPG_Dual_cpp_t::d70)
            .def_readwrite("d71", &CPG_Dual_cpp_t::d71)
            .def_readwrite("d72", &CPG_Dual_cpp_t::d72)
            .def_readwrite("d73", &CPG_Dual_cpp_t::d73)
            .def_readwrite("d74", &CPG_Dual_cpp_t::d74)
            .def_readwrite("d75", &CPG_Dual_cpp_t::d75)
            .def_readwrite("d76", &CPG_Dual_cpp_t::d76)
            .def_readwrite("d77", &CPG_Dual_cpp_t::d77)
            .def_readwrite("d78", &CPG_Dual_cpp_t::d78)
            .def_readwrite("d79", &CPG_Dual_cpp_t::d79)
            .def_readwrite("d80", &CPG_Dual_cpp_t::d80)
            .def_readwrite("d81", &CPG_Dual_cpp_t::d81)
            .def_readwrite("d82", &CPG_Dual_cpp_t::d82)
            .def_readwrite("d83", &CPG_Dual_cpp_t::d83)
            .def_readwrite("d84", &CPG_Dual_cpp_t::d84)
            .def_readwrite("d85", &CPG_Dual_cpp_t::d85)
            .def_readwrite("d86", &CPG_Dual_cpp_t::d86)
            .def_readwrite("d87", &CPG_Dual_cpp_t::d87)
            .def_readwrite("d88", &CPG_Dual_cpp_t::d88)
            .def_readwrite("d89", &CPG_Dual_cpp_t::d89)
            .def_readwrite("d90", &CPG_Dual_cpp_t::d90)
            .def_readwrite("d91", &CPG_Dual_cpp_t::d91)
            .def_readwrite("d92", &CPG_Dual_cpp_t::d92)
            .def_readwrite("d93", &CPG_Dual_cpp_t::d93)
            .def_readwrite("d94", &CPG_Dual_cpp_t::d94)
            .def_readwrite("d95", &CPG_Dual_cpp_t::d95)
            .def_readwrite("d96", &CPG_Dual_cpp_t::d96)
            .def_readwrite("d97", &CPG_Dual_cpp_t::d97)
            .def_readwrite("d98", &CPG_Dual_cpp_t::d98)
            .def_readwrite("d99", &CPG_Dual_cpp_t::d99)
            .def_readwrite("d100", &CPG_Dual_cpp_t::d100)
            .def_readwrite("d101", &CPG_Dual_cpp_t::d101)
            .def_readwrite("d102", &CPG_Dual_cpp_t::d102)
            .def_readwrite("d103", &CPG_Dual_cpp_t::d103)
            .def_readwrite("d104", &CPG_Dual_cpp_t::d104)
            .def_readwrite("d105", &CPG_Dual_cpp_t::d105)
            .def_readwrite("d106", &CPG_Dual_cpp_t::d106)
            .def_readwrite("d107", &CPG_Dual_cpp_t::d107)
            .def_readwrite("d108", &CPG_Dual_cpp_t::d108)
            .def_readwrite("d109", &CPG_Dual_cpp_t::d109)
            .def_readwrite("d110", &CPG_Dual_cpp_t::d110)
            .def_readwrite("d111", &CPG_Dual_cpp_t::d111)
            .def_readwrite("d112", &CPG_Dual_cpp_t::d112)
            .def_readwrite("d113", &CPG_Dual_cpp_t::d113)
            .def_readwrite("d114", &CPG_Dual_cpp_t::d114)
            .def_readwrite("d115", &CPG_Dual_cpp_t::d115)
            .def_readwrite("d116", &CPG_Dual_cpp_t::d116)
            .def_readwrite("d117", &CPG_Dual_cpp_t::d117)
            .def_readwrite("d118", &CPG_Dual_cpp_t::d118)
            .def_readwrite("d119", &CPG_Dual_cpp_t::d119)
            .def_readwrite("d120", &CPG_Dual_cpp_t::d120)
            .def_readwrite("d121", &CPG_Dual_cpp_t::d121)
            .def_readwrite("d122", &CPG_Dual_cpp_t::d122)
            .def_readwrite("d123", &CPG_Dual_cpp_t::d123)
            .def_readwrite("d124", &CPG_Dual_cpp_t::d124)
            .def_readwrite("d125", &CPG_Dual_cpp_t::d125)
            .def_readwrite("d126", &CPG_Dual_cpp_t::d126)
            .def_readwrite("d127", &CPG_Dual_cpp_t::d127)
            .def_readwrite("d128", &CPG_Dual_cpp_t::d128)
            .def_readwrite("d129", &CPG_Dual_cpp_t::d129)
            .def_readwrite("d130", &CPG_Dual_cpp_t::d130)
            .def_readwrite("d131", &CPG_Dual_cpp_t::d131)
            .def_readwrite("d132", &CPG_Dual_cpp_t::d132)
            .def_readwrite("d133", &CPG_Dual_cpp_t::d133)
            .def_readwrite("d134", &CPG_Dual_cpp_t::d134)
            .def_readwrite("d135", &CPG_Dual_cpp_t::d135)
            .def_readwrite("d136", &CPG_Dual_cpp_t::d136)
            .def_readwrite("d137", &CPG_Dual_cpp_t::d137)
            .def_readwrite("d138", &CPG_Dual_cpp_t::d138)
            .def_readwrite("d139", &CPG_Dual_cpp_t::d139)
            .def_readwrite("d140", &CPG_Dual_cpp_t::d140)
            .def_readwrite("d141", &CPG_Dual_cpp_t::d141)
            .def_readwrite("d142", &CPG_Dual_cpp_t::d142)
            .def_readwrite("d143", &CPG_Dual_cpp_t::d143)
            .def_readwrite("d144", &CPG_Dual_cpp_t::d144)
            .def_readwrite("d145", &CPG_Dual_cpp_t::d145)
            .def_readwrite("d146", &CPG_Dual_cpp_t::d146)
            .def_readwrite("d147", &CPG_Dual_cpp_t::d147)
            .def_readwrite("d148", &CPG_Dual_cpp_t::d148)
            .def_readwrite("d149", &CPG_Dual_cpp_t::d149)
            .def_readwrite("d150", &CPG_Dual_cpp_t::d150)
            .def_readwrite("d151", &CPG_Dual_cpp_t::d151)
            .def_readwrite("d152", &CPG_Dual_cpp_t::d152)
            .def_readwrite("d153", &CPG_Dual_cpp_t::d153)
            .def_readwrite("d154", &CPG_Dual_cpp_t::d154)
            .def_readwrite("d155", &CPG_Dual_cpp_t::d155)
            .def_readwrite("d156", &CPG_Dual_cpp_t::d156)
            .def_readwrite("d157", &CPG_Dual_cpp_t::d157)
            .def_readwrite("d158", &CPG_Dual_cpp_t::d158)
            .def_readwrite("d159", &CPG_Dual_cpp_t::d159)
            .def_readwrite("d160", &CPG_Dual_cpp_t::d160)
            .def_readwrite("d161", &CPG_Dual_cpp_t::d161)
            .def_readwrite("d162", &CPG_Dual_cpp_t::d162)
            .def_readwrite("d163", &CPG_Dual_cpp_t::d163)
            .def_readwrite("d164", &CPG_Dual_cpp_t::d164)
            .def_readwrite("d165", &CPG_Dual_cpp_t::d165)
            .def_readwrite("d166", &CPG_Dual_cpp_t::d166)
            .def_readwrite("d167", &CPG_Dual_cpp_t::d167)
            .def_readwrite("d168", &CPG_Dual_cpp_t::d168)
            .def_readwrite("d169", &CPG_Dual_cpp_t::d169)
            .def_readwrite("d170", &CPG_Dual_cpp_t::d170)
            .def_readwrite("d171", &CPG_Dual_cpp_t::d171)
            .def_readwrite("d172", &CPG_Dual_cpp_t::d172)
            .def_readwrite("d173", &CPG_Dual_cpp_t::d173)
            .def_readwrite("d174", &CPG_Dual_cpp_t::d174)
            .def_readwrite("d175", &CPG_Dual_cpp_t::d175)
            .def_readwrite("d176", &CPG_Dual_cpp_t::d176)
            .def_readwrite("d177", &CPG_Dual_cpp_t::d177)
            .def_readwrite("d178", &CPG_Dual_cpp_t::d178)
            .def_readwrite("d179", &CPG_Dual_cpp_t::d179)
            .def_readwrite("d180", &CPG_Dual_cpp_t::d180)
            .def_readwrite("d181", &CPG_Dual_cpp_t::d181)
            .def_readwrite("d182", &CPG_Dual_cpp_t::d182)
            .def_readwrite("d183", &CPG_Dual_cpp_t::d183)
            .def_readwrite("d184", &CPG_Dual_cpp_t::d184)
            .def_readwrite("d185", &CPG_Dual_cpp_t::d185)
            .def_readwrite("d186", &CPG_Dual_cpp_t::d186)
            .def_readwrite("d187", &CPG_Dual_cpp_t::d187)
            .def_readwrite("d188", &CPG_Dual_cpp_t::d188)
            .def_readwrite("d189", &CPG_Dual_cpp_t::d189)
            .def_readwrite("d190", &CPG_Dual_cpp_t::d190)
            .def_readwrite("d191", &CPG_Dual_cpp_t::d191)
            .def_readwrite("d192", &CPG_Dual_cpp_t::d192)
            .def_readwrite("d193", &CPG_Dual_cpp_t::d193)
            .def_readwrite("d194", &CPG_Dual_cpp_t::d194)
            .def_readwrite("d195", &CPG_Dual_cpp_t::d195)
            .def_readwrite("d196", &CPG_Dual_cpp_t::d196)
            .def_readwrite("d197", &CPG_Dual_cpp_t::d197)
            .def_readwrite("d198", &CPG_Dual_cpp_t::d198)
            .def_readwrite("d199", &CPG_Dual_cpp_t::d199)
            .def_readwrite("d200", &CPG_Dual_cpp_t::d200)
            .def_readwrite("d201", &CPG_Dual_cpp_t::d201)
            .def_readwrite("d202", &CPG_Dual_cpp_t::d202)
            .def_readwrite("d203", &CPG_Dual_cpp_t::d203)
            .def_readwrite("d204", &CPG_Dual_cpp_t::d204)
            .def_readwrite("d205", &CPG_Dual_cpp_t::d205)
            .def_readwrite("d206", &CPG_Dual_cpp_t::d206)
            .def_readwrite("d207", &CPG_Dual_cpp_t::d207)
            .def_readwrite("d208", &CPG_Dual_cpp_t::d208)
            .def_readwrite("d209", &CPG_Dual_cpp_t::d209)
            .def_readwrite("d210", &CPG_Dual_cpp_t::d210)
            .def_readwrite("d211", &CPG_Dual_cpp_t::d211)
            .def_readwrite("d212", &CPG_Dual_cpp_t::d212)
            .def_readwrite("d213", &CPG_Dual_cpp_t::d213)
            .def_readwrite("d214", &CPG_Dual_cpp_t::d214)
            .def_readwrite("d215", &CPG_Dual_cpp_t::d215)
            .def_readwrite("d216", &CPG_Dual_cpp_t::d216)
            .def_readwrite("d217", &CPG_Dual_cpp_t::d217)
            .def_readwrite("d218", &CPG_Dual_cpp_t::d218)
            .def_readwrite("d219", &CPG_Dual_cpp_t::d219)
            .def_readwrite("d220", &CPG_Dual_cpp_t::d220)
            .def_readwrite("d221", &CPG_Dual_cpp_t::d221)
            .def_readwrite("d222", &CPG_Dual_cpp_t::d222)
            .def_readwrite("d223", &CPG_Dual_cpp_t::d223)
            .def_readwrite("d224", &CPG_Dual_cpp_t::d224)
            .def_readwrite("d225", &CPG_Dual_cpp_t::d225)
            .def_readwrite("d226", &CPG_Dual_cpp_t::d226)
            .def_readwrite("d227", &CPG_Dual_cpp_t::d227)
            .def_readwrite("d228", &CPG_Dual_cpp_t::d228)
            .def_readwrite("d229", &CPG_Dual_cpp_t::d229)
            .def_readwrite("d230", &CPG_Dual_cpp_t::d230)
            .def_readwrite("d231", &CPG_Dual_cpp_t::d231)
            .def_readwrite("d232", &CPG_Dual_cpp_t::d232)
            .def_readwrite("d233", &CPG_Dual_cpp_t::d233)
            .def_readwrite("d234", &CPG_Dual_cpp_t::d234)
            .def_readwrite("d235", &CPG_Dual_cpp_t::d235)
            .def_readwrite("d236", &CPG_Dual_cpp_t::d236)
            .def_readwrite("d237", &CPG_Dual_cpp_t::d237)
            .def_readwrite("d238", &CPG_Dual_cpp_t::d238)
            .def_readwrite("d239", &CPG_Dual_cpp_t::d239)
            .def_readwrite("d240", &CPG_Dual_cpp_t::d240)
            .def_readwrite("d241", &CPG_Dual_cpp_t::d241)
            .def_readwrite("d242", &CPG_Dual_cpp_t::d242)
            .def_readwrite("d243", &CPG_Dual_cpp_t::d243)
            .def_readwrite("d244", &CPG_Dual_cpp_t::d244)
            .def_readwrite("d245", &CPG_Dual_cpp_t::d245)
            .def_readwrite("d246", &CPG_Dual_cpp_t::d246)
            .def_readwrite("d247", &CPG_Dual_cpp_t::d247)
            .def_readwrite("d248", &CPG_Dual_cpp_t::d248)
            .def_readwrite("d249", &CPG_Dual_cpp_t::d249)
            .def_readwrite("d250", &CPG_Dual_cpp_t::d250)
            .def_readwrite("d251", &CPG_Dual_cpp_t::d251)
            .def_readwrite("d252", &CPG_Dual_cpp_t::d252)
            .def_readwrite("d253", &CPG_Dual_cpp_t::d253)
            .def_readwrite("d254", &CPG_Dual_cpp_t::d254)
            .def_readwrite("d255", &CPG_Dual_cpp_t::d255)
            .def_readwrite("d256", &CPG_Dual_cpp_t::d256)
            .def_readwrite("d257", &CPG_Dual_cpp_t::d257)
            .def_readwrite("d258", &CPG_Dual_cpp_t::d258)
            .def_readwrite("d259", &CPG_Dual_cpp_t::d259)
            .def_readwrite("d260", &CPG_Dual_cpp_t::d260)
            .def_readwrite("d261", &CPG_Dual_cpp_t::d261)
            .def_readwrite("d262", &CPG_Dual_cpp_t::d262)
            .def_readwrite("d263", &CPG_Dual_cpp_t::d263)
            .def_readwrite("d264", &CPG_Dual_cpp_t::d264)
            .def_readwrite("d265", &CPG_Dual_cpp_t::d265)
            .def_readwrite("d266", &CPG_Dual_cpp_t::d266)
            .def_readwrite("d267", &CPG_Dual_cpp_t::d267)
            .def_readwrite("d268", &CPG_Dual_cpp_t::d268)
            .def_readwrite("d269", &CPG_Dual_cpp_t::d269)
            .def_readwrite("d270", &CPG_Dual_cpp_t::d270)
            .def_readwrite("d271", &CPG_Dual_cpp_t::d271)
            .def_readwrite("d272", &CPG_Dual_cpp_t::d272)
            .def_readwrite("d273", &CPG_Dual_cpp_t::d273)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_feastol", &cpg_set_solver_feastol);
    m.def("set_solver_abstol", &cpg_set_solver_abstol);
    m.def("set_solver_reltol", &cpg_set_solver_reltol);
    m.def("set_solver_feastol_inacc", &cpg_set_solver_feastol_inacc);
    m.def("set_solver_abstol_inacc", &cpg_set_solver_abstol_inacc);
    m.def("set_solver_reltol_inacc", &cpg_set_solver_reltol_inacc);
    m.def("set_solver_maxit", &cpg_set_solver_maxit);

}
