
/*
Auto-generated by CVXPYgen on February 20, 2026 at 23:27:12.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_sqrt_tau(-0.68383154103145094016);
  cpg_update_sqrt_tau_xq_goal(0, 0.17204783302275034051);
  cpg_update_tau_lamb(-0.12710363454430329000);
  cpg_update_start_pos(0, 0.42618149316640008273);
  cpg_update_end_pos(0, 0.36476530898512571355);
  cpg_update_A_discrete(0, -1.20207584207666373644);
  cpg_update_B_discrete(0, 0.14857162739443738331);
  cpg_update_y_discrete(0, 0.49858784432332448056);
  cpg_update_ox_cvxpy(0, 0.31361502889156539498);
  cpg_update_ou_cvxpy(0, 0.12530318856859903875);
  cpg_update_etta(-0.02078118056507345310);
  cpg_update_S_x_scaling(0, -0.31127290488852382699);
  cpg_update_c_x_scaling(0, 0.20435649780474213211);
  cpg_update_omega_max(0.07233687328821442053);
  cpg_update_S_u_scaling(0, -0.33181964494968013701);
  cpg_update_c_u_scaling(0, 0.91732853549083759326);
  cpg_update_m_max(-0.99094634732251518638);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<300; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<707; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }
  for(i=0; i<700; i++) {
    printf("vc[%d] = %f\n", i, CPG_Result.prim->vc[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<7; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<7; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<7; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<7; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<7; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<7; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<7; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<7; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<7; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<7; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<7; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<7; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<7; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<7; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<7; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<7; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<7; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<7; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<7; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<7; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<7; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<7; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<7; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<7; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<7; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<7; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<7; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<7; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  for(i=0; i<7; i++) {
    printf("d32[%d] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  for(i=0; i<7; i++) {
    printf("d33[%d] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  for(i=0; i<7; i++) {
    printf("d34[%d] = %f\n", i, CPG_Result.dual->d34[i]);
  }
  for(i=0; i<7; i++) {
    printf("d35[%d] = %f\n", i, CPG_Result.dual->d35[i]);
  }
  for(i=0; i<7; i++) {
    printf("d36[%d] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  for(i=0; i<7; i++) {
    printf("d37[%d] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  for(i=0; i<7; i++) {
    printf("d38[%d] = %f\n", i, CPG_Result.dual->d38[i]);
  }
  for(i=0; i<7; i++) {
    printf("d39[%d] = %f\n", i, CPG_Result.dual->d39[i]);
  }
  for(i=0; i<7; i++) {
    printf("d40[%d] = %f\n", i, CPG_Result.dual->d40[i]);
  }
  for(i=0; i<7; i++) {
    printf("d41[%d] = %f\n", i, CPG_Result.dual->d41[i]);
  }
  for(i=0; i<7; i++) {
    printf("d42[%d] = %f\n", i, CPG_Result.dual->d42[i]);
  }
  for(i=0; i<7; i++) {
    printf("d43[%d] = %f\n", i, CPG_Result.dual->d43[i]);
  }
  for(i=0; i<7; i++) {
    printf("d44[%d] = %f\n", i, CPG_Result.dual->d44[i]);
  }
  for(i=0; i<7; i++) {
    printf("d45[%d] = %f\n", i, CPG_Result.dual->d45[i]);
  }
  for(i=0; i<7; i++) {
    printf("d46[%d] = %f\n", i, CPG_Result.dual->d46[i]);
  }
  for(i=0; i<7; i++) {
    printf("d47[%d] = %f\n", i, CPG_Result.dual->d47[i]);
  }
  for(i=0; i<7; i++) {
    printf("d48[%d] = %f\n", i, CPG_Result.dual->d48[i]);
  }
  for(i=0; i<7; i++) {
    printf("d49[%d] = %f\n", i, CPG_Result.dual->d49[i]);
  }
  for(i=0; i<7; i++) {
    printf("d50[%d] = %f\n", i, CPG_Result.dual->d50[i]);
  }
  for(i=0; i<7; i++) {
    printf("d51[%d] = %f\n", i, CPG_Result.dual->d51[i]);
  }
  for(i=0; i<7; i++) {
    printf("d52[%d] = %f\n", i, CPG_Result.dual->d52[i]);
  }
  for(i=0; i<7; i++) {
    printf("d53[%d] = %f\n", i, CPG_Result.dual->d53[i]);
  }
  for(i=0; i<7; i++) {
    printf("d54[%d] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  for(i=0; i<7; i++) {
    printf("d55[%d] = %f\n", i, CPG_Result.dual->d55[i]);
  }
  for(i=0; i<7; i++) {
    printf("d56[%d] = %f\n", i, CPG_Result.dual->d56[i]);
  }
  for(i=0; i<7; i++) {
    printf("d57[%d] = %f\n", i, CPG_Result.dual->d57[i]);
  }
  for(i=0; i<7; i++) {
    printf("d58[%d] = %f\n", i, CPG_Result.dual->d58[i]);
  }
  for(i=0; i<7; i++) {
    printf("d59[%d] = %f\n", i, CPG_Result.dual->d59[i]);
  }
  for(i=0; i<7; i++) {
    printf("d60[%d] = %f\n", i, CPG_Result.dual->d60[i]);
  }
  for(i=0; i<7; i++) {
    printf("d61[%d] = %f\n", i, CPG_Result.dual->d61[i]);
  }
  for(i=0; i<7; i++) {
    printf("d62[%d] = %f\n", i, CPG_Result.dual->d62[i]);
  }
  for(i=0; i<7; i++) {
    printf("d63[%d] = %f\n", i, CPG_Result.dual->d63[i]);
  }
  for(i=0; i<7; i++) {
    printf("d64[%d] = %f\n", i, CPG_Result.dual->d64[i]);
  }
  for(i=0; i<7; i++) {
    printf("d65[%d] = %f\n", i, CPG_Result.dual->d65[i]);
  }
  for(i=0; i<7; i++) {
    printf("d66[%d] = %f\n", i, CPG_Result.dual->d66[i]);
  }
  for(i=0; i<7; i++) {
    printf("d67[%d] = %f\n", i, CPG_Result.dual->d67[i]);
  }
  for(i=0; i<7; i++) {
    printf("d68[%d] = %f\n", i, CPG_Result.dual->d68[i]);
  }
  for(i=0; i<7; i++) {
    printf("d69[%d] = %f\n", i, CPG_Result.dual->d69[i]);
  }
  for(i=0; i<7; i++) {
    printf("d70[%d] = %f\n", i, CPG_Result.dual->d70[i]);
  }
  for(i=0; i<7; i++) {
    printf("d71[%d] = %f\n", i, CPG_Result.dual->d71[i]);
  }
  for(i=0; i<7; i++) {
    printf("d72[%d] = %f\n", i, CPG_Result.dual->d72[i]);
  }
  for(i=0; i<7; i++) {
    printf("d73[%d] = %f\n", i, CPG_Result.dual->d73[i]);
  }
  for(i=0; i<7; i++) {
    printf("d74[%d] = %f\n", i, CPG_Result.dual->d74[i]);
  }
  for(i=0; i<7; i++) {
    printf("d75[%d] = %f\n", i, CPG_Result.dual->d75[i]);
  }
  for(i=0; i<7; i++) {
    printf("d76[%d] = %f\n", i, CPG_Result.dual->d76[i]);
  }
  for(i=0; i<7; i++) {
    printf("d77[%d] = %f\n", i, CPG_Result.dual->d77[i]);
  }
  for(i=0; i<7; i++) {
    printf("d78[%d] = %f\n", i, CPG_Result.dual->d78[i]);
  }
  for(i=0; i<7; i++) {
    printf("d79[%d] = %f\n", i, CPG_Result.dual->d79[i]);
  }
  for(i=0; i<7; i++) {
    printf("d80[%d] = %f\n", i, CPG_Result.dual->d80[i]);
  }
  for(i=0; i<7; i++) {
    printf("d81[%d] = %f\n", i, CPG_Result.dual->d81[i]);
  }
  for(i=0; i<7; i++) {
    printf("d82[%d] = %f\n", i, CPG_Result.dual->d82[i]);
  }
  for(i=0; i<7; i++) {
    printf("d83[%d] = %f\n", i, CPG_Result.dual->d83[i]);
  }
  for(i=0; i<7; i++) {
    printf("d84[%d] = %f\n", i, CPG_Result.dual->d84[i]);
  }
  for(i=0; i<7; i++) {
    printf("d85[%d] = %f\n", i, CPG_Result.dual->d85[i]);
  }
  for(i=0; i<7; i++) {
    printf("d86[%d] = %f\n", i, CPG_Result.dual->d86[i]);
  }
  for(i=0; i<7; i++) {
    printf("d87[%d] = %f\n", i, CPG_Result.dual->d87[i]);
  }
  for(i=0; i<7; i++) {
    printf("d88[%d] = %f\n", i, CPG_Result.dual->d88[i]);
  }
  for(i=0; i<7; i++) {
    printf("d89[%d] = %f\n", i, CPG_Result.dual->d89[i]);
  }
  for(i=0; i<7; i++) {
    printf("d90[%d] = %f\n", i, CPG_Result.dual->d90[i]);
  }
  for(i=0; i<7; i++) {
    printf("d91[%d] = %f\n", i, CPG_Result.dual->d91[i]);
  }
  for(i=0; i<7; i++) {
    printf("d92[%d] = %f\n", i, CPG_Result.dual->d92[i]);
  }
  for(i=0; i<7; i++) {
    printf("d93[%d] = %f\n", i, CPG_Result.dual->d93[i]);
  }
  for(i=0; i<7; i++) {
    printf("d94[%d] = %f\n", i, CPG_Result.dual->d94[i]);
  }
  for(i=0; i<7; i++) {
    printf("d95[%d] = %f\n", i, CPG_Result.dual->d95[i]);
  }
  for(i=0; i<7; i++) {
    printf("d96[%d] = %f\n", i, CPG_Result.dual->d96[i]);
  }
  for(i=0; i<7; i++) {
    printf("d97[%d] = %f\n", i, CPG_Result.dual->d97[i]);
  }
  for(i=0; i<7; i++) {
    printf("d98[%d] = %f\n", i, CPG_Result.dual->d98[i]);
  }
  for(i=0; i<7; i++) {
    printf("d99[%d] = %f\n", i, CPG_Result.dual->d99[i]);
  }
  for(i=0; i<7; i++) {
    printf("d100[%d] = %f\n", i, CPG_Result.dual->d100[i]);
  }
  for(i=0; i<7; i++) {
    printf("d101[%d] = %f\n", i, CPG_Result.dual->d101[i]);
  }
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  printf("d109 = %f\n", CPG_Result.dual->d109);
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  printf("d122 = %f\n", CPG_Result.dual->d122);
  printf("d123 = %f\n", CPG_Result.dual->d123);
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  printf("d126 = %f\n", CPG_Result.dual->d126);
  printf("d127 = %f\n", CPG_Result.dual->d127);
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  printf("d131 = %f\n", CPG_Result.dual->d131);
  printf("d132 = %f\n", CPG_Result.dual->d132);
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  printf("d135 = %f\n", CPG_Result.dual->d135);
  printf("d136 = %f\n", CPG_Result.dual->d136);
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  printf("d140 = %f\n", CPG_Result.dual->d140);
  printf("d141 = %f\n", CPG_Result.dual->d141);
  printf("d142 = %f\n", CPG_Result.dual->d142);
  printf("d143 = %f\n", CPG_Result.dual->d143);
  printf("d144 = %f\n", CPG_Result.dual->d144);
  printf("d145 = %f\n", CPG_Result.dual->d145);
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  printf("d149 = %f\n", CPG_Result.dual->d149);
  printf("d150 = %f\n", CPG_Result.dual->d150);
  printf("d151 = %f\n", CPG_Result.dual->d151);
  printf("d152 = %f\n", CPG_Result.dual->d152);
  printf("d153 = %f\n", CPG_Result.dual->d153);
  printf("d154 = %f\n", CPG_Result.dual->d154);
  printf("d155 = %f\n", CPG_Result.dual->d155);
  printf("d156 = %f\n", CPG_Result.dual->d156);
  printf("d157 = %f\n", CPG_Result.dual->d157);
  printf("d158 = %f\n", CPG_Result.dual->d158);
  printf("d159 = %f\n", CPG_Result.dual->d159);
  printf("d160 = %f\n", CPG_Result.dual->d160);
  printf("d161 = %f\n", CPG_Result.dual->d161);
  printf("d162 = %f\n", CPG_Result.dual->d162);
  printf("d163 = %f\n", CPG_Result.dual->d163);
  printf("d164 = %f\n", CPG_Result.dual->d164);
  printf("d165 = %f\n", CPG_Result.dual->d165);
  printf("d166 = %f\n", CPG_Result.dual->d166);
  printf("d167 = %f\n", CPG_Result.dual->d167);
  printf("d168 = %f\n", CPG_Result.dual->d168);
  printf("d169 = %f\n", CPG_Result.dual->d169);
  printf("d170 = %f\n", CPG_Result.dual->d170);
  printf("d171 = %f\n", CPG_Result.dual->d171);
  printf("d172 = %f\n", CPG_Result.dual->d172);
  printf("d173 = %f\n", CPG_Result.dual->d173);
  printf("d174 = %f\n", CPG_Result.dual->d174);
  printf("d175 = %f\n", CPG_Result.dual->d175);
  printf("d176 = %f\n", CPG_Result.dual->d176);
  printf("d177 = %f\n", CPG_Result.dual->d177);
  printf("d178 = %f\n", CPG_Result.dual->d178);
  printf("d179 = %f\n", CPG_Result.dual->d179);
  printf("d180 = %f\n", CPG_Result.dual->d180);
  printf("d181 = %f\n", CPG_Result.dual->d181);
  printf("d182 = %f\n", CPG_Result.dual->d182);
  printf("d183 = %f\n", CPG_Result.dual->d183);
  printf("d184 = %f\n", CPG_Result.dual->d184);
  printf("d185 = %f\n", CPG_Result.dual->d185);
  printf("d186 = %f\n", CPG_Result.dual->d186);
  printf("d187 = %f\n", CPG_Result.dual->d187);
  printf("d188 = %f\n", CPG_Result.dual->d188);
  printf("d189 = %f\n", CPG_Result.dual->d189);
  printf("d190 = %f\n", CPG_Result.dual->d190);
  printf("d191 = %f\n", CPG_Result.dual->d191);
  printf("d192 = %f\n", CPG_Result.dual->d192);
  printf("d193 = %f\n", CPG_Result.dual->d193);
  printf("d194 = %f\n", CPG_Result.dual->d194);
  printf("d195 = %f\n", CPG_Result.dual->d195);
  printf("d196 = %f\n", CPG_Result.dual->d196);
  printf("d197 = %f\n", CPG_Result.dual->d197);
  printf("d198 = %f\n", CPG_Result.dual->d198);
  printf("d199 = %f\n", CPG_Result.dual->d199);
  printf("d200 = %f\n", CPG_Result.dual->d200);
  printf("d201 = %f\n", CPG_Result.dual->d201);
  printf("d202 = %f\n", CPG_Result.dual->d202);
  printf("d203 = %f\n", CPG_Result.dual->d203);
  printf("d204 = %f\n", CPG_Result.dual->d204);
  printf("d205 = %f\n", CPG_Result.dual->d205);
  printf("d206 = %f\n", CPG_Result.dual->d206);
  printf("d207 = %f\n", CPG_Result.dual->d207);
  printf("d208 = %f\n", CPG_Result.dual->d208);
  printf("d209 = %f\n", CPG_Result.dual->d209);
  printf("d210 = %f\n", CPG_Result.dual->d210);
  printf("d211 = %f\n", CPG_Result.dual->d211);
  printf("d212 = %f\n", CPG_Result.dual->d212);
  printf("d213 = %f\n", CPG_Result.dual->d213);
  printf("d214 = %f\n", CPG_Result.dual->d214);
  printf("d215 = %f\n", CPG_Result.dual->d215);
  printf("d216 = %f\n", CPG_Result.dual->d216);
  printf("d217 = %f\n", CPG_Result.dual->d217);
  printf("d218 = %f\n", CPG_Result.dual->d218);
  printf("d219 = %f\n", CPG_Result.dual->d219);
  printf("d220 = %f\n", CPG_Result.dual->d220);
  printf("d221 = %f\n", CPG_Result.dual->d221);
  printf("d222 = %f\n", CPG_Result.dual->d222);
  printf("d223 = %f\n", CPG_Result.dual->d223);
  printf("d224 = %f\n", CPG_Result.dual->d224);
  printf("d225 = %f\n", CPG_Result.dual->d225);
  printf("d226 = %f\n", CPG_Result.dual->d226);
  printf("d227 = %f\n", CPG_Result.dual->d227);
  printf("d228 = %f\n", CPG_Result.dual->d228);
  printf("d229 = %f\n", CPG_Result.dual->d229);
  printf("d230 = %f\n", CPG_Result.dual->d230);
  printf("d231 = %f\n", CPG_Result.dual->d231);
  printf("d232 = %f\n", CPG_Result.dual->d232);
  printf("d233 = %f\n", CPG_Result.dual->d233);
  printf("d234 = %f\n", CPG_Result.dual->d234);
  printf("d235 = %f\n", CPG_Result.dual->d235);
  printf("d236 = %f\n", CPG_Result.dual->d236);
  printf("d237 = %f\n", CPG_Result.dual->d237);
  printf("d238 = %f\n", CPG_Result.dual->d238);
  printf("d239 = %f\n", CPG_Result.dual->d239);
  printf("d240 = %f\n", CPG_Result.dual->d240);
  printf("d241 = %f\n", CPG_Result.dual->d241);
  printf("d242 = %f\n", CPG_Result.dual->d242);
  printf("d243 = %f\n", CPG_Result.dual->d243);
  printf("d244 = %f\n", CPG_Result.dual->d244);
  printf("d245 = %f\n", CPG_Result.dual->d245);
  printf("d246 = %f\n", CPG_Result.dual->d246);
  printf("d247 = %f\n", CPG_Result.dual->d247);
  printf("d248 = %f\n", CPG_Result.dual->d248);
  printf("d249 = %f\n", CPG_Result.dual->d249);
  printf("d250 = %f\n", CPG_Result.dual->d250);
  printf("d251 = %f\n", CPG_Result.dual->d251);
  printf("d252 = %f\n", CPG_Result.dual->d252);
  printf("d253 = %f\n", CPG_Result.dual->d253);
  printf("d254 = %f\n", CPG_Result.dual->d254);
  printf("d255 = %f\n", CPG_Result.dual->d255);
  printf("d256 = %f\n", CPG_Result.dual->d256);
  printf("d257 = %f\n", CPG_Result.dual->d257);
  printf("d258 = %f\n", CPG_Result.dual->d258);
  printf("d259 = %f\n", CPG_Result.dual->d259);
  printf("d260 = %f\n", CPG_Result.dual->d260);
  printf("d261 = %f\n", CPG_Result.dual->d261);
  printf("d262 = %f\n", CPG_Result.dual->d262);
  printf("d263 = %f\n", CPG_Result.dual->d263);
  printf("d264 = %f\n", CPG_Result.dual->d264);
  printf("d265 = %f\n", CPG_Result.dual->d265);
  printf("d266 = %f\n", CPG_Result.dual->d266);
  printf("d267 = %f\n", CPG_Result.dual->d267);
  printf("d268 = %f\n", CPG_Result.dual->d268);
  printf("d269 = %f\n", CPG_Result.dual->d269);
  printf("d270 = %f\n", CPG_Result.dual->d270);
  printf("d271 = %f\n", CPG_Result.dual->d271);
  printf("d272 = %f\n", CPG_Result.dual->d272);
  printf("d273 = %f\n", CPG_Result.dual->d273);
  printf("d274 = %f\n", CPG_Result.dual->d274);
  printf("d275 = %f\n", CPG_Result.dual->d275);
  printf("d276 = %f\n", CPG_Result.dual->d276);
  printf("d277 = %f\n", CPG_Result.dual->d277);
  printf("d278 = %f\n", CPG_Result.dual->d278);
  printf("d279 = %f\n", CPG_Result.dual->d279);
  printf("d280 = %f\n", CPG_Result.dual->d280);
  printf("d281 = %f\n", CPG_Result.dual->d281);
  printf("d282 = %f\n", CPG_Result.dual->d282);
  printf("d283 = %f\n", CPG_Result.dual->d283);
  printf("d284 = %f\n", CPG_Result.dual->d284);
  printf("d285 = %f\n", CPG_Result.dual->d285);
  printf("d286 = %f\n", CPG_Result.dual->d286);
  printf("d287 = %f\n", CPG_Result.dual->d287);
  printf("d288 = %f\n", CPG_Result.dual->d288);
  printf("d289 = %f\n", CPG_Result.dual->d289);
  printf("d290 = %f\n", CPG_Result.dual->d290);
  printf("d291 = %f\n", CPG_Result.dual->d291);
  printf("d292 = %f\n", CPG_Result.dual->d292);
  printf("d293 = %f\n", CPG_Result.dual->d293);
  printf("d294 = %f\n", CPG_Result.dual->d294);
  printf("d295 = %f\n", CPG_Result.dual->d295);
  printf("d296 = %f\n", CPG_Result.dual->d296);
  printf("d297 = %f\n", CPG_Result.dual->d297);
  printf("d298 = %f\n", CPG_Result.dual->d298);
  printf("d299 = %f\n", CPG_Result.dual->d299);
  printf("d300 = %f\n", CPG_Result.dual->d300);
  printf("d301 = %f\n", CPG_Result.dual->d301);
  printf("d302 = %f\n", CPG_Result.dual->d302);
  printf("d303 = %f\n", CPG_Result.dual->d303);
  printf("d304 = %f\n", CPG_Result.dual->d304);
  printf("d305 = %f\n", CPG_Result.dual->d305);
  printf("d306 = %f\n", CPG_Result.dual->d306);
  printf("d307 = %f\n", CPG_Result.dual->d307);
  printf("d308 = %f\n", CPG_Result.dual->d308);
  printf("d309 = %f\n", CPG_Result.dual->d309);
  printf("d310 = %f\n", CPG_Result.dual->d310);
  printf("d311 = %f\n", CPG_Result.dual->d311);
  printf("d312 = %f\n", CPG_Result.dual->d312);
  printf("d313 = %f\n", CPG_Result.dual->d313);
  printf("d314 = %f\n", CPG_Result.dual->d314);
  printf("d315 = %f\n", CPG_Result.dual->d315);
  printf("d316 = %f\n", CPG_Result.dual->d316);
  printf("d317 = %f\n", CPG_Result.dual->d317);
  printf("d318 = %f\n", CPG_Result.dual->d318);
  printf("d319 = %f\n", CPG_Result.dual->d319);
  printf("d320 = %f\n", CPG_Result.dual->d320);
  printf("d321 = %f\n", CPG_Result.dual->d321);
  printf("d322 = %f\n", CPG_Result.dual->d322);
  printf("d323 = %f\n", CPG_Result.dual->d323);
  printf("d324 = %f\n", CPG_Result.dual->d324);
  printf("d325 = %f\n", CPG_Result.dual->d325);
  printf("d326 = %f\n", CPG_Result.dual->d326);
  printf("d327 = %f\n", CPG_Result.dual->d327);
  printf("d328 = %f\n", CPG_Result.dual->d328);
  printf("d329 = %f\n", CPG_Result.dual->d329);
  printf("d330 = %f\n", CPG_Result.dual->d330);
  printf("d331 = %f\n", CPG_Result.dual->d331);
  printf("d332 = %f\n", CPG_Result.dual->d332);
  printf("d333 = %f\n", CPG_Result.dual->d333);
  printf("d334 = %f\n", CPG_Result.dual->d334);
  printf("d335 = %f\n", CPG_Result.dual->d335);
  printf("d336 = %f\n", CPG_Result.dual->d336);
  printf("d337 = %f\n", CPG_Result.dual->d337);
  printf("d338 = %f\n", CPG_Result.dual->d338);
  printf("d339 = %f\n", CPG_Result.dual->d339);
  printf("d340 = %f\n", CPG_Result.dual->d340);
  printf("d341 = %f\n", CPG_Result.dual->d341);
  printf("d342 = %f\n", CPG_Result.dual->d342);
  printf("d343 = %f\n", CPG_Result.dual->d343);
  printf("d344 = %f\n", CPG_Result.dual->d344);
  printf("d345 = %f\n", CPG_Result.dual->d345);
  printf("d346 = %f\n", CPG_Result.dual->d346);
  printf("d347 = %f\n", CPG_Result.dual->d347);
  printf("d348 = %f\n", CPG_Result.dual->d348);
  printf("d349 = %f\n", CPG_Result.dual->d349);
  printf("d350 = %f\n", CPG_Result.dual->d350);
  printf("d351 = %f\n", CPG_Result.dual->d351);
  printf("d352 = %f\n", CPG_Result.dual->d352);
  printf("d353 = %f\n", CPG_Result.dual->d353);
  printf("d354 = %f\n", CPG_Result.dual->d354);
  printf("d355 = %f\n", CPG_Result.dual->d355);
  printf("d356 = %f\n", CPG_Result.dual->d356);
  printf("d357 = %f\n", CPG_Result.dual->d357);
  printf("d358 = %f\n", CPG_Result.dual->d358);
  printf("d359 = %f\n", CPG_Result.dual->d359);
  printf("d360 = %f\n", CPG_Result.dual->d360);
  printf("d361 = %f\n", CPG_Result.dual->d361);
  printf("d362 = %f\n", CPG_Result.dual->d362);
  printf("d363 = %f\n", CPG_Result.dual->d363);
  printf("d364 = %f\n", CPG_Result.dual->d364);
  printf("d365 = %f\n", CPG_Result.dual->d365);
  printf("d366 = %f\n", CPG_Result.dual->d366);
  printf("d367 = %f\n", CPG_Result.dual->d367);
  printf("d368 = %f\n", CPG_Result.dual->d368);
  printf("d369 = %f\n", CPG_Result.dual->d369);
  printf("d370 = %f\n", CPG_Result.dual->d370);
  printf("d371 = %f\n", CPG_Result.dual->d371);
  printf("d372 = %f\n", CPG_Result.dual->d372);
  printf("d373 = %f\n", CPG_Result.dual->d373);
  printf("d374 = %f\n", CPG_Result.dual->d374);
  printf("d375 = %f\n", CPG_Result.dual->d375);
  printf("d376 = %f\n", CPG_Result.dual->d376);
  printf("d377 = %f\n", CPG_Result.dual->d377);
  printf("d378 = %f\n", CPG_Result.dual->d378);
  printf("d379 = %f\n", CPG_Result.dual->d379);
  printf("d380 = %f\n", CPG_Result.dual->d380);
  printf("d381 = %f\n", CPG_Result.dual->d381);
  printf("d382 = %f\n", CPG_Result.dual->d382);
  printf("d383 = %f\n", CPG_Result.dual->d383);
  printf("d384 = %f\n", CPG_Result.dual->d384);
  printf("d385 = %f\n", CPG_Result.dual->d385);
  printf("d386 = %f\n", CPG_Result.dual->d386);
  printf("d387 = %f\n", CPG_Result.dual->d387);
  printf("d388 = %f\n", CPG_Result.dual->d388);
  printf("d389 = %f\n", CPG_Result.dual->d389);
  printf("d390 = %f\n", CPG_Result.dual->d390);
  printf("d391 = %f\n", CPG_Result.dual->d391);
  printf("d392 = %f\n", CPG_Result.dual->d392);
  printf("d393 = %f\n", CPG_Result.dual->d393);
  printf("d394 = %f\n", CPG_Result.dual->d394);
  printf("d395 = %f\n", CPG_Result.dual->d395);
  printf("d396 = %f\n", CPG_Result.dual->d396);
  printf("d397 = %f\n", CPG_Result.dual->d397);
  printf("d398 = %f\n", CPG_Result.dual->d398);
  printf("d399 = %f\n", CPG_Result.dual->d399);
  printf("d400 = %f\n", CPG_Result.dual->d400);
  printf("d401 = %f\n", CPG_Result.dual->d401);
  printf("d402 = %f\n", CPG_Result.dual->d402);
  printf("d403 = %f\n", CPG_Result.dual->d403);

  return 0;

}
