
/*
Auto-generated by CVXPYgen on March 31, 2026 at 23:25:22.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include <time.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_sqrt_tau(1.82574185835055380345);
  cpg_update_sqrt_alpha_m_sqrt_tau(1.29099444873580582183);
  cpg_update_tau_lamb(33333.33333333333575865254);
  cpg_update_start_pos(0, 0.50000000000000000000);
  cpg_update_end_pos(0, 0.50000000000000000000);
  cpg_update_A_discrete(0, 0.98738065509473293968);
  cpg_update_B_discrete_l(0, 0.00001428323475571563);
  cpg_update_B_discrete_r(0, 0.00000976535351529728);
  cpg_update_y_discrete(0, 0.09690183345156239136);
  cpg_update_ox_cvxpy(0, 0.50000349535704546877);
  cpg_update_ou_cvxpy(0, -0.25200540617738997895);
  cpg_update_etta(0.00097656250000000000);
  cpg_update_inv_Jb_S_b_scaling(0, 0.17456442870571628467);
  cpg_update_inv_Jb_c_b_scaling(0, -0.08571101675412967635);
  cpg_update_omega_max(0.17453292519943294780);
  cpg_update_S_u_scaling(0, 0.20000000000000001110);
  cpg_update_c_u_scaling(0, -0.10000000000000000555);
  cpg_update_m_max(0.20000000000000001110);
  cpg_set_solver_maxit(50);
    // Solve the problem instance
  cpg_solve();

      double start = clock();
  cpg_solve();
  double  end = clock();

  double cpu_time_used = ((double)(end - start)) / CLOCKS_PER_SEC;

  printf("obj = %f\n", CPG_Result.info->obj_val);
  printf("Solver time = %.1f ms\n", cpu_time_used*1000);
  

  return 0;

}
