
/*
Auto-generated by CVXPYgen on July 06, 2026 at 07:41:35
Content: Function definitions
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_tau(cpg_float val){
  cpg_params_vec[0] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_tau_lamb(cpg_float val){
  cpg_params_vec[1] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_start_pos(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_end_pos(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+9] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_A_discrete(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+16] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_discrete(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1486] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_y_discrete(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2326] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_ox_cvxpy(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2536] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_ou_cvxpy(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2753] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_etta(cpg_float val){
  cpg_params_vec[2873] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_inv_Jb_S_b_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2874] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_inv_Jb_c_b_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2883] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_omegab_max(cpg_float val){
  cpg_params_vec[2886] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_S_u_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2887] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_c_u_scaling(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2903] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_Fth_max(cpg_float val){
  cpg_params_vec[2907] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<2744; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<224; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

void cpg_canonicalize_G(){
  for(i=0; i<4585; i++){
    Canon_Params.G->x[i] = 0;
    for(j=canon_G_map.p[i]; j<canon_G_map.p[i+1]; j++){
      Canon_Params.G->x[i] += canon_G_map.x[j]*cpg_params_vec[canon_G_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<2307; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.u[0] = ecos_workspace->x[150];
  CPG_Prim.u[1] = ecos_workspace->x[151];
  CPG_Prim.u[2] = ecos_workspace->x[152];
  CPG_Prim.u[3] = ecos_workspace->x[153];
  CPG_Prim.u[4] = ecos_workspace->x[154];
  CPG_Prim.u[5] = ecos_workspace->x[155];
  CPG_Prim.u[6] = ecos_workspace->x[156];
  CPG_Prim.u[7] = ecos_workspace->x[157];
  CPG_Prim.u[8] = ecos_workspace->x[158];
  CPG_Prim.u[9] = ecos_workspace->x[159];
  CPG_Prim.u[10] = ecos_workspace->x[160];
  CPG_Prim.u[11] = ecos_workspace->x[161];
  CPG_Prim.u[12] = ecos_workspace->x[162];
  CPG_Prim.u[13] = ecos_workspace->x[163];
  CPG_Prim.u[14] = ecos_workspace->x[164];
  CPG_Prim.u[15] = ecos_workspace->x[165];
  CPG_Prim.u[16] = ecos_workspace->x[166];
  CPG_Prim.u[17] = ecos_workspace->x[167];
  CPG_Prim.u[18] = ecos_workspace->x[168];
  CPG_Prim.u[19] = ecos_workspace->x[169];
  CPG_Prim.u[20] = ecos_workspace->x[170];
  CPG_Prim.u[21] = ecos_workspace->x[171];
  CPG_Prim.u[22] = ecos_workspace->x[172];
  CPG_Prim.u[23] = ecos_workspace->x[173];
  CPG_Prim.u[24] = ecos_workspace->x[174];
  CPG_Prim.u[25] = ecos_workspace->x[175];
  CPG_Prim.u[26] = ecos_workspace->x[176];
  CPG_Prim.u[27] = ecos_workspace->x[177];
  CPG_Prim.u[28] = ecos_workspace->x[178];
  CPG_Prim.u[29] = ecos_workspace->x[179];
  CPG_Prim.u[30] = ecos_workspace->x[180];
  CPG_Prim.u[31] = ecos_workspace->x[181];
  CPG_Prim.u[32] = ecos_workspace->x[182];
  CPG_Prim.u[33] = ecos_workspace->x[183];
  CPG_Prim.u[34] = ecos_workspace->x[184];
  CPG_Prim.u[35] = ecos_workspace->x[185];
  CPG_Prim.u[36] = ecos_workspace->x[186];
  CPG_Prim.u[37] = ecos_workspace->x[187];
  CPG_Prim.u[38] = ecos_workspace->x[188];
  CPG_Prim.u[39] = ecos_workspace->x[189];
  CPG_Prim.u[40] = ecos_workspace->x[190];
  CPG_Prim.u[41] = ecos_workspace->x[191];
  CPG_Prim.u[42] = ecos_workspace->x[192];
  CPG_Prim.u[43] = ecos_workspace->x[193];
  CPG_Prim.u[44] = ecos_workspace->x[194];
  CPG_Prim.u[45] = ecos_workspace->x[195];
  CPG_Prim.u[46] = ecos_workspace->x[196];
  CPG_Prim.u[47] = ecos_workspace->x[197];
  CPG_Prim.u[48] = ecos_workspace->x[198];
  CPG_Prim.u[49] = ecos_workspace->x[199];
  CPG_Prim.u[50] = ecos_workspace->x[200];
  CPG_Prim.u[51] = ecos_workspace->x[201];
  CPG_Prim.u[52] = ecos_workspace->x[202];
  CPG_Prim.u[53] = ecos_workspace->x[203];
  CPG_Prim.u[54] = ecos_workspace->x[204];
  CPG_Prim.u[55] = ecos_workspace->x[205];
  CPG_Prim.u[56] = ecos_workspace->x[206];
  CPG_Prim.u[57] = ecos_workspace->x[207];
  CPG_Prim.u[58] = ecos_workspace->x[208];
  CPG_Prim.u[59] = ecos_workspace->x[209];
  CPG_Prim.u[60] = ecos_workspace->x[210];
  CPG_Prim.u[61] = ecos_workspace->x[211];
  CPG_Prim.u[62] = ecos_workspace->x[212];
  CPG_Prim.u[63] = ecos_workspace->x[213];
  CPG_Prim.u[64] = ecos_workspace->x[214];
  CPG_Prim.u[65] = ecos_workspace->x[215];
  CPG_Prim.u[66] = ecos_workspace->x[216];
  CPG_Prim.u[67] = ecos_workspace->x[217];
  CPG_Prim.u[68] = ecos_workspace->x[218];
  CPG_Prim.u[69] = ecos_workspace->x[219];
  CPG_Prim.u[70] = ecos_workspace->x[220];
  CPG_Prim.u[71] = ecos_workspace->x[221];
  CPG_Prim.u[72] = ecos_workspace->x[222];
  CPG_Prim.u[73] = ecos_workspace->x[223];
  CPG_Prim.u[74] = ecos_workspace->x[224];
  CPG_Prim.u[75] = ecos_workspace->x[225];
  CPG_Prim.u[76] = ecos_workspace->x[226];
  CPG_Prim.u[77] = ecos_workspace->x[227];
  CPG_Prim.u[78] = ecos_workspace->x[228];
  CPG_Prim.u[79] = ecos_workspace->x[229];
  CPG_Prim.u[80] = ecos_workspace->x[230];
  CPG_Prim.u[81] = ecos_workspace->x[231];
  CPG_Prim.u[82] = ecos_workspace->x[232];
  CPG_Prim.u[83] = ecos_workspace->x[233];
  CPG_Prim.u[84] = ecos_workspace->x[234];
  CPG_Prim.u[85] = ecos_workspace->x[235];
  CPG_Prim.u[86] = ecos_workspace->x[236];
  CPG_Prim.u[87] = ecos_workspace->x[237];
  CPG_Prim.u[88] = ecos_workspace->x[238];
  CPG_Prim.u[89] = ecos_workspace->x[239];
  CPG_Prim.u[90] = ecos_workspace->x[240];
  CPG_Prim.u[91] = ecos_workspace->x[241];
  CPG_Prim.u[92] = ecos_workspace->x[242];
  CPG_Prim.u[93] = ecos_workspace->x[243];
  CPG_Prim.u[94] = ecos_workspace->x[244];
  CPG_Prim.u[95] = ecos_workspace->x[245];
  CPG_Prim.u[96] = ecos_workspace->x[246];
  CPG_Prim.u[97] = ecos_workspace->x[247];
  CPG_Prim.u[98] = ecos_workspace->x[248];
  CPG_Prim.u[99] = ecos_workspace->x[249];
  CPG_Prim.u[100] = ecos_workspace->x[250];
  CPG_Prim.u[101] = ecos_workspace->x[251];
  CPG_Prim.u[102] = ecos_workspace->x[252];
  CPG_Prim.u[103] = ecos_workspace->x[253];
  CPG_Prim.u[104] = ecos_workspace->x[254];
  CPG_Prim.u[105] = ecos_workspace->x[255];
  CPG_Prim.u[106] = ecos_workspace->x[256];
  CPG_Prim.u[107] = ecos_workspace->x[257];
  CPG_Prim.u[108] = ecos_workspace->x[258];
  CPG_Prim.u[109] = ecos_workspace->x[259];
  CPG_Prim.u[110] = ecos_workspace->x[260];
  CPG_Prim.u[111] = ecos_workspace->x[261];
  CPG_Prim.u[112] = ecos_workspace->x[262];
  CPG_Prim.u[113] = ecos_workspace->x[263];
  CPG_Prim.u[114] = ecos_workspace->x[264];
  CPG_Prim.u[115] = ecos_workspace->x[265];
  CPG_Prim.u[116] = ecos_workspace->x[266];
  CPG_Prim.u[117] = ecos_workspace->x[267];
  CPG_Prim.u[118] = ecos_workspace->x[268];
  CPG_Prim.u[119] = ecos_workspace->x[269];
  CPG_Prim.vc[0] = ecos_workspace->x[390];
  CPG_Prim.vc[1] = ecos_workspace->x[391];
  CPG_Prim.vc[2] = ecos_workspace->x[392];
  CPG_Prim.vc[3] = ecos_workspace->x[393];
  CPG_Prim.vc[4] = ecos_workspace->x[394];
  CPG_Prim.vc[5] = ecos_workspace->x[395];
  CPG_Prim.vc[6] = ecos_workspace->x[396];
  CPG_Prim.vc[7] = ecos_workspace->x[397];
  CPG_Prim.vc[8] = ecos_workspace->x[398];
  CPG_Prim.vc[9] = ecos_workspace->x[399];
  CPG_Prim.vc[10] = ecos_workspace->x[400];
  CPG_Prim.vc[11] = ecos_workspace->x[401];
  CPG_Prim.vc[12] = ecos_workspace->x[402];
  CPG_Prim.vc[13] = ecos_workspace->x[403];
  CPG_Prim.vc[14] = ecos_workspace->x[404];
  CPG_Prim.vc[15] = ecos_workspace->x[405];
  CPG_Prim.vc[16] = ecos_workspace->x[406];
  CPG_Prim.vc[17] = ecos_workspace->x[407];
  CPG_Prim.vc[18] = ecos_workspace->x[408];
  CPG_Prim.vc[19] = ecos_workspace->x[409];
  CPG_Prim.vc[20] = ecos_workspace->x[410];
  CPG_Prim.vc[21] = ecos_workspace->x[411];
  CPG_Prim.vc[22] = ecos_workspace->x[412];
  CPG_Prim.vc[23] = ecos_workspace->x[413];
  CPG_Prim.vc[24] = ecos_workspace->x[414];
  CPG_Prim.vc[25] = ecos_workspace->x[415];
  CPG_Prim.vc[26] = ecos_workspace->x[416];
  CPG_Prim.vc[27] = ecos_workspace->x[417];
  CPG_Prim.vc[28] = ecos_workspace->x[418];
  CPG_Prim.vc[29] = ecos_workspace->x[419];
  CPG_Prim.vc[30] = ecos_workspace->x[420];
  CPG_Prim.vc[31] = ecos_workspace->x[421];
  CPG_Prim.vc[32] = ecos_workspace->x[422];
  CPG_Prim.vc[33] = ecos_workspace->x[423];
  CPG_Prim.vc[34] = ecos_workspace->x[424];
  CPG_Prim.vc[35] = ecos_workspace->x[425];
  CPG_Prim.vc[36] = ecos_workspace->x[426];
  CPG_Prim.vc[37] = ecos_workspace->x[427];
  CPG_Prim.vc[38] = ecos_workspace->x[428];
  CPG_Prim.vc[39] = ecos_workspace->x[429];
  CPG_Prim.vc[40] = ecos_workspace->x[430];
  CPG_Prim.vc[41] = ecos_workspace->x[431];
  CPG_Prim.vc[42] = ecos_workspace->x[432];
  CPG_Prim.vc[43] = ecos_workspace->x[433];
  CPG_Prim.vc[44] = ecos_workspace->x[434];
  CPG_Prim.vc[45] = ecos_workspace->x[435];
  CPG_Prim.vc[46] = ecos_workspace->x[436];
  CPG_Prim.vc[47] = ecos_workspace->x[437];
  CPG_Prim.vc[48] = ecos_workspace->x[438];
  CPG_Prim.vc[49] = ecos_workspace->x[439];
  CPG_Prim.vc[50] = ecos_workspace->x[440];
  CPG_Prim.vc[51] = ecos_workspace->x[441];
  CPG_Prim.vc[52] = ecos_workspace->x[442];
  CPG_Prim.vc[53] = ecos_workspace->x[443];
  CPG_Prim.vc[54] = ecos_workspace->x[444];
  CPG_Prim.vc[55] = ecos_workspace->x[445];
  CPG_Prim.vc[56] = ecos_workspace->x[446];
  CPG_Prim.vc[57] = ecos_workspace->x[447];
  CPG_Prim.vc[58] = ecos_workspace->x[448];
  CPG_Prim.vc[59] = ecos_workspace->x[449];
  CPG_Prim.vc[60] = ecos_workspace->x[450];
  CPG_Prim.vc[61] = ecos_workspace->x[451];
  CPG_Prim.vc[62] = ecos_workspace->x[452];
  CPG_Prim.vc[63] = ecos_workspace->x[453];
  CPG_Prim.vc[64] = ecos_workspace->x[454];
  CPG_Prim.vc[65] = ecos_workspace->x[455];
  CPG_Prim.vc[66] = ecos_workspace->x[456];
  CPG_Prim.vc[67] = ecos_workspace->x[457];
  CPG_Prim.vc[68] = ecos_workspace->x[458];
  CPG_Prim.vc[69] = ecos_workspace->x[459];
  CPG_Prim.vc[70] = ecos_workspace->x[460];
  CPG_Prim.vc[71] = ecos_workspace->x[461];
  CPG_Prim.vc[72] = ecos_workspace->x[462];
  CPG_Prim.vc[73] = ecos_workspace->x[463];
  CPG_Prim.vc[74] = ecos_workspace->x[464];
  CPG_Prim.vc[75] = ecos_workspace->x[465];
  CPG_Prim.vc[76] = ecos_workspace->x[466];
  CPG_Prim.vc[77] = ecos_workspace->x[467];
  CPG_Prim.vc[78] = ecos_workspace->x[468];
  CPG_Prim.vc[79] = ecos_workspace->x[469];
  CPG_Prim.vc[80] = ecos_workspace->x[470];
  CPG_Prim.vc[81] = ecos_workspace->x[471];
  CPG_Prim.vc[82] = ecos_workspace->x[472];
  CPG_Prim.vc[83] = ecos_workspace->x[473];
  CPG_Prim.vc[84] = ecos_workspace->x[474];
  CPG_Prim.vc[85] = ecos_workspace->x[475];
  CPG_Prim.vc[86] = ecos_workspace->x[476];
  CPG_Prim.vc[87] = ecos_workspace->x[477];
  CPG_Prim.vc[88] = ecos_workspace->x[478];
  CPG_Prim.vc[89] = ecos_workspace->x[479];
  CPG_Prim.vc[90] = ecos_workspace->x[480];
  CPG_Prim.vc[91] = ecos_workspace->x[481];
  CPG_Prim.vc[92] = ecos_workspace->x[482];
  CPG_Prim.vc[93] = ecos_workspace->x[483];
  CPG_Prim.vc[94] = ecos_workspace->x[484];
  CPG_Prim.vc[95] = ecos_workspace->x[485];
  CPG_Prim.vc[96] = ecos_workspace->x[486];
  CPG_Prim.vc[97] = ecos_workspace->x[487];
  CPG_Prim.vc[98] = ecos_workspace->x[488];
  CPG_Prim.vc[99] = ecos_workspace->x[489];
  CPG_Prim.vc[100] = ecos_workspace->x[490];
  CPG_Prim.vc[101] = ecos_workspace->x[491];
  CPG_Prim.vc[102] = ecos_workspace->x[492];
  CPG_Prim.vc[103] = ecos_workspace->x[493];
  CPG_Prim.vc[104] = ecos_workspace->x[494];
  CPG_Prim.vc[105] = ecos_workspace->x[495];
  CPG_Prim.vc[106] = ecos_workspace->x[496];
  CPG_Prim.vc[107] = ecos_workspace->x[497];
  CPG_Prim.vc[108] = ecos_workspace->x[498];
  CPG_Prim.vc[109] = ecos_workspace->x[499];
  CPG_Prim.vc[110] = ecos_workspace->x[500];
  CPG_Prim.vc[111] = ecos_workspace->x[501];
  CPG_Prim.vc[112] = ecos_workspace->x[502];
  CPG_Prim.vc[113] = ecos_workspace->x[503];
  CPG_Prim.vc[114] = ecos_workspace->x[504];
  CPG_Prim.vc[115] = ecos_workspace->x[505];
  CPG_Prim.vc[116] = ecos_workspace->x[506];
  CPG_Prim.vc[117] = ecos_workspace->x[507];
  CPG_Prim.vc[118] = ecos_workspace->x[508];
  CPG_Prim.vc[119] = ecos_workspace->x[509];
  CPG_Prim.vc[120] = ecos_workspace->x[510];
  CPG_Prim.vc[121] = ecos_workspace->x[511];
  CPG_Prim.vc[122] = ecos_workspace->x[512];
  CPG_Prim.vc[123] = ecos_workspace->x[513];
  CPG_Prim.vc[124] = ecos_workspace->x[514];
  CPG_Prim.vc[125] = ecos_workspace->x[515];
  CPG_Prim.vc[126] = ecos_workspace->x[516];
  CPG_Prim.vc[127] = ecos_workspace->x[517];
  CPG_Prim.vc[128] = ecos_workspace->x[518];
  CPG_Prim.vc[129] = ecos_workspace->x[519];
  CPG_Prim.vc[130] = ecos_workspace->x[520];
  CPG_Prim.vc[131] = ecos_workspace->x[521];
  CPG_Prim.vc[132] = ecos_workspace->x[522];
  CPG_Prim.vc[133] = ecos_workspace->x[523];
  CPG_Prim.vc[134] = ecos_workspace->x[524];
  CPG_Prim.vc[135] = ecos_workspace->x[525];
  CPG_Prim.vc[136] = ecos_workspace->x[526];
  CPG_Prim.vc[137] = ecos_workspace->x[527];
  CPG_Prim.vc[138] = ecos_workspace->x[528];
  CPG_Prim.vc[139] = ecos_workspace->x[529];
  CPG_Prim.vc[140] = ecos_workspace->x[530];
  CPG_Prim.vc[141] = ecos_workspace->x[531];
  CPG_Prim.vc[142] = ecos_workspace->x[532];
  CPG_Prim.vc[143] = ecos_workspace->x[533];
  CPG_Prim.vc[144] = ecos_workspace->x[534];
  CPG_Prim.vc[145] = ecos_workspace->x[535];
  CPG_Prim.vc[146] = ecos_workspace->x[536];
  CPG_Prim.vc[147] = ecos_workspace->x[537];
  CPG_Prim.vc[148] = ecos_workspace->x[538];
  CPG_Prim.vc[149] = ecos_workspace->x[539];
  CPG_Prim.vc[150] = ecos_workspace->x[540];
  CPG_Prim.vc[151] = ecos_workspace->x[541];
  CPG_Prim.vc[152] = ecos_workspace->x[542];
  CPG_Prim.vc[153] = ecos_workspace->x[543];
  CPG_Prim.vc[154] = ecos_workspace->x[544];
  CPG_Prim.vc[155] = ecos_workspace->x[545];
  CPG_Prim.vc[156] = ecos_workspace->x[546];
  CPG_Prim.vc[157] = ecos_workspace->x[547];
  CPG_Prim.vc[158] = ecos_workspace->x[548];
  CPG_Prim.vc[159] = ecos_workspace->x[549];
  CPG_Prim.vc[160] = ecos_workspace->x[550];
  CPG_Prim.vc[161] = ecos_workspace->x[551];
  CPG_Prim.vc[162] = ecos_workspace->x[552];
  CPG_Prim.vc[163] = ecos_workspace->x[553];
  CPG_Prim.vc[164] = ecos_workspace->x[554];
  CPG_Prim.vc[165] = ecos_workspace->x[555];
  CPG_Prim.vc[166] = ecos_workspace->x[556];
  CPG_Prim.vc[167] = ecos_workspace->x[557];
  CPG_Prim.vc[168] = ecos_workspace->x[558];
  CPG_Prim.vc[169] = ecos_workspace->x[559];
  CPG_Prim.vc[170] = ecos_workspace->x[560];
  CPG_Prim.vc[171] = ecos_workspace->x[561];
  CPG_Prim.vc[172] = ecos_workspace->x[562];
  CPG_Prim.vc[173] = ecos_workspace->x[563];
  CPG_Prim.vc[174] = ecos_workspace->x[564];
  CPG_Prim.vc[175] = ecos_workspace->x[565];
  CPG_Prim.vc[176] = ecos_workspace->x[566];
  CPG_Prim.vc[177] = ecos_workspace->x[567];
  CPG_Prim.vc[178] = ecos_workspace->x[568];
  CPG_Prim.vc[179] = ecos_workspace->x[569];
  CPG_Prim.vc[180] = ecos_workspace->x[570];
  CPG_Prim.vc[181] = ecos_workspace->x[571];
  CPG_Prim.vc[182] = ecos_workspace->x[572];
  CPG_Prim.vc[183] = ecos_workspace->x[573];
  CPG_Prim.vc[184] = ecos_workspace->x[574];
  CPG_Prim.vc[185] = ecos_workspace->x[575];
  CPG_Prim.vc[186] = ecos_workspace->x[576];
  CPG_Prim.vc[187] = ecos_workspace->x[577];
  CPG_Prim.vc[188] = ecos_workspace->x[578];
  CPG_Prim.vc[189] = ecos_workspace->x[579];
  CPG_Prim.vc[190] = ecos_workspace->x[580];
  CPG_Prim.vc[191] = ecos_workspace->x[581];
  CPG_Prim.vc[192] = ecos_workspace->x[582];
  CPG_Prim.vc[193] = ecos_workspace->x[583];
  CPG_Prim.vc[194] = ecos_workspace->x[584];
  CPG_Prim.vc[195] = ecos_workspace->x[585];
  CPG_Prim.vc[196] = ecos_workspace->x[586];
  CPG_Prim.vc[197] = ecos_workspace->x[587];
  CPG_Prim.vc[198] = ecos_workspace->x[588];
  CPG_Prim.vc[199] = ecos_workspace->x[589];
  CPG_Prim.vc[200] = ecos_workspace->x[590];
  CPG_Prim.vc[201] = ecos_workspace->x[591];
  CPG_Prim.vc[202] = ecos_workspace->x[592];
  CPG_Prim.vc[203] = ecos_workspace->x[593];
  CPG_Prim.vc[204] = ecos_workspace->x[594];
  CPG_Prim.vc[205] = ecos_workspace->x[595];
  CPG_Prim.vc[206] = ecos_workspace->x[596];
  CPG_Prim.vc[207] = ecos_workspace->x[597];
  CPG_Prim.vc[208] = ecos_workspace->x[598];
  CPG_Prim.vc[209] = ecos_workspace->x[599];
  CPG_Prim.x[0] = ecos_workspace->x[810];
  CPG_Prim.x[1] = ecos_workspace->x[811];
  CPG_Prim.x[2] = ecos_workspace->x[812];
  CPG_Prim.x[3] = ecos_workspace->x[813];
  CPG_Prim.x[4] = ecos_workspace->x[814];
  CPG_Prim.x[5] = ecos_workspace->x[815];
  CPG_Prim.x[6] = ecos_workspace->x[816];
  CPG_Prim.x[7] = ecos_workspace->x[817];
  CPG_Prim.x[8] = ecos_workspace->x[818];
  CPG_Prim.x[9] = ecos_workspace->x[819];
  CPG_Prim.x[10] = ecos_workspace->x[820];
  CPG_Prim.x[11] = ecos_workspace->x[821];
  CPG_Prim.x[12] = ecos_workspace->x[822];
  CPG_Prim.x[13] = ecos_workspace->x[823];
  CPG_Prim.x[14] = ecos_workspace->x[824];
  CPG_Prim.x[15] = ecos_workspace->x[825];
  CPG_Prim.x[16] = ecos_workspace->x[826];
  CPG_Prim.x[17] = ecos_workspace->x[827];
  CPG_Prim.x[18] = ecos_workspace->x[828];
  CPG_Prim.x[19] = ecos_workspace->x[829];
  CPG_Prim.x[20] = ecos_workspace->x[830];
  CPG_Prim.x[21] = ecos_workspace->x[831];
  CPG_Prim.x[22] = ecos_workspace->x[832];
  CPG_Prim.x[23] = ecos_workspace->x[833];
  CPG_Prim.x[24] = ecos_workspace->x[834];
  CPG_Prim.x[25] = ecos_workspace->x[835];
  CPG_Prim.x[26] = ecos_workspace->x[836];
  CPG_Prim.x[27] = ecos_workspace->x[837];
  CPG_Prim.x[28] = ecos_workspace->x[838];
  CPG_Prim.x[29] = ecos_workspace->x[839];
  CPG_Prim.x[30] = ecos_workspace->x[840];
  CPG_Prim.x[31] = ecos_workspace->x[841];
  CPG_Prim.x[32] = ecos_workspace->x[842];
  CPG_Prim.x[33] = ecos_workspace->x[843];
  CPG_Prim.x[34] = ecos_workspace->x[844];
  CPG_Prim.x[35] = ecos_workspace->x[845];
  CPG_Prim.x[36] = ecos_workspace->x[846];
  CPG_Prim.x[37] = ecos_workspace->x[847];
  CPG_Prim.x[38] = ecos_workspace->x[848];
  CPG_Prim.x[39] = ecos_workspace->x[849];
  CPG_Prim.x[40] = ecos_workspace->x[850];
  CPG_Prim.x[41] = ecos_workspace->x[851];
  CPG_Prim.x[42] = ecos_workspace->x[852];
  CPG_Prim.x[43] = ecos_workspace->x[853];
  CPG_Prim.x[44] = ecos_workspace->x[854];
  CPG_Prim.x[45] = ecos_workspace->x[855];
  CPG_Prim.x[46] = ecos_workspace->x[856];
  CPG_Prim.x[47] = ecos_workspace->x[857];
  CPG_Prim.x[48] = ecos_workspace->x[858];
  CPG_Prim.x[49] = ecos_workspace->x[859];
  CPG_Prim.x[50] = ecos_workspace->x[860];
  CPG_Prim.x[51] = ecos_workspace->x[861];
  CPG_Prim.x[52] = ecos_workspace->x[862];
  CPG_Prim.x[53] = ecos_workspace->x[863];
  CPG_Prim.x[54] = ecos_workspace->x[864];
  CPG_Prim.x[55] = ecos_workspace->x[865];
  CPG_Prim.x[56] = ecos_workspace->x[866];
  CPG_Prim.x[57] = ecos_workspace->x[867];
  CPG_Prim.x[58] = ecos_workspace->x[868];
  CPG_Prim.x[59] = ecos_workspace->x[869];
  CPG_Prim.x[60] = ecos_workspace->x[870];
  CPG_Prim.x[61] = ecos_workspace->x[871];
  CPG_Prim.x[62] = ecos_workspace->x[872];
  CPG_Prim.x[63] = ecos_workspace->x[873];
  CPG_Prim.x[64] = ecos_workspace->x[874];
  CPG_Prim.x[65] = ecos_workspace->x[875];
  CPG_Prim.x[66] = ecos_workspace->x[876];
  CPG_Prim.x[67] = ecos_workspace->x[877];
  CPG_Prim.x[68] = ecos_workspace->x[878];
  CPG_Prim.x[69] = ecos_workspace->x[879];
  CPG_Prim.x[70] = ecos_workspace->x[880];
  CPG_Prim.x[71] = ecos_workspace->x[881];
  CPG_Prim.x[72] = ecos_workspace->x[882];
  CPG_Prim.x[73] = ecos_workspace->x[883];
  CPG_Prim.x[74] = ecos_workspace->x[884];
  CPG_Prim.x[75] = ecos_workspace->x[885];
  CPG_Prim.x[76] = ecos_workspace->x[886];
  CPG_Prim.x[77] = ecos_workspace->x[887];
  CPG_Prim.x[78] = ecos_workspace->x[888];
  CPG_Prim.x[79] = ecos_workspace->x[889];
  CPG_Prim.x[80] = ecos_workspace->x[890];
  CPG_Prim.x[81] = ecos_workspace->x[891];
  CPG_Prim.x[82] = ecos_workspace->x[892];
  CPG_Prim.x[83] = ecos_workspace->x[893];
  CPG_Prim.x[84] = ecos_workspace->x[894];
  CPG_Prim.x[85] = ecos_workspace->x[895];
  CPG_Prim.x[86] = ecos_workspace->x[896];
  CPG_Prim.x[87] = ecos_workspace->x[897];
  CPG_Prim.x[88] = ecos_workspace->x[898];
  CPG_Prim.x[89] = ecos_workspace->x[899];
  CPG_Prim.x[90] = ecos_workspace->x[900];
  CPG_Prim.x[91] = ecos_workspace->x[901];
  CPG_Prim.x[92] = ecos_workspace->x[902];
  CPG_Prim.x[93] = ecos_workspace->x[903];
  CPG_Prim.x[94] = ecos_workspace->x[904];
  CPG_Prim.x[95] = ecos_workspace->x[905];
  CPG_Prim.x[96] = ecos_workspace->x[906];
  CPG_Prim.x[97] = ecos_workspace->x[907];
  CPG_Prim.x[98] = ecos_workspace->x[908];
  CPG_Prim.x[99] = ecos_workspace->x[909];
  CPG_Prim.x[100] = ecos_workspace->x[910];
  CPG_Prim.x[101] = ecos_workspace->x[911];
  CPG_Prim.x[102] = ecos_workspace->x[912];
  CPG_Prim.x[103] = ecos_workspace->x[913];
  CPG_Prim.x[104] = ecos_workspace->x[914];
  CPG_Prim.x[105] = ecos_workspace->x[915];
  CPG_Prim.x[106] = ecos_workspace->x[916];
  CPG_Prim.x[107] = ecos_workspace->x[917];
  CPG_Prim.x[108] = ecos_workspace->x[918];
  CPG_Prim.x[109] = ecos_workspace->x[919];
  CPG_Prim.x[110] = ecos_workspace->x[920];
  CPG_Prim.x[111] = ecos_workspace->x[921];
  CPG_Prim.x[112] = ecos_workspace->x[922];
  CPG_Prim.x[113] = ecos_workspace->x[923];
  CPG_Prim.x[114] = ecos_workspace->x[924];
  CPG_Prim.x[115] = ecos_workspace->x[925];
  CPG_Prim.x[116] = ecos_workspace->x[926];
  CPG_Prim.x[117] = ecos_workspace->x[927];
  CPG_Prim.x[118] = ecos_workspace->x[928];
  CPG_Prim.x[119] = ecos_workspace->x[929];
  CPG_Prim.x[120] = ecos_workspace->x[930];
  CPG_Prim.x[121] = ecos_workspace->x[931];
  CPG_Prim.x[122] = ecos_workspace->x[932];
  CPG_Prim.x[123] = ecos_workspace->x[933];
  CPG_Prim.x[124] = ecos_workspace->x[934];
  CPG_Prim.x[125] = ecos_workspace->x[935];
  CPG_Prim.x[126] = ecos_workspace->x[936];
  CPG_Prim.x[127] = ecos_workspace->x[937];
  CPG_Prim.x[128] = ecos_workspace->x[938];
  CPG_Prim.x[129] = ecos_workspace->x[939];
  CPG_Prim.x[130] = ecos_workspace->x[940];
  CPG_Prim.x[131] = ecos_workspace->x[941];
  CPG_Prim.x[132] = ecos_workspace->x[942];
  CPG_Prim.x[133] = ecos_workspace->x[943];
  CPG_Prim.x[134] = ecos_workspace->x[944];
  CPG_Prim.x[135] = ecos_workspace->x[945];
  CPG_Prim.x[136] = ecos_workspace->x[946];
  CPG_Prim.x[137] = ecos_workspace->x[947];
  CPG_Prim.x[138] = ecos_workspace->x[948];
  CPG_Prim.x[139] = ecos_workspace->x[949];
  CPG_Prim.x[140] = ecos_workspace->x[950];
  CPG_Prim.x[141] = ecos_workspace->x[951];
  CPG_Prim.x[142] = ecos_workspace->x[952];
  CPG_Prim.x[143] = ecos_workspace->x[953];
  CPG_Prim.x[144] = ecos_workspace->x[954];
  CPG_Prim.x[145] = ecos_workspace->x[955];
  CPG_Prim.x[146] = ecos_workspace->x[956];
  CPG_Prim.x[147] = ecos_workspace->x[957];
  CPG_Prim.x[148] = ecos_workspace->x[958];
  CPG_Prim.x[149] = ecos_workspace->x[959];
  CPG_Prim.x[150] = ecos_workspace->x[960];
  CPG_Prim.x[151] = ecos_workspace->x[961];
  CPG_Prim.x[152] = ecos_workspace->x[962];
  CPG_Prim.x[153] = ecos_workspace->x[963];
  CPG_Prim.x[154] = ecos_workspace->x[964];
  CPG_Prim.x[155] = ecos_workspace->x[965];
  CPG_Prim.x[156] = ecos_workspace->x[966];
  CPG_Prim.x[157] = ecos_workspace->x[967];
  CPG_Prim.x[158] = ecos_workspace->x[968];
  CPG_Prim.x[159] = ecos_workspace->x[969];
  CPG_Prim.x[160] = ecos_workspace->x[970];
  CPG_Prim.x[161] = ecos_workspace->x[971];
  CPG_Prim.x[162] = ecos_workspace->x[972];
  CPG_Prim.x[163] = ecos_workspace->x[973];
  CPG_Prim.x[164] = ecos_workspace->x[974];
  CPG_Prim.x[165] = ecos_workspace->x[975];
  CPG_Prim.x[166] = ecos_workspace->x[976];
  CPG_Prim.x[167] = ecos_workspace->x[977];
  CPG_Prim.x[168] = ecos_workspace->x[978];
  CPG_Prim.x[169] = ecos_workspace->x[979];
  CPG_Prim.x[170] = ecos_workspace->x[980];
  CPG_Prim.x[171] = ecos_workspace->x[981];
  CPG_Prim.x[172] = ecos_workspace->x[982];
  CPG_Prim.x[173] = ecos_workspace->x[983];
  CPG_Prim.x[174] = ecos_workspace->x[984];
  CPG_Prim.x[175] = ecos_workspace->x[985];
  CPG_Prim.x[176] = ecos_workspace->x[986];
  CPG_Prim.x[177] = ecos_workspace->x[987];
  CPG_Prim.x[178] = ecos_workspace->x[988];
  CPG_Prim.x[179] = ecos_workspace->x[989];
  CPG_Prim.x[180] = ecos_workspace->x[990];
  CPG_Prim.x[181] = ecos_workspace->x[991];
  CPG_Prim.x[182] = ecos_workspace->x[992];
  CPG_Prim.x[183] = ecos_workspace->x[993];
  CPG_Prim.x[184] = ecos_workspace->x[994];
  CPG_Prim.x[185] = ecos_workspace->x[995];
  CPG_Prim.x[186] = ecos_workspace->x[996];
  CPG_Prim.x[187] = ecos_workspace->x[997];
  CPG_Prim.x[188] = ecos_workspace->x[998];
  CPG_Prim.x[189] = ecos_workspace->x[999];
  CPG_Prim.x[190] = ecos_workspace->x[1000];
  CPG_Prim.x[191] = ecos_workspace->x[1001];
  CPG_Prim.x[192] = ecos_workspace->x[1002];
  CPG_Prim.x[193] = ecos_workspace->x[1003];
  CPG_Prim.x[194] = ecos_workspace->x[1004];
  CPG_Prim.x[195] = ecos_workspace->x[1005];
  CPG_Prim.x[196] = ecos_workspace->x[1006];
  CPG_Prim.x[197] = ecos_workspace->x[1007];
  CPG_Prim.x[198] = ecos_workspace->x[1008];
  CPG_Prim.x[199] = ecos_workspace->x[1009];
  CPG_Prim.x[200] = ecos_workspace->x[1010];
  CPG_Prim.x[201] = ecos_workspace->x[1011];
  CPG_Prim.x[202] = ecos_workspace->x[1012];
  CPG_Prim.x[203] = ecos_workspace->x[1013];
  CPG_Prim.x[204] = ecos_workspace->x[1014];
  CPG_Prim.x[205] = ecos_workspace->x[1015];
  CPG_Prim.x[206] = ecos_workspace->x[1016];
  CPG_Prim.x[207] = ecos_workspace->x[1017];
  CPG_Prim.x[208] = ecos_workspace->x[1018];
  CPG_Prim.x[209] = ecos_workspace->x[1019];
  CPG_Prim.x[210] = ecos_workspace->x[1020];
  CPG_Prim.x[211] = ecos_workspace->x[1021];
  CPG_Prim.x[212] = ecos_workspace->x[1022];
  CPG_Prim.x[213] = ecos_workspace->x[1023];
  CPG_Prim.x[214] = ecos_workspace->x[1024];
  CPG_Prim.x[215] = ecos_workspace->x[1025];
  CPG_Prim.x[216] = ecos_workspace->x[1026];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = ecos_workspace->y[0];
  CPG_Dual.d0[1] = ecos_workspace->y[1];
  CPG_Dual.d0[2] = ecos_workspace->y[2];
  CPG_Dual.d0[3] = ecos_workspace->y[3];
  CPG_Dual.d0[4] = ecos_workspace->y[4];
  CPG_Dual.d0[5] = ecos_workspace->y[5];
  CPG_Dual.d0[6] = ecos_workspace->y[6];
  CPG_Dual.d1[0] = ecos_workspace->y[7];
  CPG_Dual.d1[1] = ecos_workspace->y[8];
  CPG_Dual.d1[2] = ecos_workspace->y[9];
  CPG_Dual.d1[3] = ecos_workspace->y[10];
  CPG_Dual.d1[4] = ecos_workspace->y[11];
  CPG_Dual.d1[5] = ecos_workspace->y[12];
  CPG_Dual.d1[6] = ecos_workspace->y[13];
  CPG_Dual.d2[0] = ecos_workspace->y[14];
  CPG_Dual.d2[1] = ecos_workspace->y[15];
  CPG_Dual.d2[2] = ecos_workspace->y[16];
  CPG_Dual.d2[3] = ecos_workspace->y[17];
  CPG_Dual.d2[4] = ecos_workspace->y[18];
  CPG_Dual.d2[5] = ecos_workspace->y[19];
  CPG_Dual.d2[6] = ecos_workspace->y[20];
  CPG_Dual.d3[0] = ecos_workspace->y[21];
  CPG_Dual.d3[1] = ecos_workspace->y[22];
  CPG_Dual.d3[2] = ecos_workspace->y[23];
  CPG_Dual.d3[3] = ecos_workspace->y[24];
  CPG_Dual.d3[4] = ecos_workspace->y[25];
  CPG_Dual.d3[5] = ecos_workspace->y[26];
  CPG_Dual.d3[6] = ecos_workspace->y[27];
  CPG_Dual.d4[0] = ecos_workspace->y[28];
  CPG_Dual.d4[1] = ecos_workspace->y[29];
  CPG_Dual.d4[2] = ecos_workspace->y[30];
  CPG_Dual.d4[3] = ecos_workspace->y[31];
  CPG_Dual.d4[4] = ecos_workspace->y[32];
  CPG_Dual.d4[5] = ecos_workspace->y[33];
  CPG_Dual.d4[6] = ecos_workspace->y[34];
  CPG_Dual.d5[0] = ecos_workspace->y[35];
  CPG_Dual.d5[1] = ecos_workspace->y[36];
  CPG_Dual.d5[2] = ecos_workspace->y[37];
  CPG_Dual.d5[3] = ecos_workspace->y[38];
  CPG_Dual.d5[4] = ecos_workspace->y[39];
  CPG_Dual.d5[5] = ecos_workspace->y[40];
  CPG_Dual.d5[6] = ecos_workspace->y[41];
  CPG_Dual.d6[0] = ecos_workspace->y[42];
  CPG_Dual.d6[1] = ecos_workspace->y[43];
  CPG_Dual.d6[2] = ecos_workspace->y[44];
  CPG_Dual.d6[3] = ecos_workspace->y[45];
  CPG_Dual.d6[4] = ecos_workspace->y[46];
  CPG_Dual.d6[5] = ecos_workspace->y[47];
  CPG_Dual.d6[6] = ecos_workspace->y[48];
  CPG_Dual.d7[0] = ecos_workspace->y[49];
  CPG_Dual.d7[1] = ecos_workspace->y[50];
  CPG_Dual.d7[2] = ecos_workspace->y[51];
  CPG_Dual.d7[3] = ecos_workspace->y[52];
  CPG_Dual.d7[4] = ecos_workspace->y[53];
  CPG_Dual.d7[5] = ecos_workspace->y[54];
  CPG_Dual.d7[6] = ecos_workspace->y[55];
  CPG_Dual.d8[0] = ecos_workspace->y[56];
  CPG_Dual.d8[1] = ecos_workspace->y[57];
  CPG_Dual.d8[2] = ecos_workspace->y[58];
  CPG_Dual.d8[3] = ecos_workspace->y[59];
  CPG_Dual.d8[4] = ecos_workspace->y[60];
  CPG_Dual.d8[5] = ecos_workspace->y[61];
  CPG_Dual.d8[6] = ecos_workspace->y[62];
  CPG_Dual.d9[0] = ecos_workspace->y[63];
  CPG_Dual.d9[1] = ecos_workspace->y[64];
  CPG_Dual.d9[2] = ecos_workspace->y[65];
  CPG_Dual.d9[3] = ecos_workspace->y[66];
  CPG_Dual.d9[4] = ecos_workspace->y[67];
  CPG_Dual.d9[5] = ecos_workspace->y[68];
  CPG_Dual.d9[6] = ecos_workspace->y[69];
  CPG_Dual.d10[0] = ecos_workspace->y[70];
  CPG_Dual.d10[1] = ecos_workspace->y[71];
  CPG_Dual.d10[2] = ecos_workspace->y[72];
  CPG_Dual.d10[3] = ecos_workspace->y[73];
  CPG_Dual.d10[4] = ecos_workspace->y[74];
  CPG_Dual.d10[5] = ecos_workspace->y[75];
  CPG_Dual.d10[6] = ecos_workspace->y[76];
  CPG_Dual.d11[0] = ecos_workspace->y[77];
  CPG_Dual.d11[1] = ecos_workspace->y[78];
  CPG_Dual.d11[2] = ecos_workspace->y[79];
  CPG_Dual.d11[3] = ecos_workspace->y[80];
  CPG_Dual.d11[4] = ecos_workspace->y[81];
  CPG_Dual.d11[5] = ecos_workspace->y[82];
  CPG_Dual.d11[6] = ecos_workspace->y[83];
  CPG_Dual.d12[0] = ecos_workspace->y[84];
  CPG_Dual.d12[1] = ecos_workspace->y[85];
  CPG_Dual.d12[2] = ecos_workspace->y[86];
  CPG_Dual.d12[3] = ecos_workspace->y[87];
  CPG_Dual.d12[4] = ecos_workspace->y[88];
  CPG_Dual.d12[5] = ecos_workspace->y[89];
  CPG_Dual.d12[6] = ecos_workspace->y[90];
  CPG_Dual.d13[0] = ecos_workspace->y[91];
  CPG_Dual.d13[1] = ecos_workspace->y[92];
  CPG_Dual.d13[2] = ecos_workspace->y[93];
  CPG_Dual.d13[3] = ecos_workspace->y[94];
  CPG_Dual.d13[4] = ecos_workspace->y[95];
  CPG_Dual.d13[5] = ecos_workspace->y[96];
  CPG_Dual.d13[6] = ecos_workspace->y[97];
  CPG_Dual.d14[0] = ecos_workspace->y[98];
  CPG_Dual.d14[1] = ecos_workspace->y[99];
  CPG_Dual.d14[2] = ecos_workspace->y[100];
  CPG_Dual.d14[3] = ecos_workspace->y[101];
  CPG_Dual.d14[4] = ecos_workspace->y[102];
  CPG_Dual.d14[5] = ecos_workspace->y[103];
  CPG_Dual.d14[6] = ecos_workspace->y[104];
  CPG_Dual.d15[0] = ecos_workspace->y[105];
  CPG_Dual.d15[1] = ecos_workspace->y[106];
  CPG_Dual.d15[2] = ecos_workspace->y[107];
  CPG_Dual.d15[3] = ecos_workspace->y[108];
  CPG_Dual.d15[4] = ecos_workspace->y[109];
  CPG_Dual.d15[5] = ecos_workspace->y[110];
  CPG_Dual.d15[6] = ecos_workspace->y[111];
  CPG_Dual.d16[0] = ecos_workspace->y[112];
  CPG_Dual.d16[1] = ecos_workspace->y[113];
  CPG_Dual.d16[2] = ecos_workspace->y[114];
  CPG_Dual.d16[3] = ecos_workspace->y[115];
  CPG_Dual.d16[4] = ecos_workspace->y[116];
  CPG_Dual.d16[5] = ecos_workspace->y[117];
  CPG_Dual.d16[6] = ecos_workspace->y[118];
  CPG_Dual.d17[0] = ecos_workspace->y[119];
  CPG_Dual.d17[1] = ecos_workspace->y[120];
  CPG_Dual.d17[2] = ecos_workspace->y[121];
  CPG_Dual.d17[3] = ecos_workspace->y[122];
  CPG_Dual.d17[4] = ecos_workspace->y[123];
  CPG_Dual.d17[5] = ecos_workspace->y[124];
  CPG_Dual.d17[6] = ecos_workspace->y[125];
  CPG_Dual.d18[0] = ecos_workspace->y[126];
  CPG_Dual.d18[1] = ecos_workspace->y[127];
  CPG_Dual.d18[2] = ecos_workspace->y[128];
  CPG_Dual.d18[3] = ecos_workspace->y[129];
  CPG_Dual.d18[4] = ecos_workspace->y[130];
  CPG_Dual.d18[5] = ecos_workspace->y[131];
  CPG_Dual.d18[6] = ecos_workspace->y[132];
  CPG_Dual.d19[0] = ecos_workspace->y[133];
  CPG_Dual.d19[1] = ecos_workspace->y[134];
  CPG_Dual.d19[2] = ecos_workspace->y[135];
  CPG_Dual.d19[3] = ecos_workspace->y[136];
  CPG_Dual.d19[4] = ecos_workspace->y[137];
  CPG_Dual.d19[5] = ecos_workspace->y[138];
  CPG_Dual.d19[6] = ecos_workspace->y[139];
  CPG_Dual.d20[0] = ecos_workspace->y[140];
  CPG_Dual.d20[1] = ecos_workspace->y[141];
  CPG_Dual.d20[2] = ecos_workspace->y[142];
  CPG_Dual.d20[3] = ecos_workspace->y[143];
  CPG_Dual.d20[4] = ecos_workspace->y[144];
  CPG_Dual.d20[5] = ecos_workspace->y[145];
  CPG_Dual.d20[6] = ecos_workspace->y[146];
  CPG_Dual.d21[0] = ecos_workspace->y[147];
  CPG_Dual.d21[1] = ecos_workspace->y[148];
  CPG_Dual.d21[2] = ecos_workspace->y[149];
  CPG_Dual.d21[3] = ecos_workspace->y[150];
  CPG_Dual.d21[4] = ecos_workspace->y[151];
  CPG_Dual.d21[5] = ecos_workspace->y[152];
  CPG_Dual.d21[6] = ecos_workspace->y[153];
  CPG_Dual.d22[0] = ecos_workspace->y[154];
  CPG_Dual.d22[1] = ecos_workspace->y[155];
  CPG_Dual.d22[2] = ecos_workspace->y[156];
  CPG_Dual.d22[3] = ecos_workspace->y[157];
  CPG_Dual.d22[4] = ecos_workspace->y[158];
  CPG_Dual.d22[5] = ecos_workspace->y[159];
  CPG_Dual.d22[6] = ecos_workspace->y[160];
  CPG_Dual.d23[0] = ecos_workspace->y[161];
  CPG_Dual.d23[1] = ecos_workspace->y[162];
  CPG_Dual.d23[2] = ecos_workspace->y[163];
  CPG_Dual.d23[3] = ecos_workspace->y[164];
  CPG_Dual.d23[4] = ecos_workspace->y[165];
  CPG_Dual.d23[5] = ecos_workspace->y[166];
  CPG_Dual.d23[6] = ecos_workspace->y[167];
  CPG_Dual.d24[0] = ecos_workspace->y[168];
  CPG_Dual.d24[1] = ecos_workspace->y[169];
  CPG_Dual.d24[2] = ecos_workspace->y[170];
  CPG_Dual.d24[3] = ecos_workspace->y[171];
  CPG_Dual.d24[4] = ecos_workspace->y[172];
  CPG_Dual.d24[5] = ecos_workspace->y[173];
  CPG_Dual.d24[6] = ecos_workspace->y[174];
  CPG_Dual.d25[0] = ecos_workspace->y[175];
  CPG_Dual.d25[1] = ecos_workspace->y[176];
  CPG_Dual.d25[2] = ecos_workspace->y[177];
  CPG_Dual.d25[3] = ecos_workspace->y[178];
  CPG_Dual.d25[4] = ecos_workspace->y[179];
  CPG_Dual.d25[5] = ecos_workspace->y[180];
  CPG_Dual.d25[6] = ecos_workspace->y[181];
  CPG_Dual.d26[0] = ecos_workspace->y[182];
  CPG_Dual.d26[1] = ecos_workspace->y[183];
  CPG_Dual.d26[2] = ecos_workspace->y[184];
  CPG_Dual.d26[3] = ecos_workspace->y[185];
  CPG_Dual.d26[4] = ecos_workspace->y[186];
  CPG_Dual.d26[5] = ecos_workspace->y[187];
  CPG_Dual.d26[6] = ecos_workspace->y[188];
  CPG_Dual.d27[0] = ecos_workspace->y[189];
  CPG_Dual.d27[1] = ecos_workspace->y[190];
  CPG_Dual.d27[2] = ecos_workspace->y[191];
  CPG_Dual.d27[3] = ecos_workspace->y[192];
  CPG_Dual.d27[4] = ecos_workspace->y[193];
  CPG_Dual.d27[5] = ecos_workspace->y[194];
  CPG_Dual.d27[6] = ecos_workspace->y[195];
  CPG_Dual.d28[0] = ecos_workspace->y[196];
  CPG_Dual.d28[1] = ecos_workspace->y[197];
  CPG_Dual.d28[2] = ecos_workspace->y[198];
  CPG_Dual.d28[3] = ecos_workspace->y[199];
  CPG_Dual.d28[4] = ecos_workspace->y[200];
  CPG_Dual.d28[5] = ecos_workspace->y[201];
  CPG_Dual.d28[6] = ecos_workspace->y[202];
  CPG_Dual.d29[0] = ecos_workspace->y[203];
  CPG_Dual.d29[1] = ecos_workspace->y[204];
  CPG_Dual.d29[2] = ecos_workspace->y[205];
  CPG_Dual.d29[3] = ecos_workspace->y[206];
  CPG_Dual.d29[4] = ecos_workspace->y[207];
  CPG_Dual.d29[5] = ecos_workspace->y[208];
  CPG_Dual.d29[6] = ecos_workspace->y[209];
  CPG_Dual.d30[0] = ecos_workspace->y[210];
  CPG_Dual.d30[1] = ecos_workspace->y[211];
  CPG_Dual.d30[2] = ecos_workspace->y[212];
  CPG_Dual.d30[3] = ecos_workspace->y[213];
  CPG_Dual.d30[4] = ecos_workspace->y[214];
  CPG_Dual.d30[5] = ecos_workspace->y[215];
  CPG_Dual.d30[6] = ecos_workspace->y[216];
  CPG_Dual.d31[0] = ecos_workspace->y[217];
  CPG_Dual.d31[1] = ecos_workspace->y[218];
  CPG_Dual.d31[2] = ecos_workspace->y[219];
  CPG_Dual.d31[3] = ecos_workspace->y[220];
  CPG_Dual.d31[4] = ecos_workspace->y[221];
  CPG_Dual.d31[5] = ecos_workspace->y[222];
  CPG_Dual.d31[6] = ecos_workspace->y[223];
  CPG_Dual.d32 = ecos_workspace->z[843];
  CPG_Dual.d33 = ecos_workspace->z[877];
  CPG_Dual.d34 = ecos_workspace->z[911];
  CPG_Dual.d35 = ecos_workspace->z[945];
  CPG_Dual.d36 = ecos_workspace->z[979];
  CPG_Dual.d37 = ecos_workspace->z[1013];
  CPG_Dual.d38 = ecos_workspace->z[1047];
  CPG_Dual.d39 = ecos_workspace->z[1081];
  CPG_Dual.d40 = ecos_workspace->z[1115];
  CPG_Dual.d41 = ecos_workspace->z[1149];
  CPG_Dual.d42 = ecos_workspace->z[1183];
  CPG_Dual.d43 = ecos_workspace->z[1217];
  CPG_Dual.d44 = ecos_workspace->z[1251];
  CPG_Dual.d45 = ecos_workspace->z[1285];
  CPG_Dual.d46 = ecos_workspace->z[1319];
  CPG_Dual.d47 = ecos_workspace->z[1353];
  CPG_Dual.d48 = ecos_workspace->z[1387];
  CPG_Dual.d49 = ecos_workspace->z[1421];
  CPG_Dual.d50 = ecos_workspace->z[1455];
  CPG_Dual.d51 = ecos_workspace->z[1489];
  CPG_Dual.d52 = ecos_workspace->z[1523];
  CPG_Dual.d53 = ecos_workspace->z[1557];
  CPG_Dual.d54 = ecos_workspace->z[1591];
  CPG_Dual.d55 = ecos_workspace->z[1625];
  CPG_Dual.d56 = ecos_workspace->z[1659];
  CPG_Dual.d57 = ecos_workspace->z[1693];
  CPG_Dual.d58 = ecos_workspace->z[1727];
  CPG_Dual.d59 = ecos_workspace->z[1761];
  CPG_Dual.d60 = ecos_workspace->z[1795];
  CPG_Dual.d61 = ecos_workspace->z[1829];
  CPG_Dual.d62 = ecos_workspace->z[1851];
  CPG_Dual.d63 = ecos_workspace->z[1852];
  CPG_Dual.d64 = ecos_workspace->z[1853];
  CPG_Dual.d65 = ecos_workspace->z[1854];
  CPG_Dual.d66 = ecos_workspace->z[1855];
  CPG_Dual.d67 = ecos_workspace->z[1856];
  CPG_Dual.d68 = ecos_workspace->z[1857];
  CPG_Dual.d69 = ecos_workspace->z[1858];
  CPG_Dual.d70 = ecos_workspace->z[1859];
  CPG_Dual.d71 = ecos_workspace->z[1860];
  CPG_Dual.d72 = ecos_workspace->z[1861];
  CPG_Dual.d73 = ecos_workspace->z[1862];
  CPG_Dual.d74 = ecos_workspace->z[1863];
  CPG_Dual.d75 = ecos_workspace->z[1864];
  CPG_Dual.d76 = ecos_workspace->z[1865];
  CPG_Dual.d77 = ecos_workspace->z[1866];
  CPG_Dual.d78 = ecos_workspace->z[1867];
  CPG_Dual.d79 = ecos_workspace->z[1868];
  CPG_Dual.d80 = ecos_workspace->z[1869];
  CPG_Dual.d81 = ecos_workspace->z[1870];
  CPG_Dual.d82 = ecos_workspace->z[1871];
  CPG_Dual.d83 = ecos_workspace->z[1872];
  CPG_Dual.d84 = ecos_workspace->z[1873];
  CPG_Dual.d85 = ecos_workspace->z[1874];
  CPG_Dual.d86 = ecos_workspace->z[1875];
  CPG_Dual.d87 = ecos_workspace->z[1876];
  CPG_Dual.d88 = ecos_workspace->z[1877];
  CPG_Dual.d89 = ecos_workspace->z[1878];
  CPG_Dual.d90 = ecos_workspace->z[1879];
  CPG_Dual.d91 = ecos_workspace->z[1880];
  CPG_Dual.d92 = ecos_workspace->z[1881];
  CPG_Dual.d93 = ecos_workspace->z[1882];
  CPG_Dual.d94 = ecos_workspace->z[1883];
  CPG_Dual.d95 = ecos_workspace->z[1884];
  CPG_Dual.d96 = ecos_workspace->z[1885];
  CPG_Dual.d97 = ecos_workspace->z[1886];
  CPG_Dual.d98 = ecos_workspace->z[1887];
  CPG_Dual.d99 = ecos_workspace->z[1888];
  CPG_Dual.d100 = ecos_workspace->z[1889];
  CPG_Dual.d101 = ecos_workspace->z[1890];
  CPG_Dual.d102 = ecos_workspace->z[1891];
  CPG_Dual.d103 = ecos_workspace->z[1892];
  CPG_Dual.d104 = ecos_workspace->z[1893];
  CPG_Dual.d105 = ecos_workspace->z[1894];
  CPG_Dual.d106 = ecos_workspace->z[1895];
  CPG_Dual.d107 = ecos_workspace->z[1896];
  CPG_Dual.d108 = ecos_workspace->z[1897];
  CPG_Dual.d109 = ecos_workspace->z[1898];
  CPG_Dual.d110 = ecos_workspace->z[1899];
  CPG_Dual.d111 = ecos_workspace->z[1900];
  CPG_Dual.d112 = ecos_workspace->z[1901];
  CPG_Dual.d113 = ecos_workspace->z[1902];
  CPG_Dual.d114 = ecos_workspace->z[1903];
  CPG_Dual.d115 = ecos_workspace->z[1904];
  CPG_Dual.d116 = ecos_workspace->z[1905];
  CPG_Dual.d117 = ecos_workspace->z[1906];
  CPG_Dual.d118 = ecos_workspace->z[1907];
  CPG_Dual.d119 = ecos_workspace->z[1908];
  CPG_Dual.d120 = ecos_workspace->z[1909];
  CPG_Dual.d121 = ecos_workspace->z[1910];
  CPG_Dual.d122 = ecos_workspace->z[1911];
  CPG_Dual.d123 = ecos_workspace->z[1912];
  CPG_Dual.d124 = ecos_workspace->z[1913];
  CPG_Dual.d125 = ecos_workspace->z[1914];
  CPG_Dual.d126 = ecos_workspace->z[1915];
  CPG_Dual.d127 = ecos_workspace->z[1916];
  CPG_Dual.d128 = ecos_workspace->z[1917];
  CPG_Dual.d129 = ecos_workspace->z[1918];
  CPG_Dual.d130 = ecos_workspace->z[1919];
  CPG_Dual.d131 = ecos_workspace->z[1920];
  CPG_Dual.d132 = ecos_workspace->z[1921];
  CPG_Dual.d133 = ecos_workspace->z[1922];
  CPG_Dual.d134 = ecos_workspace->z[1923];
  CPG_Dual.d135 = ecos_workspace->z[1924];
  CPG_Dual.d136 = ecos_workspace->z[1925];
  CPG_Dual.d137 = ecos_workspace->z[1926];
  CPG_Dual.d138 = ecos_workspace->z[1927];
  CPG_Dual.d139 = ecos_workspace->z[1928];
  CPG_Dual.d140 = ecos_workspace->z[1929];
  CPG_Dual.d141 = ecos_workspace->z[1930];
  CPG_Dual.d142 = ecos_workspace->z[1931];
  CPG_Dual.d143 = ecos_workspace->z[1932];
  CPG_Dual.d144 = ecos_workspace->z[1933];
  CPG_Dual.d145 = ecos_workspace->z[1934];
  CPG_Dual.d146 = ecos_workspace->z[1935];
  CPG_Dual.d147 = ecos_workspace->z[1936];
  CPG_Dual.d148 = ecos_workspace->z[1937];
  CPG_Dual.d149 = ecos_workspace->z[1938];
  CPG_Dual.d150 = ecos_workspace->z[1939];
  CPG_Dual.d151 = ecos_workspace->z[1940];
  CPG_Dual.d152 = ecos_workspace->z[1941];
  CPG_Dual.d153 = ecos_workspace->z[1942];
  CPG_Dual.d154 = ecos_workspace->z[1943];
  CPG_Dual.d155 = ecos_workspace->z[1944];
  CPG_Dual.d156 = ecos_workspace->z[1945];
  CPG_Dual.d157 = ecos_workspace->z[1946];
  CPG_Dual.d158 = ecos_workspace->z[1947];
  CPG_Dual.d159 = ecos_workspace->z[1948];
  CPG_Dual.d160 = ecos_workspace->z[1949];
  CPG_Dual.d161 = ecos_workspace->z[1950];
  CPG_Dual.d162 = ecos_workspace->z[1951];
  CPG_Dual.d163 = ecos_workspace->z[1952];
  CPG_Dual.d164 = ecos_workspace->z[1953];
  CPG_Dual.d165 = ecos_workspace->z[1954];
  CPG_Dual.d166 = ecos_workspace->z[1955];
  CPG_Dual.d167 = ecos_workspace->z[1956];
  CPG_Dual.d168 = ecos_workspace->z[1957];
  CPG_Dual.d169 = ecos_workspace->z[1958];
  CPG_Dual.d170 = ecos_workspace->z[1959];
  CPG_Dual.d171 = ecos_workspace->z[1960];
  CPG_Dual.d172 = ecos_workspace->z[1961];
  CPG_Dual.d173 = ecos_workspace->z[1962];
  CPG_Dual.d174 = ecos_workspace->z[1963];
  CPG_Dual.d175 = ecos_workspace->z[1964];
  CPG_Dual.d176 = ecos_workspace->z[1965];
  CPG_Dual.d177 = ecos_workspace->z[1966];
  CPG_Dual.d178 = ecos_workspace->z[1967];
  CPG_Dual.d179 = ecos_workspace->z[1968];
  CPG_Dual.d180 = ecos_workspace->z[1969];
  CPG_Dual.d181 = ecos_workspace->z[1970];
  CPG_Dual.d182 = ecos_workspace->z[1971];
  CPG_Dual.d183 = ecos_workspace->z[1972];
  CPG_Dual.d184 = ecos_workspace->z[1973];
  CPG_Dual.d185 = ecos_workspace->z[1974];
  CPG_Dual.d186 = ecos_workspace->z[1975];
  CPG_Dual.d187 = ecos_workspace->z[1976];
  CPG_Dual.d188 = ecos_workspace->z[1977];
  CPG_Dual.d189 = ecos_workspace->z[1978];
  CPG_Dual.d190 = ecos_workspace->z[1979];
  CPG_Dual.d191 = ecos_workspace->z[1980];
  CPG_Dual.d192 = ecos_workspace->z[1981];
  CPG_Dual.d193 = ecos_workspace->z[1982];
  CPG_Dual.d194 = ecos_workspace->z[1983];
  CPG_Dual.d195 = ecos_workspace->z[1984];
  CPG_Dual.d196 = ecos_workspace->z[1985];
  CPG_Dual.d197 = ecos_workspace->z[1986];
  CPG_Dual.d198 = ecos_workspace->z[1987];
  CPG_Dual.d199 = ecos_workspace->z[1988];
  CPG_Dual.d200 = ecos_workspace->z[1989];
  CPG_Dual.d201 = ecos_workspace->z[1990];
  CPG_Dual.d202 = ecos_workspace->z[1991];
  CPG_Dual.d203 = ecos_workspace->z[1992];
  CPG_Dual.d204 = ecos_workspace->z[1993];
  CPG_Dual.d205 = ecos_workspace->z[1994];
  CPG_Dual.d206 = ecos_workspace->z[1995];
  CPG_Dual.d207 = ecos_workspace->z[1996];
  CPG_Dual.d208 = ecos_workspace->z[1997];
  CPG_Dual.d209 = ecos_workspace->z[1998];
  CPG_Dual.d210 = ecos_workspace->z[1999];
  CPG_Dual.d211 = ecos_workspace->z[2000];
  CPG_Dual.d212 = ecos_workspace->z[2001];
  CPG_Dual.d213 = ecos_workspace->z[2002];
  CPG_Dual.d214 = ecos_workspace->z[2003];
  CPG_Dual.d215 = ecos_workspace->z[2004];
  CPG_Dual.d216 = ecos_workspace->z[2005];
  CPG_Dual.d217 = ecos_workspace->z[2006];
  CPG_Dual.d218 = ecos_workspace->z[2007];
  CPG_Dual.d219 = ecos_workspace->z[2008];
  CPG_Dual.d220 = ecos_workspace->z[2009];
  CPG_Dual.d221 = ecos_workspace->z[2010];
  CPG_Dual.d222 = ecos_workspace->z[2011];
  CPG_Dual.d223 = ecos_workspace->z[2012];
  CPG_Dual.d224 = ecos_workspace->z[2013];
  CPG_Dual.d225 = ecos_workspace->z[2014];
  CPG_Dual.d226 = ecos_workspace->z[2015];
  CPG_Dual.d227 = ecos_workspace->z[2016];
  CPG_Dual.d228 = ecos_workspace->z[2017];
  CPG_Dual.d229 = ecos_workspace->z[2018];
  CPG_Dual.d230 = ecos_workspace->z[2019];
  CPG_Dual.d231 = ecos_workspace->z[2020];
  CPG_Dual.d232 = ecos_workspace->z[2021];
  CPG_Dual.d233 = ecos_workspace->z[2022];
  CPG_Dual.d234 = ecos_workspace->z[2023];
  CPG_Dual.d235 = ecos_workspace->z[2024];
  CPG_Dual.d236 = ecos_workspace->z[2025];
  CPG_Dual.d237 = ecos_workspace->z[2026];
  CPG_Dual.d238 = ecos_workspace->z[2027];
  CPG_Dual.d239 = ecos_workspace->z[2028];
  CPG_Dual.d240 = ecos_workspace->z[2029];
  CPG_Dual.d241 = ecos_workspace->z[2030];
  CPG_Dual.d242 = ecos_workspace->z[2031];
  CPG_Dual.d243 = ecos_workspace->z[2032];
  CPG_Dual.d244 = ecos_workspace->z[2033];
  CPG_Dual.d245 = ecos_workspace->z[2034];
  CPG_Dual.d246 = ecos_workspace->z[2035];
  CPG_Dual.d247 = ecos_workspace->z[2036];
  CPG_Dual.d248 = ecos_workspace->z[2037];
  CPG_Dual.d249 = ecos_workspace->z[2038];
  CPG_Dual.d250 = ecos_workspace->z[2039];
  CPG_Dual.d251 = ecos_workspace->z[2040];
  CPG_Dual.d252 = ecos_workspace->z[2041];
  CPG_Dual.d253 = ecos_workspace->z[2042];
  CPG_Dual.d254 = ecos_workspace->z[2043];
  CPG_Dual.d255 = ecos_workspace->z[2044];
  CPG_Dual.d256 = ecos_workspace->z[2045];
  CPG_Dual.d257 = ecos_workspace->z[2046];
  CPG_Dual.d258 = ecos_workspace->z[2047];
  CPG_Dual.d259 = ecos_workspace->z[2048];
  CPG_Dual.d260 = ecos_workspace->z[2049];
  CPG_Dual.d261 = ecos_workspace->z[2050];
  CPG_Dual.d262 = ecos_workspace->z[2051];
  CPG_Dual.d263 = ecos_workspace->z[2052];
  CPG_Dual.d264 = ecos_workspace->z[2053];
  CPG_Dual.d265 = ecos_workspace->z[2054];
  CPG_Dual.d266 = ecos_workspace->z[2055];
  CPG_Dual.d267 = ecos_workspace->z[2056];
  CPG_Dual.d268 = ecos_workspace->z[2057];
  CPG_Dual.d269 = ecos_workspace->z[2058];
  CPG_Dual.d270 = ecos_workspace->z[2059];
  CPG_Dual.d271 = ecos_workspace->z[2060];
  CPG_Dual.d272 = ecos_workspace->z[2061];
  CPG_Dual.d273 = ecos_workspace->z[2062];
  CPG_Dual.d274 = ecos_workspace->z[2063];
  CPG_Dual.d275 = ecos_workspace->z[2064];
  CPG_Dual.d276 = ecos_workspace->z[2065];
  CPG_Dual.d277 = ecos_workspace->z[2066];
  CPG_Dual.d278 = ecos_workspace->z[2067];
  CPG_Dual.d279 = ecos_workspace->z[2068];
  CPG_Dual.d280 = ecos_workspace->z[2069];
  CPG_Dual.d281 = ecos_workspace->z[2070];
  CPG_Dual.d282 = ecos_workspace->z[2071];
  CPG_Dual.d283 = ecos_workspace->z[2072];
  CPG_Dual.d284 = ecos_workspace->z[2073];
  CPG_Dual.d285 = ecos_workspace->z[2074];
  CPG_Dual.d286 = ecos_workspace->z[2075];
  CPG_Dual.d287 = ecos_workspace->z[2076];
  CPG_Dual.d288 = ecos_workspace->z[2077];
  CPG_Dual.d289 = ecos_workspace->z[2078];
  CPG_Dual.d290 = ecos_workspace->z[2079];
  CPG_Dual.d291 = ecos_workspace->z[2080];
  CPG_Dual.d292 = ecos_workspace->z[2081];
  CPG_Dual.d293 = ecos_workspace->z[2082];
  CPG_Dual.d294 = ecos_workspace->z[2083];
  CPG_Dual.d295 = ecos_workspace->z[2084];
  CPG_Dual.d296 = ecos_workspace->z[2085];
  CPG_Dual.d297 = ecos_workspace->z[2086];
  CPG_Dual.d298 = ecos_workspace->z[2087];
  CPG_Dual.d299 = ecos_workspace->z[2088];
  CPG_Dual.d300 = ecos_workspace->z[2089];
  CPG_Dual.d301 = ecos_workspace->z[2090];
  CPG_Dual.d302 = ecos_workspace->z[2091];
  CPG_Dual.d303 = ecos_workspace->z[2092];
  CPG_Dual.d304 = ecos_workspace->z[2093];
  CPG_Dual.d305 = ecos_workspace->z[2094];
  CPG_Dual.d306 = ecos_workspace->z[2095];
  CPG_Dual.d307 = ecos_workspace->z[2096];
  CPG_Dual.d308 = ecos_workspace->z[2097];
  CPG_Dual.d309 = ecos_workspace->z[2098];
  CPG_Dual.d310 = ecos_workspace->z[2099];
  CPG_Dual.d311 = ecos_workspace->z[2100];
  CPG_Dual.d312 = ecos_workspace->z[2101];
  CPG_Dual.d313 = ecos_workspace->z[2102];
  CPG_Dual.d314 = ecos_workspace->z[2103];
  CPG_Dual.d315 = ecos_workspace->z[2104];
  CPG_Dual.d316 = ecos_workspace->z[2105];
  CPG_Dual.d317 = ecos_workspace->z[2106];
  CPG_Dual.d318 = ecos_workspace->z[2107];
  CPG_Dual.d319 = ecos_workspace->z[2108];
  CPG_Dual.d320 = ecos_workspace->z[2109];
  CPG_Dual.d321 = ecos_workspace->z[2110];
  CPG_Dual.d322 = ecos_workspace->z[2111];
  CPG_Dual.d323 = ecos_workspace->z[2112];
  CPG_Dual.d324 = ecos_workspace->z[2113];
  CPG_Dual.d325 = ecos_workspace->z[2114];
  CPG_Dual.d326 = ecos_workspace->z[2115];
  CPG_Dual.d327 = ecos_workspace->z[2116];
  CPG_Dual.d328 = ecos_workspace->z[2117];
  CPG_Dual.d329 = ecos_workspace->z[2118];
  CPG_Dual.d330 = ecos_workspace->z[2119];
  CPG_Dual.d331 = ecos_workspace->z[2120];
  CPG_Dual.d332 = ecos_workspace->z[2121];
  CPG_Dual.d333 = ecos_workspace->z[2122];
  CPG_Dual.d334 = ecos_workspace->z[2123];
  CPG_Dual.d335 = ecos_workspace->z[2124];
  CPG_Dual.d336 = ecos_workspace->z[2125];
  CPG_Dual.d337 = ecos_workspace->z[2126];
  CPG_Dual.d338 = ecos_workspace->z[2127];
  CPG_Dual.d339 = ecos_workspace->z[2128];
  CPG_Dual.d340 = ecos_workspace->z[2129];
  CPG_Dual.d341 = ecos_workspace->z[2130];
  CPG_Dual.d342 = ecos_workspace->z[2131];
  CPG_Dual.d343 = ecos_workspace->z[2132];
  CPG_Dual.d344 = ecos_workspace->z[2133];
  CPG_Dual.d345 = ecos_workspace->z[2134];
  CPG_Dual.d346 = ecos_workspace->z[2135];
  CPG_Dual.d347 = ecos_workspace->z[2136];
  CPG_Dual.d348 = ecos_workspace->z[2137];
  CPG_Dual.d349 = ecos_workspace->z[2138];
  CPG_Dual.d350 = ecos_workspace->z[2139];
  CPG_Dual.d351 = ecos_workspace->z[2140];
  CPG_Dual.d352 = ecos_workspace->z[2141];
  CPG_Dual.d353 = ecos_workspace->z[2142];
  CPG_Dual.d354 = ecos_workspace->z[2143];
  CPG_Dual.d355 = ecos_workspace->z[2144];
  CPG_Dual.d356 = ecos_workspace->z[2145];
  CPG_Dual.d357 = ecos_workspace->z[2146];
  CPG_Dual.d358 = ecos_workspace->z[2147];
  CPG_Dual.d359 = ecos_workspace->z[2148];
  CPG_Dual.d360 = ecos_workspace->z[2149];
  CPG_Dual.d361 = ecos_workspace->z[2150];
  CPG_Dual.d362 = ecos_workspace->z[2151];
  CPG_Dual.d363 = ecos_workspace->z[2152];
  CPG_Dual.d364 = ecos_workspace->z[2153];
  CPG_Dual.d365 = ecos_workspace->z[2154];
  CPG_Dual.d366 = ecos_workspace->z[2155];
  CPG_Dual.d367 = ecos_workspace->z[2156];
  CPG_Dual.d368 = ecos_workspace->z[2157];
  CPG_Dual.d369 = ecos_workspace->z[2158];
  CPG_Dual.d370 = ecos_workspace->z[2159];
  CPG_Dual.d371 = ecos_workspace->z[2160];
  CPG_Dual.d372 = ecos_workspace->z[2161];
  CPG_Dual.d373 = ecos_workspace->z[2162];
  CPG_Dual.d374 = ecos_workspace->z[2163];
  CPG_Dual.d375 = ecos_workspace->z[2164];
  CPG_Dual.d376 = ecos_workspace->z[2165];
  CPG_Dual.d377 = ecos_workspace->z[2166];
  CPG_Dual.d378 = ecos_workspace->z[2167];
  CPG_Dual.d379 = ecos_workspace->z[2168];
  CPG_Dual.d380 = ecos_workspace->z[2169];
  CPG_Dual.d381 = ecos_workspace->z[2170];
  CPG_Dual.d382 = ecos_workspace->z[2171];
  CPG_Dual.d383 = ecos_workspace->z[2172];
  CPG_Dual.d384 = ecos_workspace->z[2173];
  CPG_Dual.d385 = ecos_workspace->z[2174];
  CPG_Dual.d386 = ecos_workspace->z[2175];
  CPG_Dual.d387 = ecos_workspace->z[2176];
  CPG_Dual.d388 = ecos_workspace->z[2177];
  CPG_Dual.d389 = ecos_workspace->z[2178];
  CPG_Dual.d390 = ecos_workspace->z[2179];
  CPG_Dual.d391 = ecos_workspace->z[2180];
  CPG_Dual.d392 = ecos_workspace->z[2181];
  CPG_Dual.d393 = ecos_workspace->z[2182];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (ecos_workspace->info->pcost);
  CPG_Info.iter = ecos_workspace->info->iter;
  CPG_Info.status = ecos_flag;
  CPG_Info.pri_res = ecos_workspace->info->pres;
  CPG_Info.dua_res = ecos_workspace->info->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<1456; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<2744; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<224; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<4585; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<2307; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (Canon_Outdated.G) {
    cpg_canonicalize_G();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!ecos_workspace ) {
    cpg_copy_all();
    ecos_workspace = ECOS_setup(1456, 2307, 224, 2183, 31, (int *) &ecos_q, 0, Canon_Params_conditioning.G->x, Canon_Params_conditioning.G->p, Canon_Params_conditioning.G->i, Canon_Params_conditioning.A->x, Canon_Params_conditioning.A->p, Canon_Params_conditioning.A->i, Canon_Params_conditioning.c, Canon_Params_conditioning.h, Canon_Params_conditioning.b);
  } else {
    if (Canon_Outdated.A || Canon_Outdated.b || Canon_Outdated.G) {
      cpg_copy_all();
      ECOS_updateData(ecos_workspace, Canon_Params_conditioning.G->x, Canon_Params_conditioning.A->x, Canon_Params_conditioning.c, Canon_Params_conditioning.h, Canon_Params_conditioning.b);
    } else {
      if (Canon_Outdated.h) {
        cpg_copy_h();
        for (i=0; i<2307; i++) { ecos_updateDataEntry_h(ecos_workspace, i, Canon_Params_conditioning.h[i]); };
      }
    }
  }
  ecos_workspace->stgs->feastol = Canon_Settings.feastol;
  ecos_workspace->stgs->abstol = Canon_Settings.abstol;
  ecos_workspace->stgs->reltol = Canon_Settings.reltol;
  ecos_workspace->stgs->feastol_inacc = Canon_Settings.feastol_inacc;
  ecos_workspace->stgs->abstol_inacc = Canon_Settings.abstol_inacc;
  ecos_workspace->stgs->reltol_inacc = Canon_Settings.reltol_inacc;
  ecos_workspace->stgs->maxit = Canon_Settings.maxit;
  // Solve with ECOS
  ecos_flag = ECOS_solve(ecos_workspace);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
  Canon_Outdated.G = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.feastol = 1e-8;
  Canon_Settings.abstol = 1e-8;
  Canon_Settings.reltol = 1e-8;
  Canon_Settings.feastol_inacc = 1e-4;
  Canon_Settings.abstol_inacc = 5e-5;
  Canon_Settings.reltol_inacc = 5e-5;
  Canon_Settings.maxit = 100;
}

void cpg_set_solver_feastol(cpg_float feastol_new){
  Canon_Settings.feastol = feastol_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_feastol_inacc(cpg_float feastol_inacc_new){
  Canon_Settings.feastol_inacc = feastol_inacc_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_maxit(cpg_int maxit_new){
  Canon_Settings.maxit = maxit_new;
}
