
/*
Auto-generated by CVXPYgen on March 31, 2026 at 23:25:22.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_sqrt_tau(1.82574185835055380345);
  cpg_update_sqrt_alpha_m_sqrt_tau(1.29099444873580582183);
  cpg_update_tau_lamb(33333.33333333333575865254);
  cpg_update_start_pos(0, 0.50000000000000000000);
  cpg_update_end_pos(0, 0.50000000000000000000);
  cpg_update_A_discrete(0, 0.98738065509473293968);
  cpg_update_B_discrete_l(0, 0.00001428323475571563);
  cpg_update_B_discrete_r(0, 0.00000976535351529728);
  cpg_update_y_discrete(0, 0.09690183345156239136);
  cpg_update_ox_cvxpy(0, 0.50000349535704546877);
  cpg_update_ou_cvxpy(0, -0.25200540617738997895);
  cpg_update_etta(0.00097656250000000000);
  cpg_update_inv_Jb_S_b_scaling(0, 0.17456442870571628467);
  cpg_update_inv_Jb_c_b_scaling(0, -0.08571101675412967635);
  cpg_update_omega_max(0.17453292519943294780);
  cpg_update_S_u_scaling(0, 0.20000000000000001110);
  cpg_update_c_u_scaling(0, -0.10000000000000000555);
  cpg_update_m_max(0.20000000000000001110);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<93; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<210; i++) {
    printf("vc[%d] = %f\n", i, CPG_Result.prim->vc[i]);
  }
  for(i=0; i<217; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<7; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<7; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<7; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<7; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<7; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<7; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<7; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<7; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<7; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<7; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<7; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<7; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<7; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<7; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<7; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<7; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<7; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<7; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<7; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<7; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<7; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<7; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  for(i=0; i<7; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  for(i=0; i<7; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<7; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  for(i=0; i<7; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  for(i=0; i<7; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<7; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  printf("d32 = %f\n", CPG_Result.dual->d32);
  printf("d33 = %f\n", CPG_Result.dual->d33);
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  printf("d63 = %f\n", CPG_Result.dual->d63);
  printf("d64 = %f\n", CPG_Result.dual->d64);
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  printf("d73 = %f\n", CPG_Result.dual->d73);
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  printf("d77 = %f\n", CPG_Result.dual->d77);
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  printf("d86 = %f\n", CPG_Result.dual->d86);
  printf("d87 = %f\n", CPG_Result.dual->d87);
  printf("d88 = %f\n", CPG_Result.dual->d88);
  printf("d89 = %f\n", CPG_Result.dual->d89);
  printf("d90 = %f\n", CPG_Result.dual->d90);
  printf("d91 = %f\n", CPG_Result.dual->d91);
  printf("d92 = %f\n", CPG_Result.dual->d92);
  printf("d93 = %f\n", CPG_Result.dual->d93);
  printf("d94 = %f\n", CPG_Result.dual->d94);
  printf("d95 = %f\n", CPG_Result.dual->d95);
  printf("d96 = %f\n", CPG_Result.dual->d96);
  printf("d97 = %f\n", CPG_Result.dual->d97);
  printf("d98 = %f\n", CPG_Result.dual->d98);
  printf("d99 = %f\n", CPG_Result.dual->d99);
  printf("d100 = %f\n", CPG_Result.dual->d100);
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  printf("d109 = %f\n", CPG_Result.dual->d109);
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  printf("d122 = %f\n", CPG_Result.dual->d122);
  printf("d123 = %f\n", CPG_Result.dual->d123);
  printf("d124 = %f\n", CPG_Result.dual->d124);

  return 0;

}
